if (window.MASTER_QUESTION_BANK) {

    // =========================================================================
    // 1. MATEMATIKA UMUM (MATUMU)
    // =========================================================================
    window.MASTER_QUESTION_BANK.matumu[1] = [
        { q: "Bentuk sederhana dari pecahan berpangkat $\\frac{2^{-3} \\cdot 8^{2/3}}{4^{-1}}$ adalah...", options: ["4", "2", "8", "1/2", "1"], correct: 0 },
        { q: "Nilai dari $^{2}\\log 16 + ^{3}\\log 27 - ^{5}\\log 25$ adalah...", options: ["4", "5", "3", "2", "6"], correct: 2 },
        { q: "Hasil rasionalisasi bentuk akar $\\frac{6}{\\sqrt{5} - \\sqrt{2}}$ adalah...", options: ["$3(\\sqrt{5} + \\sqrt{2})$", "$\\sqrt{5} + \\sqrt{2}$", "$6(\\sqrt{5} + \\sqrt{2})$", "$2(\\sqrt{5} - \\sqrt{2})$", "$2(\\sqrt{5} + \\sqrt{2})$"], correct: 4 },
        { q: "Jika $a = 27$ dan $b = 32$, nilai dari $a^{2/3} \\cdot b^{2/5}$ adalah...", options: ["18", "36", "24", "72", "12"], correct: 1 },
        { q: "Bentuk sederhana dari $(x^{-2}y^3)^2 \\cdot (x^3y^{-1})$ adalah...", options: ["$x^1y^5$", "$x^{-1}y^4$", "$x^5y^5$", "$x^{-1}y^5$", "$y^5/x$"], correct: 3 },
        { q: "Nilai dari $^{2}\\log 8 + ^{2}\\log 4 - ^{2}\\log 2$ adalah...", options: ["3", "5", "4", "2", "1"], correct: 2 },
        { q: "Bentuk $\\sqrt{48} - \\sqrt{12} + \\sqrt{27}$ jika disederhanakan menjadi...", options: ["$5\\sqrt{3}$", "$3\\sqrt{3}$", "$4\\sqrt{3}$", "$6\\sqrt{3}$", "$2\\sqrt{3}$"], correct: 0 },
        { q: "Nilai $x$ yang memenuhi $3^{2x-1} = 27$ adalah...", options: ["1", "3", "4", "2", "0"], correct: 3 },
        { q: "Hasil perkalian $(\\sqrt{7} + \\sqrt{3})(\\sqrt{7} - \\sqrt{3})$ adalah...", options: ["10", "4", "21", "4\\sqrt{3}$", "7"], correct: 1 },
        { q: "Bentuk sederhana dari $\\frac{a^3b^{-2}c}{a^{-1}b^2c^3}$ adalah...", options: ["$\\frac{a^2}{b^4c^2}$", "$\\frac{a^4b^4}{c^2}$", "$\\frac{a^4}{c^2}$", "$a^4b^4c^2$", "$\\frac{a^4}{b^4c^2}$"], correct: 4 },
        { q: "Jika $^{3}\\log 2 = p$, maka $^{3}\\log 8$ adalah...", options: ["2p", "p^3", "p+3", "3p", "p/3"], correct: 3 },
        { q: "Bentuk pangkat positif dari $\\frac{x^{-3}y^2}{z^{-4}}$ adalah...", options: ["$\\frac{x^3y^2}{z^4}$", "$\\frac{y^2z^4}{x^3}$", "$\\frac{z^4}{x^3y^2}$", "$x^3y^2z^4$", "$\\frac{y^2}{x^3z^4}$"], correct: 1 },
        { q: "Nilai dari $\\sqrt{0.000081}$ adalah...", options: ["0.009", "0.09", "0.9", "0.0009", "0.00009"], correct: 0 },
        { q: "Nilai $x$ dari $^{x}\\log 81 = 4$ adalah...", options: ["9", "2", "4", "81", "3"], correct: 4 },
        { q: "Bentuk sederhana dari $\\frac{2}{\\sqrt{3}}$ adalah...", options: ["$\\frac{1}{3}\\sqrt{3}$", "$2\\sqrt{3}$", "$\\frac{2}{3}\\sqrt{3}$", "$\\frac{3}{2}\\sqrt{3}$", "$\\sqrt{3}$"], correct: 2 },
        { q: "Nilai dari $(2^3)^2 \\cdot 2^{-4}$ adalah...", options: ["2", "4", "8", "16", "1"], correct: 1 },
        { q: "Hasil dari $^{5}\\log 100 - ^{5}\\log 4$ adalah...", options: ["1", "3", "4", "5", "2"], correct: 4 },
        { q: "Jika $2^{x+1} = 16$, nilai $x$ adalah...", options: ["4", "2", "3", "5", "1"], correct: 2 },
        { q: "Bentuk $\\sqrt{75}$ sama dengan...", options: ["$5\\sqrt{3}$", "$3\\sqrt{5}$", "$25\\sqrt{3}$", "$15\\sqrt{5}$", "$5\\sqrt{5}$"], correct: 0 },
        { q: "Nilai dari $(1/2)^{-3}$ adalah...", options: ["-8", "1/8", "6", "8", "-6"], correct: 3 },
        { q: "Bentuk sederhana dari $a^5 \\cdot a^{-2} / a^2$ adalah...", options: ["$a^2$", "$a^3$", "$a^5$", "1", "a"], correct: 4 },
        { q: "Nilai dari $^{2}\\log 1$ adalah...", options: ["0", "1", "2", "tak terhingga", "-1"], correct: 0 },
        { q: "Bentuk rasional $\\frac{4}{2+\\sqrt{2}}$ adalah...", options: ["$4 + 2\\sqrt{2}$", "$2 - \\sqrt{2}$", "$4 - 2\\sqrt{2}$", "$2 + \\sqrt{2}$", "$4\\sqrt{2}$"], correct: 2 },
        { q: "Nilai $x$ dari $^{2}\\log(x-1) = 3$ adalah...", options: ["8", "7", "10", "9", "6"], correct: 3 },
        { q: "Bentuk sederhana dari $\\sqrt{8} + \\sqrt{18}$ adalah...", options: ["$6\\sqrt{2}$", "$5\\sqrt{2}$", "$4\\sqrt{2}$", "$13\\sqrt{2}$", "$2\\sqrt{2}$"], correct: 1 }
    ];

    window.MASTER_QUESTION_BANK.matumu[2] = [
        { q: "Akar-akar persamaan kuadrat $x^2 - 5x + 6 = 0$ adalah...", options: ["2 dan 3", "-2 dan -3", "1 dan 6", "-1 dan -6", "2 dan -3"], correct: 0 },
        { q: "Jumlah akar-akar ($x_1 + x_2$) dari persamaan $2x^2 - 8x + 6 = 0$ adalah...", options: ["-4", "3", "4", "-3", "8"], correct: 2 },
        { q: "Hasil kali akar-akar ($x_1 \\cdot x_2$) dari persamaan $3x^2 + 6x - 9 = 0$ adalah...", options: ["3", "-2", "2", "9", "-3"], correct: 4 },
        { q: "Diskriminan ($D$) dari persamaan kuadrat $x^2 - 4x + 4 = 0$ adalah...", options: ["16", "0", "8", "-16", "4"], correct: 1 },
        { q: "Himpunan penyelesaian dari pertidaksamaan $x^2 - 3x - 10 < 0$ adalah...", options: ["$x < -2$ atau $x > 5$", "$-5 < x < 2$", "$x < -5$ atau $x > 2$", "$-2 < x < 5$", "$2 < x < 5$"], correct: 3 },
        { q: "Persamaan kuadrat yang akar-akarnya 3 dan -5 adalah...", options: ["$x^2 - 2x - 15 = 0$", "$x^2 + 8x - 15 = 0$", "$x^2 + 2x - 15 = 0$", "$x^2 - 8x - 15 = 0$", "$x^2 + 2x + 15 = 0$"], correct: 2 },
        { q: "Jika diskriminan $D > 0$, maka persamaan kuadrat memiliki akar-akar...", options: ["Real dan berbeda", "Real dan kembar", "Imajiner / tidak real", "Sama dengan nol", "Rasional sama"], correct: 0 },
        { q: "Akar-akar dari $2x^2 + 5x - 3 = 0$ adalah...", options: ["-1/2 dan 3", "1/2 dan 3", "-1/2 dan -3", "1/2 dan -3", "2 dan -3"], correct: 3 },
        { q: "Himpunan penyelesaian $x^2 - 9 \\ge 0$ adalah...", options: ["$-3 \\le x \\le 3$", "$x \\le -3$ atau $x \\ge 3$", "$x \\ge 3$", "$x \\le -3$", "$x > 3$"], correct: 1 },
        { q: "Jika $x_1$ dan $x_2$ akar $x^2 - 6x + 8 = 0$, nilai $x_1^2 + x_2^2$ adalah...", options: ["36", "16", "52", "28", "20"], correct: 4 },
        { q: "Persamaan kuadrat $x^2 + px + 9 = 0$ memiliki akar kembar. Nilai $p$ positif adalah...", options: ["3", "9", "12", "6", "18"], correct: 3 },
        { q: "Pertidaksamaan $x^2 - 4x + 3 \\le 0$ dipenuhi oleh...", options: ["$x \\le 1$ atau $x \\ge 3$", "$1 \\le x \\le 3$", "$-3 \\le x \\le -1$", "$x \\le -3$", "$1 < x < 3$"], correct: 1 },
        { q: "Akar dari $x^2 - 16 = 0$ adalah...", options: ["4 dan -4", "4 saja", "16 dan -16", "8 dan -8", "2 dan -2"], correct: 0 },
        { q: "Nilai $k$ agar $x^2 - 6x + k = 0$ tidak memiliki akar real adalah...", options: ["$k < 9$", "$k = 9$", "$k > 6$", "$k < 6$", "$k > 9$"], correct: 4 },
        { q: "Akar-akar $3x^2 - 12x = 0$ adalah...", options: ["0 dan -4", "3 dan 4", "0 dan 4", "0 dan 3", "3 dan -4"], correct: 2 },
        { q: "Jumlah kuadrat akar-akar dari $x^2 - 4x - 5 = 0$ adalah...", options: ["16", "26", "21", "11", "30"], correct: 1 },
        { q: "Pertidaksamaan kuadrat $x^2 + 2x - 8 > 0$ memiliki solusi...", options: ["$-4 < x < 2$", "$x < -2$ atau $x > 4$", "$-2 < x < 4$", "$x > 2$", "$x < -4$ atau $x > 2$"], correct: 4 },
        { q: "Persamaan kuadrat baru yang akar-akarnya dua kali akar $x^2 - 3x + 2 = 0$ adalah...", options: ["$x^2 - 6x + 4 = 0$", "$x^2 - 3x + 8 = 0$", "$x^2 - 6x + 8 = 0$", "$2x^2 - 6x + 4 = 0$", "$x^2 - 12x + 8 = 0$"], correct: 2 },
        { q: "Bentuk kuadrat sempurna dari $x^2 - 6x + 5 = 0$ adalah...", options: ["$(x-3)^2 = 4$", "$(x-3)^2 = 9$", "$(x-6)^2 = 5$", "$(x+3)^2 = 4$", "$(x-3)^2 = 5$"], correct: 0 },
        { q: "Nilai $a$ agar fungsi $f(x) = ax^2 + 4x + 1$ selalu definit positif adalah...", options: ["$a < 4$", "$a > 0$", "$a < 0$", "$a > 4$", "$a > 2$"], correct: 3 },
        { q: "Akar persamaan $(x-2)(x+5) = 0$ adalah...", options: ["-2 dan 5", "2 dan 5", "-2 dan -5", "0 dan 2", "2 dan -5"], correct: 4 },
        { q: "Jika akar $x^2 + bx + 12 = 0$ adalah 3 dan $x_2$, nilai $b$ adalah...", options: ["-7", "7", "-4", "4", "12"], correct: 0 },
        { q: "Grafik $y = x^2 - 4x + 3$ memotong sumbu X di titik...", options: ["(-1,0) dan (-3,0)", "(0,1) dan (0,3)", "(1,0) dan (3,0)", "(2,0) dan (4,0)", "(1,3)"], correct: 2 },
        { q: "Sifat akar persamaan $x^2 + 2x + 5 = 0$ adalah...", options: ["Real dan sama", "Real dan berbeda", "Rasional berlawanan", "Imajiner (tidak real)", "Positif semua"], correct: 3 },
        { q: "Nilai minimum fungsi kuadrat $y = x^2 - 2x - 3$ adalah...", options: ["-3", "-4", "-1", "0", "1"], correct: 1 }
    ];

    // =========================================================================
    // 2. MATEMATIKA LANJUT (MTL)
    // =========================================================================
    window.MASTER_QUESTION_BANK.matlan[1] = [
        { q: "Suku banyak $f(x) = 2x^3 - 5x^2 + 4x - 1$ dibagi oleh $(x - 2)$. Sisa pembagiannya adalah...", options: ["3", "1", "2", "4", "5"], correct: 0 },
        { q: "Jika $f(x) = x^3 - 3x^2 + kx - 4$ habis dibagi $(x - 1)$, maka nilai $k$ adalah...", options: ["4", "5", "6", "2", "1"], correct: 2 },
        { q: "Derajat dari polinomial $(x^2 - 1)^3 (x^3 + 1)$ adalah...", options: ["6", "8", "5", "7", "9"], correct: 4 },
        { q: "Hasil bagi dari $x^3 - 2x^2 + 3x - 5$ oleh $(x - 1)$ adalah...", options: ["$x^2 + x - 2$", "$x^2 - x + 2$", "$x^2 - 2x + 1$", "$x^2 - 3x + 2$", "$x^2 - x - 3$"], correct: 1 },
        { q: "Sisa pembagian polinomial $f(x) = x^4 - 2x^2 + 1$ oleh $(x + 1)$ adalah...", options: ["1", "2", "-1", "0", "4"], correct: 3 },
        { q: "Menurut Teorema Sisa, jika $f(x)$ dibagi oleh $(ax - b)$, maka sisanya $S = $...", options: ["$f(a/b)$", "$f(-b/a)$", "$f(b/a)$", "$f(a)$", "$f(b)$"], correct: 2 },
        { q: "Akar-akar dari persamaan polinomial $x^3 - 6x^2 + 11x - 6 = 0$ adalah...", options: ["1, 2, dan 3", "-1, -2, dan -3", "1, -2, dan 3", "2, 3, dan 4", "-1, 2, dan -3"], correct: 0 },
        { q: "Jika $(x - 2)$ merupakan faktor dari $x^3 - 4x^2 + ax + 6$, maka nilai $a$ adalah...", options: ["-1", "2", "-2", "1", "3"], correct: 3 },
        { q: "Jumlah akar-akar ($x_1 + x_2 + x_3$) dari persamaan $2x^3 - 8x^2 + x + 6 = 0$ adalah...", options: ["-4", "4", "8", "-8", "3"], correct: 1 },
        { q: "Hasil kali akar-akar ($x_1 \\cdot x_2 \\cdot x_3$) dari $2x^3 - 8x^2 + x + 6 = 0$ adalah...", options: ["3", "-6", "6", "-4", "-3"], correct: 4 },
        { q: "Suku banyak $f(x)$ dibagi $(x-1)$ sisa 3, dan dibagi $(x-2)$ sisa 5. Sisa pembagian $f(x)$ oleh $(x^2 - 3x + 2)$ adalah...", options: ["$2x - 1$", "$x + 2$", "$3x - 1$", "$2x + 1$", "$x + 1$"], correct: 3 },
        { q: "Nilai $f(-1)$ jika $f(x) = 3x^4 - 2x^3 + x - 7$ adalah...", options: ["-4", "4", "6", "-6", "2"], correct: 1 },
        { q: "Koefisien suku $x^2$ dari ekspansi $(2x - 1)^3$ adalah...", options: ["-12", "12", "6", "-6", "24"], correct: 0 },
        { q: "Suku tetap (konstanta) dari polinomial $P(x) = (2x - 3)(x^2 + 1)(x - 2)$ adalah...", options: ["-6", "12", "-12", "3", "6"], correct: 4 },
        { q: "Metode Horner digunakan untuk mempermudah perhitungan...", options: ["Matriks", "Vektor", "Pembagian dan nilai suku banyak", "Limit fungsi", "Turunan"], correct: 2 },
        { q: "Sisa pembagian $f(x) = x^3 + kx^2 - 2x + 1$ oleh $(x + 2)$ adalah 5. Nilai $k$ adalah...", options: ["3", "2", "1", "4", "5"], correct: 1 },
        { q: "Banyaknya akar real dari $x^4 - 16 = 0$ adalah...", options: ["4", "1", "0", "3", "2 (yaitu 2 dan -2)"], correct: 4 },
        { q: "Polinomial $x^3 - 1$ dapat difaktorkan menjadi...", options: ["$(x + 1)(x^2 - x + 1)$", "$(x - 1)^3$", "$(x - 1)(x^2 + x + 1)$", "$(x - 1)(x^2 - 1)$", "$(x + 1)(x^2 + 1)$"], correct: 2 },
        { q: "Jika $f(x) = x^3 + ax^2 + bx - 6$ mempunyai faktor $(x-1)$ dan $(x+2)$, nilai $a + b$ adalah...", options: ["-2", "2", "4", "-4", "0"], correct: 0 },
        { q: "Pembagian $x^4 - 1$ oleh $(x - 1)$ menghasilkan suku banyak...", options: ["$x^3 - x^2 + x - 1$", "$x^3 + 1$", "$x^3 - 1$", "$x^3 + x^2 + x + 1$", "$x^2 + 1$"], correct: 3 },
        { q: "Sisa pembagian $f(x)$ oleh $(x^2 - 9)$ jika $f(3) = 7$ dan $f(-3) = 1$ adalah...", options: ["$x - 4$", "$2x + 1$", "$2x - 1$", "$x + 2$", "$x + 4$"], correct: 4 },
        { q: "Banyaknya titik potong grafik $y = x^3 - 3x$ pada sumbu X adalah...", options: ["3", "2", "1", "0", "4"], correct: 0 },
        { q: "Suatu suku banyak berderajat $n$ jika dibagi oleh suku banyak berderajat $m$ ($n > m$) akan menghasilkan sisa berderajat maksimum...", options: ["$n - 1$", "$n - m$", "$m - 1$", "$m$", "$n$"], correct: 2 },
        { q: "Koefisien utama (leading coefficient) dari $P(x) = -3x^5 + 4x^3 - x + 2$ adalah...", options: ["5", "4", "2", "-3", "-1"], correct: 3 },
        { q: "Nilai $a$ agar $(x + 3)$ merupakan faktor dari $x^3 + 3x^2 - ax - 12$ adalah...", options: ["-4", "4", "3", "-3", "12"], correct: 1 }
    ];

    window.MASTER_QUESTION_BANK.matlan[2] = [
        { q: "Determinan dari matriks $A = \\begin{pmatrix} 1 & 2 & 0 \\\\ 0 & 1 & 3 \\\\ 2 & 0 & 1 \\end{pmatrix}$ menggunakan metode Sarrus adalah...", options: ["13", "11", "15", "7", "9"], correct: 0 },
        { q: "Matriks Kofaktor $C_{ij}$ dari elemen $a_{ij}$ dirumuskan...", options: ["$M_{ij}$", "$(-1)^{i-j} M_{ij}$", "$(-1)^{i+j} M_{ij}$", "$\\det(M_{ij})$", "$-M_{ij}$"], correct: 2 },
        { q: "Adjoin dari matriks $A$ ($Adj(A)$) adalah...", options: ["Invers matriks A", "Determinan A", "Matriks Kofaktor C", "Matriks $A^T$", "Transpose dari matriks Kofaktor ($C^T$)"], correct: 4 },
        { q: "Rumus Invers Matriks ordo 3x3 $A^{-1}$ adalah...", options: ["$\\det(A) \\cdot Adj(A)$", "$\\frac{1}{\\det(A)} \\cdot Adj(A)$", "$\\frac{1}{Adj(A)}$", "$\\frac{1}{\\det(A)} \\cdot A^T$", "$Adj(A) \\cdot A$"], correct: 1 },
        { q: "Minor $M_{11}$ dari matriks $\\begin{pmatrix} 2 & 1 & 3 \\\\ 0 & 4 & 5 \\\\ 1 & 0 & 2 \\end{pmatrix}$ diperoleh dengan menghapus baris ke-1 dan kolom ke-1, determinannya adalah...", options: ["6", "10", "4", "8", "2"], correct: 3 },
        { q: "Jika $\\det(A) = 5$, maka nilai $\\det(A^{-1})$ adalah...", options: ["5", "-5", "1/5", "-1/5", "25"], correct: 2 },
        { q: "Jika $A$ matriks ordo $3 \\times 3$ dan $\\det(A) = 2$, maka $\\det(3A) = 3^3 \\cdot \\det(A) = $...", options: ["54", "6", "18", "27", "12"], correct: 0 },
        { q: "Sifat matriks $(A \\cdot B)^{-1}$ sama dengan...", options: ["$A^{-1} \\cdot B^{-1}$", "$A \\cdot B^{-1}$", "$B \\cdot A^{-1}$", "$B^{-1} \\cdot A^{-1}$", "$(A \\cdot B)^T$"], correct: 3 },
        { q: "Sifat matriks $(A^T)^T$ menghasilkan...", options: ["Matriks $A^{-1}$", "Matriks A kembali", "Matriks Identitas", "Determinan A", "Matriks Nol"], correct: 1 },
        { q: "Penyelesaian SPLTV dengan Aturan Cramer untuk mencari nilai $x$ adalah...", options: ["$x = \\det(D) / \\det(D_x)$", "$x = \\det(D_x) \\cdot \\det(D)$", "$x = \\det(D_x) - \\det(D)$", "$x = \\det(D)$", "$x = \\det(D_x) / \\det(D)$"], correct: 4 },
        { q: "Matriks persegi yang memenuhi $A^T = A$ dinamakan matriks...", options: ["Skalar", "Diagonal", "Identitas", "Simetris", "Asimetris"], correct: 3 },
        { q: "Matriks persegi yang memenuhi $A^T = -A$ dinamakan matriks...", options: ["Simetris", "Miring Simetris (Skew-Symmetric)", "Ortogonal", "Singular", "Involutif"], correct: 1 },
        { q: "Matriks $A$ dinamakan Ortogonal apabila memenuhi sifat $A^T = $...", options: ["$A^{-1}$", "A", "-A", "I", "0"], correct: 0 },
        { q: "Determinan matriks diagonal $\\begin{pmatrix} 2 & 0 & 0 \\\\ 0 & 3 & 0 \\\\ 0 & 0 & 4 \\end{pmatrix}$ adalah...", options: ["9", "12", "6", "1", "24"], correct: 4 },
        { q: "Determinan matriks segitiga atas $\\begin{pmatrix} 1 & 4 & 5 \\\\ 0 & 2 & 6 \\\\ 0 & 0 & 3 \\end{pmatrix}$ adalah...", options: ["11", "30", "6", "1", "0"], correct: 2 },
        { q: "Jika $\\det(A) = 0$, maka sistem persamaan linear yang diwakilinya...", options: ["Memiliki 1 solusi unik", "Tidak memiliki solusi unik", "Selalu bernilai nol", "Pasti homogen", "Selalu konsisten"], correct: 1 },
        { q: "Sifat adjoin matriks $A \\cdot Adj(A) = $...", options: ["$I$", "$\\det(A)$", "$A^{-1}$", "$A^2$", "$\\det(A) \\cdot I$"], correct: 4 },
        { q: "Jika $A = \\begin{pmatrix} 1 & 0 & 0 \\\\ 0 & 1 & 0 \\\\ 0 & 0 & 1 \\end{pmatrix}$, maka $A^{100} = $...", options: ["100 I", "0", "$I$", "$A^{10}$", "3 I"], correct: 2 },
        { q: "Jika $A^T$ adalah transpose matriks A, maka $\\det(A^T) = $...", options: ["$\\det(A)$", "$1 / \\det(A)$", "$-\\det(A)$", "$(\\det A)^2$", "0"], correct: 0 },
        { q: "Determinan matriks yang memiliki dua baris identik bernilai...", options: ["1", "Sama dengan barisnya", "Tak terhingga", "0", "-1"], correct: 3 },
        { q: "Vektor baris adalah matriks yang memiliki ordo...", options: ["$n \\times 1$", "$n \\times n$", "$2 \\times 2$", "$1 \\times 1$", "$1 \\times n$"], correct: 4 },
        { q: "Invers matriks diagonal $\\begin{pmatrix} a & 0 \\\\ 0 & b \\end{pmatrix}$ adalah...", options: ["$\\begin{pmatrix} 1/a & 0 \\\\ 0 & 1/b \\end{pmatrix}$", "$\\begin{pmatrix} b & 0 \\\\ 0 & a \\end{pmatrix}$", "$\\begin{pmatrix} -a & 0 \\\\ 0 & -b \\end{pmatrix}$", "$\\begin{pmatrix} 1/b & 0 \\\\ 0 & 1/a \\end{pmatrix}$", "Matriks $I$"], correct: 0 },
        { q: "Jejak (Trace) dari matriks $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\\\ 7 & 8 & 9 \\end{pmatrix}$ adalah...", options: ["45", "0", "15", "18", "9"], correct: 2 },
        { q: "Determinan dari matriks $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\\\ 7 & 8 & 9 \\end{pmatrix}$ bernilai...", options: ["15", "-12", "6", "0", "1"], correct: 3 },
        { q: "Metode eliminasi Gauss-Jordan digunakan untuk mengubah matriks koefisien menjadi...", options: ["Matriks Segitiga Bawah", "Matriks Identitas", "Matriks Nol", "Matriks Kofaktor", "Matriks Transpose"], correct: 1 }
    ];

    // =========================================================================
    // 3. FISIKA KEJURUAN
    // =========================================================================
    window.MASTER_QUESTION_BANK.fisika[1] = [
        { q: "Dimensi dari besaran Gaya (Newton) dalam Sistem Internasional (SI) adalah...", options: ["$[M][L][T]^{-2}$", "$[M][L][T]^{-1}$", "$[M][L]^2[T]^{-2}$", "$[M][L]^{-1}[T]^{-2}$", "$[M][T]^{-2}$"], correct: 0 },
        { q: "Dua buah gaya $F_1 = 6\\text{ N}$ dan $F_2 = 8\\text{ N}$ saling tegak lurus. Resultan kedua gaya tersebut adalah...", options: ["14 N", "2 N", "10 N", "48 N", "100 N"], correct: 2 },
        { q: "Alat ukur yang paling tepat untuk mengukur diameter dalam sebuah silinder blok mesin adalah...", options: ["Mikrometer Sekrup", "Mistar Steel", "Meteran Gulung", "Dial Indicator", "Jangka Sorong"], correct: 4 },
        { q: "Satuan dari Daya dalam Sistem Internasional (SI) adalah...", options: ["Joule", "Watt", "Newton", "Pascal", "Volt"], correct: 1 },
        { q: "Sebuah mobil bergerak dengan kecepatan $72\\text{ km/jam}$. Jika dikonversi ke SI (m/s) nilainya adalah...", options: ["10 m/s", "15 m/s", "25 m/s", "20 m/s", "30 m/s"], correct: 3 },
        { q: "Di antara kelompok besaran berikut, yang semuanya tergolong BESARAN POKOK adalah...", options: ["Kecepatan, Gaya, Massa, Luas", "Massa, Berat, Waktu, Volume", "Massa, Panjang, Waktu, Suhu", "Panjang, Energi, Arus Listrik", "Tekanan, Suhu, Massa"], correct: 2 },
        { q: "Dimensi dari Usaha atau Energi ($W = F \\cdot s$) adalah...", options: ["$[M][L]^2[T]^{-2}$", "$[M][L][T]^{-2}$", "$[M][L][T]^{-1}$", "$[M][L]^{-1}[T]^{-2}$", "$[M]^2[L][T]^{-2}$"], correct: 0 },
        { q: "Alat ukur yang memiliki tingkat ketelitian hingga $0,01\\text{ mm}$ adalah...", options: ["Jangka Sorong", "Mistar", "Meteran", "Mikrometer Sekrup", "Roll Meter"], correct: 3 },
        { q: "Kuantitas fisik yang memiliki nilai dan arah dinamakan besaran...", options: ["Skalar", "Vektor", "Pokok", "Turunan skalar", "Dimensi"], correct: 1 },
        { q: "Di antara besaran berikut yang tergolong BESARAN SKALAR adalah...", options: ["Kecepatan, Gaya, Perpindahan", "Percepatan, Momentum, Torsi", "Gaya, Berat, Kuat Medan", "Impuls, Kecepatan, Massa", "Massa, Kelajuan, Jarak, Energi"], correct: 4 },
        { q: "Resultan dua gaya $F_1 = 10\\text{ N}$ dan $F_2 = 10\\text{ N}$ yang membentuk sudut $60^\\circ$ adalah...", options: ["10 N", "20 N", "$10\\sqrt{2}\\text{ N}$", "$10\\sqrt{3}\\text{ N}$", "0 N"], correct: 3 },
        { q: "Pengukuran diameter kawat diperoleh $2,05\\text{ mm}$. Banyaknya angka penting pada hasil pengukuran tersebut adalah...", options: ["2 angka penting", "3 angka penting", "1 angka penting", "4 angka penting", "5 angka penting"], correct: 1 },
        { q: "Dimensi dari Tekanan ($P = F/A$) adalah...", options: ["$[M][L]^{-1}[T]^{-2}$", "$[M][L][T]^{-2}$", "$[M][L]^2[T]^{-2}$", "$[M][L]^{-2}[T]^{-2}$", "$[M][L][T]^{-1}$"], correct: 0 },
        { q: "Vektor $A = 10\\text{ unit}$ membentuk sudut $30^\\circ$ terhadap sumbu X positif. Komponen $A_y$ searah sumbu Y adalah...", options: ["$5\\sqrt{3}$ unit", "10 unit", "2.5 unit", "0 unit", "5 unit"], correct: 4 },
        { q: "Satuan Hambatan Jenis kawat ($\\rho$) dalam SI adalah...", options: ["$\\Omega/\\text{m}$", "$\\Omega$", "$\\Omega\\text{ m}$", "Volt/m", "Ampere m"], correct: 2 },
        { q: "Pasangan besaran yang memiliki DIMENSI SAMA di bawah ini adalah...", options: ["Gaya dan Daya", "Usaha dan Energi Kinetik", "Kecepatan dan Percepatan", "Massa dan Berat", "Tekanan dan Gaya"], correct: 1 },
        { q: "Nilai perkalian titik dua vektor $\\vec{A} \\cdot \\vec{B}$ jika keduanya saling tegak lurus adalah...", options: ["A x B", "1", "A + B", "-1", "0"], correct: 4 },
        { q: "Nilai perkalian silang dua vektor searah ($0^\\circ$) adalah...", options: ["A x B", "1", "0", "A / B", "A + B"], correct: 2 },
        { q: "Besaran turunan Frekuensi memiliki satuan Hertz (Hz), yang setara dengan...", options: ["$s^{-1}$", "m/s", "kg/s", "N s", "J s"], correct: 0 },
        { q: "Notasi ilmiah dari massa elektron $0,000000000000000000000000000000911\\text{ kg}$ adalah...", options: ["$9,11 \\times 10^{-27}\\text{ kg}$", "$91,1 \\times 10^{-30}\\text{ kg}$", "$9,11 \\times 10^{31}\\text{ kg}$", "$9,11 \\times 10^{-31}\\text{ kg}$", "$0,911 \\times 10^{-30}\\text{ kg}$"], correct: 3 },
        { q: "Suatu persegi panjang berukuran $12,5\\text{ cm}$ dan $2,0\\text{ cm}$. Luas menurut aturan angka penting adalah...", options: ["$25,0\\text{ cm}^2$", "$25,00\\text{ cm}^2$", "$20\\text{ cm}^2$", "$30\\text{ cm}^2$", "$25\\text{ cm}^2$"], correct: 4 },
        { q: "Jika dua vektor sama besar $F$ menghasilkan resultan sebesar $F$, maka sudut antara kedua vektor adalah...", options: ["120°", "60°", "90°", "0°", "180°"], correct: 0 },
        { q: "Satu Tera ($T$) dalam prefix satuan SI setara dengan...", options: ["$10^9$", "$10^6$", "$10^{12}$", "$10^{-12}$", "$10^{15}$"], correct: 2 },
        { q: "Satu Mikron ($\\mu m$) setara dengan...", options: ["$10^{-3}\\text{ m}$", "$10^{-9}\\text{ m}$", "$10^{-12}\\text{ m}$", "$10^{-6}\\text{ m}$", "$10^{-1}\\text{ m}$"], correct: 3 },
        { q: "Penggunaan skala nonius pada jangka sorong berfungsi untuk...", options: ["Menjepit benda", "Meningkatkan ketelitian pengukuran", "Mengunci pengukuran", "Membaca skala utama", "Mengukur sudut"], correct: 1 }
    ];

    window.MASTER_QUESTION_BANK.fisika[2] = [
        { q: "Sepeda motor melaju dengan kecepatan awal 10 m/s dan mengalami percepatan konstan 2 m/s². Kecepatan motor setelah 5 detik adalah...", options: ["20 m/s", "15 m/s", "25 m/s", "30 m/s", "10 m/s"], correct: 0 },
        { q: "Jarak yang ditempuh sepeda motor pada soal di atas selama 5 detik adalah...", options: ["50 meter", "100 meter", "75 meter", "25 meter", "60 meter"], correct: 2 },
        { q: "Ciri utama dari Gerak Lurus Beraturan (GLB) adalah...", options: ["Percepatan konstan", "Kecepatan berubah beraturan", "Lintasan melingkar", "Gaya total tidak nol", "Kecepatan konstan dan percepatan nol"], correct: 4 },
        { q: "Mobil mengerem dari kecepatan $20\\text{ m/s}$ hingga berhenti dalam jarak $40\\text{ meter}$. Perlambatan mobil adalah...", options: ["2 m/s²", "5 m/s²", "4 m/s²", "10 m/s²", "2.5 m/s²"], correct: 1 },
        { q: "Benda jatuh bebas dari ketinggian 20 m di atas tanah ($g = 10\\text{ m/s}^2$). Waktu yang dibutuhkan untuk sampai di tanah adalah...", options: ["4 detik", "1 detik", "2.8 detik", "2 detik", "5 detik"], correct: 3 },
        { q: "Kecepatan benda jatuh bebas saat menyentuh tanah pada soal di atas adalah...", options: ["10 m/s", "40 m/s", "20 m/s", "100 m/s", "14 m/s"], correct: 2 },
        { q: "Pada Gerak Parabola, komponen kecepatan searah sumbu X ($v_x$) bersifat...", options: ["Konstan (GLB)", "GLBB dipercepat", "GLBB diperlambat", "Nol di titik tertinggi", "Selalu berubah"], correct: 0 },
        { q: "Pada Gerak Parabola, komponen kecepatan searah sumbu Y ($v_y$) bersifat...", options: ["Konstan", "Nol sepanjang lintasan", "Sama dengan $v_x$", "GLBB dipengaruhi gravitasi", "Tidak dipengaruhi g"], correct: 3 },
        { q: "Peluru ditembakkan dengan kecepatan awal $v_0$ dan sudut elevasi $\\theta$. Kecepatan di titik tertinggi adalah...", options: ["Nol murni", "$v_0 \\cos\\theta$", "$v_0 \\sin\\theta$", "$v_0$", "$g \\cdot t$"], correct: 1 },
        { q: "Tinggi maksimum ($h_{maks}$) pada gerak parabola dirumuskan...", options: ["$\\frac{v_0^2 \\sin(2\\theta)}{g}$", "$\\frac{v_0 \\sin\\theta}{g}$", "$\\frac{v_0^2 \\cos^2\\theta}{2g}$", "$\\frac{2v_0^2}{g}$", "$\\frac{v_0^2 \\sin^2\\theta}{2g}$"], correct: 4 },
        { q: "Jangkauan mendatar terjauh ($X_{maks}$) pada gerak parabola dirumuskan...", options: ["$\\frac{v_0^2 \\sin^2\\theta}{2g}$", "$\\frac{2v_0 \\sin\\theta}{g}$", "$\\frac{v_0^2 \\cos(2\\theta)}{g}$", "$\\frac{v_0^2 \\sin(2\\theta)}{g}$", "$\\frac{v_0^2}{2g}$"], correct: 3 },
        { q: "Sudut elevasi yang menghasilkan JANGKAUAN TERJAUH pada gerak parabola adalah...", options: ["30°", "45°", "60°", "90°", "15°"], correct: 1 },
        { q: "Peluru ditembakkan $v_0 = 40\\text{ m/s}$ dengan sudut $30^\\circ$ ($g=10$). Waktu untuk mencapai puncak adalah...", options: ["2 detik", "4 detik", "1 detik", "3 detik", "2.5 detik"], correct: 0 },
        { q: "Tinggi maksimum yang dicapai peluru pada soal di atas adalah...", options: ["40 meter", "10 meter", "80 meter", "15 meter", "20 meter"], correct: 4 },
        { q: "Waktu total peluru di udara hingga kembali ke tanah adalah...", options: ["Sama dengan waktu puncak", "Setengahnya", "2 kali waktu mencapai puncak", "Kuadratnya", "3 kali"], correct: 2 },
        { q: "Roda berputar 120 rpm. Frekuensi putarannya dalam Hz adalah...", options: ["120 Hz", "2 Hz", "60 Hz", "4 Hz", "0.5 Hz"], correct: 1 },
        { q: "Kecepatan sudut ($\\omega$) roda di atas adalah...", options: ["$2\\pi\\text{ rad/s}$", "$120\\pi\\text{ rad/s}$", "$240\\pi\\text{ rad/s}$", "$\\pi\\text{ rad/s}$", "$4\\pi\\text{ rad/s}$"], correct: 4 },
        { q: "Percepatan sentripetal ($a_s$) pada gerak melingkar beraturan dirumuskan...", options: ["$a_s = v \\cdot r$", "$a_s = \\omega \\cdot r$", "$a_s = \\frac{v^2}{r} = \\omega^2 r$", "$a_s = \\frac{\\omega}{r}$", "$a_s = v \\cdot \\omega^2$"], correct: 2 },
        { q: "Arah percepatan sentripetal pada gerak melingkar selalu menuju ke...", options: ["Pusat lingkaran", "Tepi luar", "Arah tangensial", "Atas", "Bawah"], correct: 0 },
        { q: "Dua roda A dan B dihubungkan dengan SABUK/RANTAI. Hubungan kecepatannya adalah...", options: ["Kecepatan sudut sama", "$v_A > v_B$", "$\\omega_A > \\omega_B$", "Kecepatan linier sama ($v_A = v_B$)", "Frekuensi sama"], correct: 3 },
        { q: "Dua roda A dan B SESUMBU (sepusat terikat). Hubungan kecepatannya adalah...", options: ["Kecepatan linier sama", "$v_A / r_A = v_B / r_B$", "Jawaban A dan C benar", "Frekuensi berbeda", "Kecepatan sudut sama ($\\omega_A = \\omega_B$)"], correct: 4 },
        { q: "Grafik posisi terhadap waktu ($s - t$) pada GLB berbentuk...", options: ["Garis lurus miring", "Parabola", "Garis mendatar", "Gelombang sinus", "Lingkaran"], correct: 0 },
        { q: "Grafik kecepatan terhadap waktu ($v - t$) pada GLBB dipercepat berbentuk...", options: ["Garis mendatar", "Garis lurus turun", "Garis lurus naik miring", "Parabola", "Lengkung"], correct: 2 },
        { q: "Luas daerah di bawah kurva grafik $v - t$ menyatakan...", options: ["Percepatan", "Kecepatan rata-rata", "Waktu tempuh", "Perpindahan / Jarak tempuh", "Gaya"], correct: 3 },
        { q: "Kemiringan (gradien) garis pada grafik $v - t$ menyatakan...", options: ["Jarak tempuh", "Percepatan", "Posisi awal", "Daya", "Kecepatan"], correct: 1 }
    ];

    // =========================================================================
    // 4. BAHASA INDONESIA
    // =========================================================================
    window.MASTER_QUESTION_BANK.indo[1] = [
        { q: "Penulisan kata serapan yang sesuai dengan PUEBI/KBBI berikut ini adalah...", options: ["Kualitas", "Kwalitas", "Resiko", "Apotik", "Praktek"], correct: 0 },
        { q: "Manakah penulisan gelar akademis yang benar sesuai aturan ejaan?", options: ["Dr Andi M.Pd", "dr. Andi MPd", "Dr. Andi, M.Pd.", "Dr. Andi, M.pd", "Dr. Andi MPd."], correct: 2 },
        { q: "Penulisan tanda baca koma (,) yang tepat terdapat pada kalimat...", options: ["Saya membeli obeng tang dan kunci pas.", "Saya membeli obeng, tang dan kunci pas.", "Saya, membeli obeng, tang, dan kunci pas.", "Saya membeli obeng, tang, dan, kunci pas.", "Saya membeli obeng, tang, dan kunci pas."], correct: 4 },
        { q: "Kata berimbuhan 'meng-...' yang mengalami peluluhan fonem terjadi pada kata...", options: ["Mengkritik", "Mengukus (kuku)", "Mengubah", "Menggambar", "Mengilap"], correct: 1 },
        { q: "Kata yang tidak baku di bawah ini adalah...", options: ["Jadwal", "Objek", "Sistem", "Praktek", "Teknik"], correct: 3 },
        { q: "Penulisan kata depan 'di' yang BENAR sebagai penunjuk tempat adalah...", options: ["Dibengkel", "Di-bengkel", "Di bengkel", "Di Bengkel", "diBengkel"], correct: 2 },
        { q: "Penulisan imbuhan 'di-' yang BENAR untuk kata kerja pasif adalah...", options: ["Dikerjakan", "Di kerjakan", "Di-kerjakan", "DiKerjakan", "Dikerja kan"], correct: 0 },
        { q: "Penggunaan tanda titik dua (:) yang BENAR terdapat pada...", options: ["Kita memerlukan alat seperti: kunci pas, obeng, dan tang.", "Saya membeli: busi dan oli.", "Langkah pertama adalah: membersihkan busi.", "Alat yang dibutuhkan: kunci pas, obeng, dan tang.", "Di antaranya adalah: A, B, dan C."], correct: 3 },
        { q: "Penulisan nama geografi yang BENAR adalah...", options: ["sungai Citarum", "Sungai Citarum", "Sungai citarum", "sungai citarum", "SUNGAI CITARUM"], correct: 1 },
        { q: "Penulisan kata gabungan ber-imbuhan konfiks (awalan & akhiran) yang BENAR adalah...", options: ["Mem pertanggung jawabkan", "Mem-pertanggung-jawabkan", "Mempertanggung jawabkan", "Mem pertanggungjawabkan", "Mempertanggungjawabkan"], correct: 4 },
        { q: "Penggunaan cetak miring (italik) digunakan untuk...", options: ["Nama orang", "Nama lembaga", "Judul bab", "Istilah asing / bahasa daerah", "Kata baku"], correct: 3 },
        { q: "Penulisan angka rupiah yang BENAR adalah...", options: ["Rp. 15.000,-", "Rp15.000,00", "Rp 15.000,-", "RP15000", "Rp: 15.000,00"], correct: 1 },
        { q: "Penulisan kata ulang yang BENAR adalah...", options: ["Anak-anak", "Anak anak", "Anak2", "Anak_anak", "Anak/anak"], correct: 0 },
        { q: "Kalimat efektif harus memenuhi syarat hemat kata. Contoh kalimat hemat adalah...", options: ["Para siswa-siswa SMK menyusun laporan.", "Siswa-siswa sekalian SMK menyusun laporan.", "Banyak siswa-siswa SMK menyusun laporan.", "Para siswa semua menyusun laporan.", "Siswa SMK menyusun laporan."], correct: 4 },
        { q: "Perbaikan kalimat 'Bagi semua siswa SMK wajib mengikuti PKL' yang efektif adalah...", options: ["Bagi siswa SMK wajib PKL.", "Bagi semua siswa wajib PKL.", "Semua siswa SMK wajib mengikuti PKL.", "Siswa SMK bagi wajib PKL.", "Bagi siswa SMK mengikuti PKL."], correct: 2 },
        { q: "Perbaikan kata yang tidak baku 'praktek' dan 'apotik' adalah...", options: ["Praktek dan apotik", "Praktik dan apotek", "Praktikum dan apotek", "Praktikal dan apotik", "Praktek dan apotek"], correct: 1 },
        { q: "Kalimat yang MENGGUNAKAN kata ber-imbuhan peluluhan /k, p, t, s/ yang benar adalah...", options: ["Ibu memfokuskan / mengomunikasikan.", "Ibu mengkomunikasikan.", "Ibu mensucikan.", "Ibu mempraktekkan.", "Ibu memfokuskan kamera."], correct: 4 },
        { q: "Penggunaan tanda hubung (-) yang BENAR untuk merangkaikan se- dengan kata berawalan kapital adalah...", options: ["Se Indonesia", "SeIndonesia", "Se-Indonesia", "se-Indonesia", "SE-INDONESIA"], correct: 2 },
        { q: "Penulisan kata depan 'ke' yang menunjukkan tempat adalah...", options: ["Ke pasar", "Kepasar", "Ke-pasar", "Ke Pasar", "kePasar"], correct: 0 },
        { q: "Penulisan kata gabungan terikat 'pasca' yang BENAR adalah...", options: ["Pasca panen", "Pasca-panen", "Pasca Panen", "Pascapanen", "pasca_panen"], correct: 3 },
        { q: "Penulisan kata gabungan terikat 'antar' yang BENAR adalah...", options: ["Antar kota", "Antar-kota", "Antar Kota", "antar_kota", "Antarkota"], correct: 4 },
        { q: "Perbaikan kata mubazir 'adalah merupakan' dalam kalimat adalah...", options: ["Memilih salah satu: 'adalah' atau 'merupakan'", "Menggunakan keduanya", "Menambahkan kata 'daripada'", "Mengabaikan", "Mengganti dengan kata 'yaitu adalah'"], correct: 0 },
        { q: "Kalimat yang MENGGUNAKAN tanda baca koma secara SALAH adalah...", options: ["Saya membeli busi, oli, dan obeng.", "Karena hujan, pertandingan ditunda.", "Siswa yang tidak membawa kartu, tidak boleh masuk.", "Ahmad pergi ke bengkel, sedangkan Budi ke pasar.", "Pak Budi, teknisi kami, sedang mengajar."], correct: 2 },
        { q: "Penulisan kata 'daripada' yang BENAR adalah...", options: ["Terpisah 'dari pada'", "Menggunakan tanda hubung 'dari-pada'", "Dicetak miring", "Serangkai 'daripada'", "Huruf kapital"], correct: 3 },
        { q: "Kalimat lugas dan denotatif wajib digunakan dalam tulisan...", options: ["Puisi", "Ilmiah / Resmi", "Novel", "Cerpen", "Drama"], correct: 1 }
    ];

    window.MASTER_QUESTION_BANK.indo[2] = [
        { q: "Kalimat Efektif adalah kalimat yang...", options: ["Mampu menyampaikan pesan penulis secara tepat dan mudah dipahami", "Sangat panjang", "Bermakna ganda", "Menggunakan kata-kata sulit", "Berbentuk puisi"], correct: 0 },
        { q: "Kalimat yang Mengandung Ambiguitas (makna ganda) adalah...", options: ["Pegawai gemuk itu datang bersama istrinya.", "Istri dari pegawai gemuk itu datang.", "Istri pegawai yang gemuk itu datang.", "Pegawai itu datang bersama istrinya.", "Wanita itu datang."], correct: 2 },
        { q: "Kalimat yang Mengandung Pleonasme (pemborosan kata) adalah...", options: ["Ia naik ke gedung.", "Ia pergi ke atas gedung.", "Ia memanjat gedung.", "Ia berada di atas gedung.", "Ia naik ke atas gedung."], correct: 4 },
        { q: "Contoh kalimat PARALEL / SEJAJAR yang BENAR di bawah ini adalah...", options: ["Tahapan kerja meliputi membersihkan komponen, pemeriksaan kerusakan, dan mengganti sparepart.", "Tahapan kerja meliputi pembersihan komponen, pemeriksaan kerusakan, dan penggantian sparepart.", "Tahapan kerja meliputi pembersihan komponen, memeriksa kerusakan, dan diganti sparepart.", "Tahapan kerja meliputi dibersihkan komponen, pemeriksaan, dan mengganti.", "Tahapan kerja meliputi pembersihan, diperiksa, dan mengganti."], correct: 1 },
        { q: "Penyebab tidak efektifnya kalimat 'Dalam laporan ini membahas tentang transmisi' adalah...", options: ["Penggunaan kata 'membahas'", "Kurang tanda koma", "Terlalu pendek", "Penggunaan kata depan 'Dalam' di awal yang mengaburkan Subjek", "Penggunaan bahasa baku"], correct: 3 },
        { q: "Kalimat yang TIDAK EFEKTIF karena subjek ganda adalah...", options: ["Dalam menyusun laporan itu, saya dibantu teknisi.", "Saya dibantu teknisi saat menyusun laporan.", "Penyusunan laporan itu saya dibantu oleh teknisi.", "Teknisi membantu saya menyusun laporan.", "Laporan disusun oleh saya dan teknisi."], correct: 2 },
        { q: "Perbaikan kalimat illogis 'Waktu dan tempat kami persilakan' adalah...", options: ["Bapak Kepala Sekolah kami persilakan menyampaikan sambutan.", "Waktu dipersilakan.", "Tempat dipersilakan.", "Waktu dan tempat diberikan.", "Kepada waktu dipersilakan."], correct: 0 },
        { q: "Kalimat yang Mengandung Kontaminasi / Kerancuan bahasa adalah...", options: ["Siswa saling membantu.", "Para siswa membantu.", "Siswa membantu.", "Para siswa-siswa saling bantu-membantu.", "Para siswa saling bantu."], correct: 3 },
        { q: "Perbaikan kalimat 'Sangat mahal sekali' menjadi hemat adalah...", options: ["Sangat mahal sekali banget", "Sangat mahal (atau: Mahal sekali)", "Amat sangat mahal sekali", "Makin mahal sekali", "Sangat amat mahal"], correct: 1 },
        { q: "Kalimat majemuk bertingkat anak kalimat Keterangan Waktu ditandai konjungsi...", options: ["Karena, sebab", "Jika, apabila", "Meskipun, walaupun", "Agar, supaya", "Ketika, setelah, sebelum, sejak"], correct: 4 },
        { q: "Kalimat majemuk bertingkat anak kalimat Keterangan Syarat ditandai konjungsi...", options: ["Sebab, karena", "Sehingga, sampai-sampai", "Meskipun", "Jika, apabila, bilamana", "Agar"], correct: 3 },
        { q: "Kalimat majemuk bertingkat anak kalimat Keterangan Tujuan ditandai konjungsi...", options: ["Karena, sebab", "Agar, supaya, demi", "Jika, apabila", "Seperti", "Bahwa"], correct: 1 },
        { q: "Ciri Kepaduan (Kohesi) pada paragraf ditunjukkan oleh...", options: ["Penggunaan kata transisi / konjungsi yang tepat antar-kalimat", "Penggunaan kata asing", "Jumlah huruf yang genap", "Tanpa kata hubung", "Menggunakan tanda tanya"], correct: 0 },
        { q: "Ciri Keutuhan (Koherensi) pada paragraf ditunjukkan oleh...", options: ["Penggunaan kata baku", "Kalimat yang panjang", "Banyak kata sifat", "Penggunaan angka", "Adanya alur penalaran logis yang mendukung satu ide pokok utama"], correct: 4 },
        { q: "Kalimat yang MENGGUNAKAN konjungsi antarkalimat perlawanan yang benar adalah...", options: ["Tetapi masalah belum selesai.", "Namun masalah belum selesai.", "Akan tetapi, masalah tersebut belum selesai.", "Melainkan masalah belum selesai.", "Sedangkan masalah belum selesai."], correct: 2 },
        { q: "Penulisan konjungsi antarkalimat 'Oleh karena itu' yang BENAR adalah...", options: ["Oleh karena itu kita harus waspada.", "Oleh karena itu, kita harus waspada.", "Oleh karena itu; kita harus waspada.", "Oleh Karena Itu, kita harus waspada.", "Oleh_karena_itu, kita waspada."], correct: 1 },
        { q: "Kalimat efektif 'Buku itu sudah saya baca' merupakan bentuk pasif dari...", options: ["Buku membaca saya.", "Membaca saya buku itu.", "Buku itu dibaca saya.", "Saya dibaca buku itu.", "Saya sudah membaca buku itu."], correct: 4 },
        { q: "Penyuntingan kalimat 'Ia bekerja keras agar supaya lulus' yang benar adalah...", options: ["Ia bekerja keras agar supaya.", "Ia bekerja keras untuk agar lulus.", "Ia bekerja keras agar lulus. (atau: supaya lulus)", "Ia bekerja keras dan supaya lulus.", "Ia bekerja keras supaya agar lulus."], correct: 2 },
        { q: "Kalimat 'Di dalam ruang bengkel terdapat berbagai alat-alat' hematnya menjadi...", options: ["Di dalam ruang bengkel terdapat berbagai alat.", "Di dalam bengkel terdapat banyak alat-alat.", "Di bengkel ada bermacam alat-alat.", "Di ruang bengkel terdapat berbagai macam alat-alat.", "Di bengkel terdapat berbagai alat-alat."], correct: 0 },
        { q: "Penyuntingan kalimat 'Yang membawa HP harap dimatikan' agar logis adalah...", options: ["Orang yang membawa HP harap dimatikan.", "Yang membawa HP harap mati.", "Dimatikan orang yang membawa HP.", "HP yang dibawa harap dimatikan.", "Membawa HP harap dimatikan."], correct: 3 },
        { q: "Penggunaan tanda koma (,) wajib diletakkan jika anak kalimat...", options: ["Berada di belakang induk kalimat", "Berupa kalimat tunggal", "Hanya terdiri dari subjek predikat", "Berada di akhir paragraf", "Mendahului induk kalimat dalam kalimat majemuk bertingkat"], correct: 4 },
        { q: "Kalimat majemuk setara rapatan subjek contohnya adalah...", options: ["Ahmad membuka kap mesin lalu mengukur tegangan baterai.", "Ahmad membuka kap mesin dan Budi mengukur tegangan.", "Jika Ahmad datang, Budi pergi.", "Ahmad tahu bahwa Budi pintar.", "Meskipun hujan, Ahmad berangkat."], correct: 0 },
        { q: "Penyebab ke-tidak-efektifan kalimat 'Berdasarkan pemeriksaan laboratorium menunjukkan bahwa...' adalah...", options: ["Penggunaan kata menunjukkan", "Kata laboratorium tidak baku", "Hilangnya Subjek kalimat akibat frasa Keterangan di awal", "Terlalu pendek", "Penggunaan kata bahwa"], correct: 2 },
        { q: "Perbaikan kalimat 'Pabrik itu memproduksi daripada sparepart' adalah...", options: ["Pabrik itu produksi daripada sparepart.", "Pabrik memproduksi akan sparepart.", "Pabrik diproduksi sparepart.", "Pabrik itu memproduksi sparepart."], correct: 3 },
        { q: "Ciri kalimat baku dalam penulisan laporan resmi adalah...", options: ["Menggunakan bahasa gaul", "Sesuai kaidah PUEBI/EYD, bernalar logis, dan hemat kata", "Menggunakan bahasa daerah", "Penuh bunga bahasa puitis", "Singkat tanpa predikat"], correct: 1 }
    ];

    // =========================================================================
    // 5. BAHASA INGGRIS TEKNIK
    // =========================================================================
    window.MASTER_QUESTION_BANK.inggris[1] = [
        { q: "The mechanic ... the engine oil yesterday afternoon.", options: ["changed", "changes", "has changed", "is changing", "will change"], correct: 0 },
        { q: "We ... in this automotive workshop for two years.", options: ["work", "worked", "have worked", "are working", "will work"], correct: 2 },
        { q: "Look! The chief engineer ... the new prototype right now.", options: ["inspects", "inspected", "has inspected", "was inspecting", "is inspecting"], correct: 4 },
        { q: "If I ... a certified technician, I would fix the hydraulic system.", options: ["am", "were", "was", "be", "been"], correct: 1 },
        { q: "What is the past participle (V3) of the verb 'Drive'?", options: ["Drove", "Driving", "Drives", "Driven", "Drived"], correct: 3 },
        { q: "He ... to the workshop yesterday.", options: ["go", "goes", "went", "gone", "going"], correct: 2 },
        { q: "The pistons ... up and down inside the cylinder block.", options: ["move", "moves", "moving", "moved", "has moved"], correct: 0 },
        { q: "You ... wear safety goggles while operating the grinding machine.", options: ["might", "can", "could", "must", "would"], correct: 3 },
        { q: "What is the synonym of 'Maintain' in workshop operations?", options: ["Destroy", "Keep / Servicing", "Purchase", "Damage", "Assembly"], correct: 1 },
        { q: "The multimeter is an instrument used ... electrical voltage.", options: ["measure", "measured", "measuring", "measures", "to measure"], correct: 4 },
        { q: "Automotive technology is becoming ... advanced than ten years ago.", options: ["most", "as", "much", "more", "little"], correct: 3 },
        { q: "We have ... this workshop equipment since 2022.", options: ["use", "used", "using", "uses", "to use"], correct: 1 },
        { q: "What is the past tense (V2) of 'Break'?", options: ["Broke", "Broken", "Breaking", "Breaks", "Breaked"], correct: 0 },
        { q: "The technician ... the battery voltage right now.", options: ["tests", "tested", "has tested", "was testing", "is testing"], correct: 4 },
        { q: "If you press the emergency button, the machine ... immediately.", options: ["stopped", "would stop", "will stop", "had stopped", "stopping"], correct: 2 },
        { q: "An ammeter is used to measure electric ...", options: ["Voltage", "Current", "Resistance", "Power", "Temperature"], correct: 1 },
        { q: "A voltmeter is used to measure electric ...", options: ["Current", "Resistance", "Power", "Heat", "Voltage"], correct: 4 },
        { q: "An ohmmeter is used to measure electrical ...", options: ["Current", "Voltage", "Resistance", "Power", "Capacitance"], correct: 2 },
        { q: "Which word is an ADJECTIVE?", options: ["Fast", "Run", "Quickly", "Runner", "Running"], correct: 0 },
        { q: "Which word is an ADVERB?", options: ["Careful", "Care", "Caring", "Carefully", "Careless"], correct: 3 },
        { q: "What is the primary function of engine coolant?", options: ["To lubricate gears", "To ignite fuel", "To clean exhaust", "To charge battery", "To prevent overheating"], correct: 4 },
        { q: "What is the primary function of engine oil?", options: ["To lubricate moving parts", "To cool the radiator", "To mix with gasoline", "To clean tires", "To ignite spark"], correct: 0 },
        { q: "Choose the correct spelling:", options: ["Maintenence", "Mantenance", "Maintenance", "Maintenanse", "Maintainance"], correct: 2 },
        { q: "Choose the correct spelling:", options: ["Equipement", "Equipmint", "Eqipment", "Equipment", "Equipmet"], correct: 3 },
        { q: "The spark plug is used to ... the fuel mixture.", options: ["cool", "ignite", "clean", "filter", "compress"], correct: 1 }
    ];

    window.MASTER_QUESTION_BANK.inggris[2] = [
        { q: "You ... wear a helmet while riding a motorcycle.", options: ["must", "can", "may", "might", "shall"], correct: 0 },
        { q: "Technicians ... follow safety procedures at all times.", options: ["could", "might", "should", "would", "may"], correct: 2 },
        { q: "You ... not touch live wires with bare hands.", options: ["can", "may", "might", "would", "must"], correct: 4 },
        { q: "We ... leave the workshop before cleaning our tools.", options: ["can", "should not", "may", "must", "might"], correct: 1 },
        { q: "... I borrow your 12mm socket wrench, please?", options: ["Must", "Should", "Would", "May / Can", "Will"], correct: 3 },
        { q: "The mechanic ... fix the transmission in two hours.", options: ["must", "may", "can", "should", "might"], correct: 2 },
        { q: "Modal auxiliary expressing OBLIGATION is...", options: ["Must / Have to", "Can", "May", "Might", "Could"], correct: 0 },
        { q: "Modal auxiliary expressing ABILITY is...", options: ["Must", "May", "Should", "Can / Be able to", "Will"], correct: 3 },
        { q: "Modal auxiliary expressing PERMISSION is...", options: ["Must", "May / Can", "Should", "Would", "Had to"], correct: 1 },
        { q: "Modal auxiliary expressing ADVICE is...", options: ["Must", "Can", "May", "Will", "Should / Ought to"], correct: 4 },
        { q: "If the engine is overheating, you ... stop the car.", options: ["can", "may", "might", "must / should", "could"], correct: 3 },
        { q: "You ... wear safety goggles when grinding metal.", options: ["may", "have to", "might", "can", "could"], correct: 1 },
        { q: "He ... speak three languages fluently.", options: ["can", "must", "should", "may", "might"], correct: 0 },
        { q: "The workshop ... open at 8:00 AM tomorrow.", options: ["can", "must", "may", "should", "will"], correct: 4 },
        { q: "It ... rain this afternoon, so close the workshop windows.", options: ["must", "can", "might / may", "should", "will"], correct: 2 },
        { q: "You ... not smoke near the fuel storage area.", options: ["can", "must", "may", "should", "would"], correct: 1 },
        { q: "All workers ... wear steel-toed boots in the factory.", options: ["may", "can", "might", "could", "are required to / must"], correct: 4 },
        { q: "I ... finish this diagnostic report by 5 PM.", options: ["may", "might", "have to", "could", "can"], correct: 2 },
        { q: "She ... operate the CNC machine very well.", options: ["can", "must", "may", "should", "might"], correct: 0 },
        { q: "... you please hand me the pliers?", options: ["Must", "May", "Should", "Could / Would", "Might"], correct: 3 },
        { q: "Passengers ... fasten their seatbelts during the ride.", options: ["can", "may", "might", "could", "must"], correct: 4 },
        { q: "You ... check the oil level before a long trip.", options: ["should", "can", "may", "might", "could"], correct: 0 },
        { q: "The battery ... be dead because the lights won't turn on.", options: ["can", "may", "must", "should", "would"], correct: 2 },
        { q: "We ... not enter the restricted area without a permit.", options: ["can", "may", "should", "must", "might"], correct: 3 },
        { q: "You ... always double-check the torque settings.", options: ["can", "should", "may", "might", "could"], correct: 1 }
    ];

}
