// Data Soal Nyata Level 16 & 17 untuk Seluruh Mata Pelajaran

if (window.MASTER_QUESTION_BANK) {

    // ==========================================
    // 1. MATEMATIKA UMUM (MATUMU)
    // ==========================================

    // --- MATUMU LEVEL 16: Turunan Fungsi Aljabar Dasar ---
    window.MASTER_QUESTION_BANK.matumu[16] = [
        { q: "Turunan pertama dari fungsi konstanta $f(x) = 7$ adalah $f'(x) = $...", options: ["0", "7", "1", "x", "-7"], correct: 0 },
        { q: "Turunan pertama dari $f(x) = x^n$ dirumuskan sebagai...", options: ["$f'(x) = n x^{n-1}$", "$f'(x) = n x^{n+1}$", "$f'(x) = x^{n-1}$", "$f'(x) = \\frac{1}{n}x^n$", "$f'(x) = n! x^n$"], correct: 0 },
        { q: "Turunan pertama dari $f(x) = 5x^4$ adalah...", options: ["$20x^3$", "$5x^3$", "$20x^4$", "$4x^3$", "$9x^3$"], correct: 0 },
        { q: "Turunan pertama dari $f(x) = 3x^2 - 4x + 6$ adalah...", options: ["$6x - 4$", "$6x^2 - 4$", "$3x - 4$", "$6x + 4$", "$x^2 - 4$"], correct: 0 },
        { q: "Jika $f(x) = (2x - 1)^3$, dengan aturan rantai turunan pertamanya adalah...", options: ["$6(2x - 1)^2$", "$3(2x - 1)^2$", "$2(2x - 1)^2$", "$6(2x - 1)$", "$12(2x - 1)^2$"], correct: 0 },
        { q: "Turunan pertama dari $f(x) = \\frac{1}{x} = x^{-1}$ adalah...", options: ["$-\\frac{1}{x^2}$", "$\\frac{1}{x^2}$", "$-\\frac{1}{x}$", "$x^{-2}$", "$-\\frac{2}{x^2}$"], correct: 0 },
        { q: "Turunan pertama dari $f(x) = \\sqrt{x} = x^{1/2}$ adalah...", options: ["$\\frac{1}{2\\sqrt{x}}$", "$2\\sqrt{x}$", "$\\frac{1}{\\sqrt{x}}$", "$-\\frac{1}{2\\sqrt{x}}$", "$\\frac{1}{2}x$"], correct: 0 },
        { q: "Jika $f(x) = u(x) \\cdot v(x)$, maka rumus turunan pertamanya adalah...", options: ["$u'v + uv'$", "$u'v - uv'$", "$u'v'$", "$uv + u'v'$", "$u/v$"], correct: 0 },
        { q: "Jika $f(x) = \\frac{u(x)}{v(x)}$, maka rumus turunan pertamanya adalah...", options: ["$\\frac{u'v - uv'}{v^2}$", "$\\frac{u'v + uv'}{v^2}$", "$\\frac{uv' - u'v}{v^2}$", "$\\frac{u'}{v'}$", "$\\frac{u'v - uv'}{v}$"], correct: 0 },
        { q: "Turunan pertama dari $f(x) = (x^2 + 3)(2x - 1)$ adalah...", options: ["$6x^2 - 2x + 6$", "$2x^2 + 6x - 1$", "$6x^2 + 2x - 6$", "$3x^2 - x + 3$", "$x^2 + x + 1$"], correct: 0 },
        { q: "Nilai dari $f'(2)$ jika $f(x) = 3x^2 - 5x + 2$ adalah...", options: ["7", "4", "5", "10", "2"], correct: 0 },
        { q: "Gradien garis singgung kurva $y = x^2 - 4x$ di titik dengan absis $x = 3$ adalah...", options: ["2", "-2", "4", "6", "0"], correct: 0 },
        { q: "Jika $f(x) = (3x - 2)^4$, maka $f'(x) = $...", options: ["$12(3x - 2)^3$", "$4(3x - 2)^3$", "$3(3x - 2)^3$", "$12(3x - 2)^4$", "$36(3x - 2)^3$"], correct: 0 },
        { q: "Turunan pertama dari $y = 4x^3 - 3x^2 + 2x - 5$ adalah...", options: ["$12x^2 - 6x + 2$", "$12x^2 - 6x - 5$", "$4x^2 - 3x + 2$", "$12x - 6$", "$12x^3 - 6x^2 + 2$"], correct: 0 },
        { q: "Jika $f(x) = \\frac{2x}{x + 1}$, maka turunan $f'(1)$ adalah...", options: ["1/2", "1", "2", "1/4", "0"], correct: 0 },
        { q: "Turunan dari $f(x) = 8\\sqrt[4]{x^3}$ adalah...", options: ["$6x^{-1/4}$", "$8x^{1/4}$", "$2x^{3/4}$", "$6x^{3/4}$", "$4x^{-1/2}$"], correct: 0 },
        { q: "Jika $y = (x^2 - 5)^5$, maka $\\frac{dy}{dx} = $...", options: ["$10x(x^2 - 5)^4$", "$5(x^2 - 5)^4$", "$2x(x^2 - 5)^4$", "$5x^2(x^2 - 5)^4$", "$10(x^2 - 5)^4$"], correct: 0 },
        { q: "Laju perubahan nilai fungsi $f(x)$ terhadap $x$ secara analitis dinamakan...", options: ["Turunan (Derivatif)", "Integral", "Limit", "Matriks", "Vektor"], correct: 0 },
        { q: "Notasi lain untuk menyatakan turunan pertama selain $f'(x)$ adalah...", options: ["$\\frac{df}{dx}$ atau $y'$", "$\\int f(x) dx$", "$\\lim_{x \\to 0}$", "$\\sum f(x)$", "$f^{-1}(x)$"], correct: 0 },
        { q: "Jika $f(x) = x^5 - 3x^3 + 2$, maka $f''(x)$ (turunan kedua) adalah...", options: ["$20x^3 - 18x$", "$5x^4 - 9x^2$", "$20x^3 - 9x^2$", "$60x^2 - 18$", "$20x^4 - 18x$"], correct: 0 },
        { q: "Turunan dari $f(x) = (x + 2)^2$ adalah...", options: ["$2x + 4$", "$2x + 2$", "$x + 2$", "$4x + 8$", "$2$"], correct: 0 },
        { q: "Jika $f(x) = \\frac{3}{x^2} = 3x^{-2}$, maka $f'(x) = $...", options: ["$-\\frac{6}{x^3}$", "$\\frac{6}{x^3}$", "$-\\frac{3}{x^3}$", "$-\\frac{6}{x^2}$", "$\\frac{3}{x^3}$"], correct: 0 },
        { q: "Nilai $x$ yang menyebabkan turunan dari $f(x) = x^2 - 6x + 9$ bernilai nol adalah...", options: ["3", "0", "-3", "6", "9"], correct: 0 },
        { q: "Turunan pertama dari $y = (2x^2 - 3)(x + 1)$ adalah...", options: ["$6x^2 + 4x - 3$", "$4x^2 - 3x + 1$", "$2x^2 + 4x - 3$", "$6x^2 - 3$", "$4x^2 + 2x$"], correct: 0 },
        { q: "Jika $f(x) = k \\cdot u(x)$ dengan $k$ adalah konstanta, maka $f'(x) = $...", options: ["$k \\cdot u'(x)$", "$k$", "$u'(x)$", "$k + u'(x)$", "0"], correct: 0 }
    ];

    // --- MATUMU LEVEL 17: Aplikasi Turunan: Maksimum, Minimum & Garis Singgung ---
    window.MASTER_QUESTION_BANK.matumu[17] = [
        { q: "Syarat suatu fungsi $f(x)$ mencapai nilai stasioner adalah turunan pertamanya...", options: ["$f'(x) = 0$", "$f'(x) > 0$", "$f'(x) < 0$", "$f''(x) = 0$", "$f(x) = 0$"], correct: 0 },
        { q: "Persamaan garis singgung kurva $y = f(x)$ di titik $(x_1, y_1)$ dengan gradien $m = f'(x_1)$ adalah...", options: ["$y - y_1 = m(x - x_1)$", "$y + y_1 = m(x + x_1)$", "$y = mx + c$", "$y_1 - y = m(x_1 - x)$", "$ax + by = c$"], correct: 0 },
        { q: "Kurva $y = f(x)$ naik pada suatu interval jika memenuhi syarat...", options: ["$f'(x) > 0$", "$f'(x) < 0$", "$f'(x) = 0$", "$f''(x) > 0$", "$f''(x) < 0$"], correct: 0 },
        { q: "Kurva $y = f(x)$ turun pada suatu interval jika memenuhi syarat...", options: ["$f'(x) < 0$", "$f'(x) > 0$", "$f'(x) = 0$", "$f''(x) < 0$", "$f(x) < 0$"], correct: 0 },
        { q: "Nilai stasioner dari fungsi $f(x) = x^2 - 4x + 3$ dicapai pada $x = $...", options: ["2", "1", "3", "-2", "0"], correct: 0 },
        { q: "Nilai minimum dari fungsi $f(x) = x^2 - 4x + 3$ adalah...", options: ["-1", "3", "0", "1", "-3"], correct: 0 },
        { q: "Gradien garis singgung kurva $y = x^2 - 5x + 6$ di titik $(1, 2)$ adalah ($y' = 2x - 5$)...", options: ["-3", "2", "-5", "3", "1"], correct: 0 },
        { q: "Suatu sebidang tanah dipagari dengan keliling 100 meter. Luas maksimum tanah tersebut adalah...", options: ["625 m²", "500 m²", "1000 m²", "250 m²", "100 m²"], correct: 0 },
        { q: "Titik balik maksimum dari fungsi $f(x) = -x^2 + 4x$ terletak pada koordinat...", options: ["(2, 4)", "(4, 2)", "(0, 0)", "(2, 0)", "(1, 3)$"], correct: 0 },
        { q: "Dua buah bilangan berjumlah 20. Hasil kali maksimum kedua bilangan tersebut adalah...", options: ["100", "96", "84", "105", "80"], correct: 0 },
        { q: "Persamaan garis singgung kurva $y = x^2$ di titik $(2, 4)$ adalah...", options: ["$y = 4x - 4$", "$y = 2x$", "$y = 4x + 4$", "$y = 2x - 4$", "$y = x + 2$"], correct: 0 },
        { q: "Jika $f''(x) < 0$ pada suatu interval, maka kurva bersifat...", options: ["Cekung ke bawah", "Cekung ke atas", "Garis lurus", "Stasioner", "Naik terus"], correct: 0 },
        { q: "Jika $f''(x) > 0$ pada suatu interval, maka kurva bersifat...", options: ["Cekung ke atas", "Cekung ke bawah", "Turun", "Stasioner", "Membentuk lingkaran"], correct: 0 },
        { q: "Kotak tanpa tutup dibuat dari selembar karton $12 \\times 12\\text{ cm}$ dengan memotong persegi seluas $x$ di setiap pojoknya. Volume maksimum dicapai saat $x = $...", options: ["2 cm", "3 cm", "4 cm", "1 cm", "5 cm"], correct: 0 },
        { q: "Syarat dua buah garis saling TEGAK LURUS adalah hubungan gradiennya...", options: ["$m_1 \\cdot m_2 = -1$", "$m_1 = m_2$", "$m_1 + m_2 = 0$", "$m_1 - m_2 = 1$", "$m_1 \\cdot m_2 = 1$"], correct: 0 },
        { q: "Syarat dua buah garis saling SEJAJAR adalah hubungan gradiennya...", options: ["$m_1 = m_2$", "$m_1 \\cdot m_2 = -1$", "$m_1 + m_2 = 1$", "$m_1 = -m_2$", "$m_1 \\cdot m_2 = 0$"], correct: 0 },
        { q: "Persamaan garis yang melalui titik $(2, 3)$ dengan gradien $m = 4$ adalah...", options: ["$y - 3 = 4(x - 2)$ (atau $y = 4x - 5$)", "$y + 3 = 4(x + 2)$", "$y = 4x + 3$", "$y - 2 = 4(x - 3)$", "$y = 2x + 4$"], correct: 0 },
        { q: "Sebuah peluru ditembakkan ke atas dengan fungsi ketinggian $h(t) = 40t - 5t^2$ (dalam meter). Ketinggian maksimum peluru dicapai saat $t = $...", options: ["4 detik", "8 detik", "2 detik", "5 detik", "10 detik"], correct: 0 },
        { q: "Ketinggian maksimum peluru pada soal di atas adalah...", options: ["80 meter", "40 meter", "160 meter", "20 meter", "100 meter"], correct: 0 },
        { q: "Titik belok suatu kurva terjadi saat turunan kedua bernilai...", options: ["$f''(x) = 0$", "$f'(x) = 0$", "$f''(x) > 0$", "$f''(x) < 0$", "$f(x) = 0$"], correct: 0 },
        { q: "Kecepatan suatu partikel adalah turunan pertama dari fungsi...", options: ["Posisi / Jarak ($s(t)$)", "Percepatan ($a(t)$)", "Waktu ($t$)", "Usaha", "Gaya"], correct: 0 },
        { q: "Percepatan suatu partikel adalah turunan pertama dari fungsi...", options: ["Kecepatan ($v(t)$)", "Posisi ($s(t)$)", "Gaya", "Massa", "Energi"], correct: 0 },
        { q: "Garis normal adalah garis yang tegak lurus dengan...", options: ["Garis singgung kurva di titik singgung", "Sumbu X", "Sumbu Y", "Asimtot kurva", "Jari-jari lingkaran"], correct: 0 },
        { q: "Jika gradien garis singgung kurva adalah $m = -3$, maka gradien garis normalnya adalah...", options: ["1/3", "-3", "-1/3", "3", "0"], correct: 0 },
        { q: "Nilai minimum dari fungsi $f(x) = x^3 - 3x$ dalam interval $-2 \\le x \\le 2$ adalah...", options: ["-2", "-1", "2", "0", "-4"], correct: 0 }
    ];

    // ==========================================
    // 2. MATEMATIKA LANJUT (MTL)
    // ==========================================

    // --- MTL LEVEL 16: Matriks Transformasi Geometri ---
    window.MASTER_QUESTION_BANK.matlan[16] = [
        { q: "Matriks transformasi untuk Pencerminan terhadap sumbu X adalah...", options: ["$\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & -1 \\\\ -1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & -1 \\end{pmatrix}$"], correct: 0 },
        { q: "Matriks transformasi untuk Pencerminan terhadap sumbu Y adalah...", options: ["$\\begin{pmatrix} -1 & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & -1 \\\\ -1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}$"], correct: 0 },
        { q: "Matriks transformasi untuk Pencerminan terhadap garis $y = x$ adalah...", options: ["$\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & -1 \\\\ -1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & 1 \\end{pmatrix}$"], correct: 0 },
        { q: "Matriks transformasi untuk Pencerminan terhadap titik asal $O(0,0)$ adalah...", options: ["$\\begin{pmatrix} -1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & -1 \\\\ -1 & 0 \\end{pmatrix}$"], correct: 0 },
        { q: "Matriks rotasi sebesar $\\theta$ dengan pusat $(0,0)$ berlawanan arah jarum jam adalah...", options: ["$\\begin{pmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{pmatrix}$", "$\\begin{pmatrix} \\cos\\theta & \\sin\\theta \\\\ -\\sin\\theta & \\cos\\theta \\end{pmatrix}$", "$\\begin{pmatrix} \\sin\\theta & \\cos\\theta \\\\ -\\cos\\theta & \\sin\\theta \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & 1 \\\\ -1 & 0 \\end{pmatrix}$"], correct: 0 },
        { q: "Matriks transformasi untuk Rotasi sebesar $90^\\circ$ berlawanan arah jarum jam dengan pusat $(0,0)$ adalah...", options: ["$\\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & 1 \\\\ -1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & 1 \\end{pmatrix}$"], correct: 0 },
        { q: "Matriks transformasi untuk Dilatasi (skala) dengan faktor pengali $k$ dan pusat $(0,0)$ adalah...", options: ["$\\begin{pmatrix} k & 0 \\\\ 0 & k \\end{pmatrix}$", "$\\begin{pmatrix} 0 & k \\\\ k & 0 \\end{pmatrix}$", "$\\begin{pmatrix} k & k \\\\ k & k \\end{pmatrix}$", "$\\begin{pmatrix} 1 & k \\\\ k & 1 \\end{pmatrix}$", "$\\begin{pmatrix} k^2 & 0 \\\\ 0 & k^2 \\end{pmatrix}$"], correct: 0 },
        { q: "Jika titik $A(3, 2)$ ditranslasikan oleh $T = (4, 5)$, koordinat bayangannya adalah...", options: ["(7, 7)", "(1, -3)", "(12, 10)", "(7, 2)", "(3, 7)"], correct: 0 },
        { q: "Bayangan titik $P(2, 5)$ dicerminkan terhadap sumbu X adalah...", options: ["(2, -5)", "(-2, 5)", "(-2, -5)", "(5, 2)", "(2, 5)"], correct: 0 },
        { q: "Bayangan titik $P(2, 5)$ dicerminkan terhadap sumbu Y adalah...", options: ["(-2, 5)", "(2, -5)", "(-2, -5)", "(5, 2)", "(-5, -2)"], correct: 0 },
        { q: "Komposisi transformasi matriks $T_2 \\circ T_1$ terhadap titik $X$ dirumuskan sebagai...", options: ["$T_2 \\cdot (T_1 \\cdot X)$", "$T_1 \\cdot T_2 \\cdot X$", "$T_1 + T_2 + X$", "$(T_1 \\cdot T_2)^{-1} X$", "$T_2 + T_1$"], correct: 0 },
        { q: "Luas bayangan suatu bangun datar yang ditransformasikan oleh matriks $T$ dengan determinan $|det(T)|$ adalah...", options: ["$Luas_{asal} \\cdot |det(T)|$", "$Luas_{asal} + det(T)$", "$Luas_{asal} / det(T)$", "$det(T) / Luas_{asal}$", "$Luas_{asal}$"], correct: 0 },
        { q: "Jika matriks transformasi $T = \\begin{pmatrix} 2 & 1 \\\\ 1 & 1 \\end{pmatrix}$, determinan matriks tersebut adalah...", options: ["1", "3", "2", "-1", "0"], correct: 0 },
        { q: "Bayangan titik $A(1, 3)$ dirotasi $180^\\circ$ dengan pusat $(0,0)$ adalah...", options: ["(-1, -3)", "(1, -3)", "(-1, 3)", "(3, 1)", "(-3, -1)"], correct: 0 },
        { q: "Transformasi yang TIDAK mengubah ukuran maupun bentuk bangun dinamakan...", options: ["Isometri (Translasi, Refleksi, Rotasi)", "Dilatasi", "Transformasi matriks non-bujur sangkar", "Perbesaran", "Peregangan"], correct: 0 },
        { q: "Transformasi yang mengubah ukuran bangun (memperbesar/memperkecil) namun bentuk tetap adalah...", options: ["Dilatasi", "Translasi", "Refleksi", "Rotasi", "Identitas"], correct: 0 },
        { q: "Titik $B(-4, 3)$ didilatasi dengan faktor skala $k = -2$ dan pusat $(0,0)$, bayangannya adalah...", options: ["(8, -6)", "(-8, 6)", "(6, -8)", "(-6, 8)", "(8, 6)"], correct: 0 },
        { q: "Matriks transformasi untuk Pencerminan terhadap garis $y = -x$ adalah...", options: ["$\\begin{pmatrix} 0 & -1 \\\\ -1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}$", "$\\begin{pmatrix} -1 & 0 \\\\ 0 & 1 \\end{pmatrix}$"], correct: 0 },
        { q: "Jika titik $(x, y)$ dicerminkan terhadap garis $y = x$, koordinat bayangannya adalah...", options: ["$(y, x)$", "$(-y, -x)$", "$(-x, y)$", "$(x, -y)$", "$(-x, -y)$"], correct: 0 },
        { q: "Jika titik $(x, y)$ dicerminkan terhadap garis $y = -x$, koordinat bayangannya adalah...", options: ["$(-y, -x)$", "$(y, x)$", "$(-x, y)$", "$(x, -y)$", "$(-x, -y)$"], correct: 0 },
        { q: "Transformasi Geseran (Shearing) sejajar sumbu X dengan faktor $k$ memiliki matriks...", options: ["$\\begin{pmatrix} 1 & k \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ k & 1 \\end{pmatrix}$", "$\\begin{pmatrix} k & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & k \\end{pmatrix}$", "$\\begin{pmatrix} k & k \\\\ 1 & 1 \\end{pmatrix}$"], correct: 0 },
        { q: "Transformasi Regangan (Stretching) dengan faktor $k$ searah sumbu X memiliki matriks...", options: ["$\\begin{pmatrix} k & 0 \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} 1 & 0 \\\\ 0 & k \\end{pmatrix}$", "$\\begin{pmatrix} 1 & k \\\\ 0 & 1 \\end{pmatrix}$", "$\\begin{pmatrix} k & k \\\\ k & k \\end{pmatrix}$", "$\\begin{pmatrix} 0 & k \\\\ k & 0 \\end{pmatrix}$"], correct: 0 },
        { q: "Bayangan garis $y = 2x + 1$ oleh translasi $T = (1, 2)$ adalah...", options: ["$y = 2x - 1$", "$y = 2x + 1$", "$y = 2x + 3$", "$y = x + 2$", "$y = 2x$"], correct: 0 },
        { q: "Invers dari matriks translasi $T = \\begin{pmatrix} a \\\\ b \\end{pmatrix}$ adalah translasi...", options: ["$-T = \\begin{pmatrix} -a \\\\ -b \\end{pmatrix}$", "$T = \\begin{pmatrix} a \\\\ b \\end{pmatrix}$", "$T^{-1} = \\begin{pmatrix} 1/a \\\\ 1/b \\end{pmatrix}$", "$\\begin{pmatrix} b \\\\ a \\end{pmatrix}$", "Matriks Nol"], correct: 0 },
        { q: "Rotasi sebesar $360^\\circ$ atau $0^\\circ$ terhadap pusat $(0,0)$ ekuivalen dengan matriks...", options: ["Matriks Identitas ($I$)", "Matriks Nol ($O$)", "Matriks Refleksi", "Matriks Singular", "Matriks Diagonal negatif"], correct: 0 }
    ];

    // --- MTL LEVEL 17: Barisan & Deret Tak Hingga Lanjut ---
    window.MASTER_QUESTION_BANK.matlan[17] = [
        { q: "Jumlah tak hingga dari deret geometri $12 + 6 + 3 + 1.5 + ...$ adalah...", options: ["24", "18", "36", "16", "20"], correct: 0 },
        { q: "Suku pertama deret geometri tak hingga adalah 10 dan jumlahnya 15. Rasio $r$ deret tersebut adalah...", options: ["1/3", "2/3", "1/2", "3/4", "1/4"], correct: 0 },
        { q: "Deret geometri tak hingga $2 + 4 + 8 + 16 + ...$ bernilai...", options: ["Tak terhingga $(\\infty)$ karena $r = 2 > 1$ konvergen salah", "10", "4", "8", "Konvergen ke 0"], correct: 0 },
        { q: "Notasi sigma (sumasi) $\\sum_{k=1}^{4} k^2$ menghasilkan nilai...", options: ["30 ($1+4+9+16$)", "16", "20", "25", "10"], correct: 0 },
        { q: "Nilai dari $\\sum_{k=1}^{3} (3k - 1)$ adalah...", options: ["12 ($2+5+8$)", "10", "15", "9", "14"], correct: 0 },
        { q: "Deret geometri tak hingga konvergen jika rasionnya memenuhi syarat...", options: ["$-1 < r < 1$ (atau $|r| < 1$)", "$r > 1$", "$r < -1$", "$r = 1$", "$r \\ge 1$"], correct: 0 },
        { q: "Deret geometri tak hingga divergen jika rasionnya memenuhi syarat...", options: ["$r > 1$ atau $r < -1$", "$-1 < r < 1$", "$r = 0$", "$r = 1$", "$r = -1$"], correct: 0 },
        { q: "Jumlah deret geometri tak hingga dirumuskan sebagai $S_\\infty = $...", options: ["$\\frac{a}{1 - r}$", "$\\frac{a}{r - 1}$", "$\\frac{a(1 - r^n)}{1 - r}$", "$\\frac{a}{1 + r}$", "$a \\cdot r$"], correct: 0 },
        { q: "Jika jumlah tak hingga deret geometri adalah 20 dan suku pertamanya 5, maka rasionya adalah...", options: ["3/4", "1/4", "1/2", "2/3", "4/5"], correct: 0 },
        { q: "Bentuk desimal berulang $0.6666... = 0.\\bar{6}$ jika diubah ke pecahan biasa adalah...", options: ["2/3", "3/5", "6/10", "1/3", "4/5"], correct: 0 },
        { q: "Bentuk desimal berulang $0.3333... = 0.\\bar{3}$ jika diubah ke pecahan biasa adalah...", options: ["1/3", "3/10", "2/3", "3/99", "1/9"], correct: 0 },
        { q: "Suku kedua deret geometri tak hingga adalah 4 dan jumlahnya 16. Suku pertamanya ($a$) adalah...", options: ["8", "6", "4", "10", "12"], correct: 0 },
        { q: "Jika suku-suku deret geometri tak hingga positif berjumlah 10 dan jumlah suku-suku genapnya adalah 4, maka suku pertamanya adalah...", options: ["6", "5", "4", "8", "2"], correct: 0 },
        { q: "Jumlah deret aritmatika tidak terhingga bernilai...", options: ["Selalu tak terhingga $(\\infty)$ kecuali beda nol", "Nol", "Konvergen", "Sama dengan suku pertama", "Terbatas"], correct: 0 },
        { q: "Nilai dari $\\sum_{n=1}^{\\infty} \\left(\\frac{1}{2}\\right)^n$ adalah...", options: ["1", "1/2", "2", "1/4", "Tak hingga"], correct: 0 },
        { q: "Sifat $\\sum (a_k + b_k) = \\sum a_k + \\sum b_k$ dinamakan sifat...", options: ["Linearitas sumasi", "Distributif", "Komutatif", "Asosiatif", "Refleksi"], correct: 0 },
        { q: "Jika $S_n = 2n^2 + n$, maka rumus suku ke-$n$ ($U_n$) adalah...", options: ["$4n - 1$", "$4n + 1$", "$2n + 1$", "$n^2 + 2$", "$4n$"], correct: 0 },
        { q: "Suatu bola dijatuhkan dari ketinggian 10 meter dan memantul kembali dengan ketinggian 3/4 dari tinggi semula. Panjang lintasan seluruhnya sampai bola berhenti adalah...", options: ["70 meter", "50 meter", "40 meter", "80 meter", "60 meter"], correct: 0 },
        { q: "Rumus cepat panjang lintasan bola memantul $(\\text{Lintasan naik + turun})$ adalah...", options: ["$S = \\frac{h(a + b)}{b - a}$", "$S = \\frac{a + b}{h}$", "$S = h \\cdot \\frac{b}{a}$", "$S = \\frac{h}{1 - r}$", "$S = 2 \\cdot \\frac{h}{1-r}$"], correct: 0 },
        { q: "Jika rasio deret geometri tak hingga bernilai $r = -1/2$ dan $a = 6$, jumlah tak hingganya adalah...", options: ["4", "12", "8", "2", "6"], correct: 0 },
        { q: "Deret $1 - 1/2 + 1/4 - 1/8 + ...$ merupakan deret geometri tak hingga dengan jumlah $S_\\infty = $...", options: ["2/3", "1/2", "1", "4/3", "3/4"], correct: 0 },
        { q: "Nilai dari $\\lim_{n \\to \\infty} \\frac{3n^2 - 1}{n^2 + 5}$ dapat dikaitkan dengan limit barisan bernilai...", options: ["3", "0", "Tak hingga", "1/5", "-1/5"], correct: 0 },
        { q: "Jika jumlah tak hingga deret geometri adalah $4a$ dan suku pertamanya $a$, maka rasio $r$ adalah...", options: ["3/4", "1/4", "1/2", "2/3", "1/3"], correct: 0 },
        { q: "Suku ke-3 suatu deret geometri tak hingga adalah 2 dan jumlahnya 8. Suku pertamanya adalah...", options: ["4 atau 8", "2", "6", "10", "1"], correct: 0 },
        { q: "Notasi sigma $\\sum_{i=1}^{3} 5$ (konstanta) bernilai...", options: ["15 ($5+5+5$)", "5", "10", "20", "0"], correct: 0 }
    ];

    // ==========================================
    // 3. FISIKA KEJURUAN
    // ==========================================

    // --- FISIKA LEVEL 16: Optik Geometri & Cermin/Lensa ---
    window.MASTER_QUESTION_BANK.fisika[16] = [
        { q: "Hukum Pemantulan Cahaya (Snellius Pemantulan) menyatakan bahwa...", options: ["Sudut datang ($i$) sama dengan sudut pantul ($r$)", "Sudut datang lebih besar dari sudut pantul", "Sinar pantul sejajar normal", "Sudut bias sama dengan sudut datang", "Tidak ada hukum khusus"], correct: 0 },
        { q: "Hubungan antara Jarak Fokus ($f$) dan Jari-jari kelengkungan cermin ($R$) adalah...", options: ["$f = 1/2 R$", "$f = R$", "$f = 2R$", "$f = R^2$", "$f = 1/R$"], correct: 0 },
        { q: "Persamaan umum Cermin dan Lensa (Dalil Esik) adalah...", options: ["$\\frac{1}{f} = \\frac{1}{s} + \\frac{1}{s'}$", "$\\frac{1}{f} = s + s'$", "$f = s \\cdot s'$", "$s = f + s'$", "$f = \\frac{s s'}{s - s'}$"], correct: 0 },
        { q: "Rumus Perbesaran Bayangan ($M$) pada cermin/lensa adalah...", options: ["$M = |\\frac{s'}{s}| = \\frac{h'}{h}$", "$M = \\frac{s}{s'}$", "$M = h \\cdot h'$", "$M = f / s$", "$M = s + s'$"], correct: 0 },
        { q: "Cermin Cekung dan Lensa Cembung memiliki sifat fokus bernilai...", options: ["Positif ($f > 0$) / Konvergen", "Negatif ($f < 0$) / Divergen", "Nol", "Tak hingga", "Bervariasi"], correct: 0 },
        { q: "Cermin Cembung dan Lensa Cekung memiliki sifat fokus bernilai...", options: ["Negatif ($f < 0$) / Divergen", "Positif ($f > 0$) / Konvergen", "Nol", "Tak hingga", "Selalu nyata"], correct: 0 },
        { q: "Kekuatan Lensa ($P$) dalam satuan Dioptri ($D$) yang memiliki fokus $f$ (dalam meter) dirumuskan...", options: ["$P = \\frac{1}{f}$", "$P = f$", "$P = \\frac{100}{f}$ (dalam cm)", "$P = f^2$", "$P = 2/f$"], correct: 0 },
        { q: "Benda diletakkan 15 cm di depan cermin cekung berfokus 10 cm. Jarak bayangannya ($s'$) adalah...", options: ["30 cm", "15 cm", "6 cm", "20 cm", "45 cm"], correct: 0 },
        { q: "Perbesaran bayangan pada soal cermin cekung di atas adalah...", options: ["2 kali", "1 kali", "0.5 kali", "3 kali", "4 kali"], correct: 0 },
        { q: "Sifat bayangan nyata yang dibentuk oleh cermin/lensa selalu...", options: ["Terbalik", "Tegak", "Maya", "Diperbesar selalu", "Di tak hingga"], correct: 0 },
        { q: "Sifat bayangan maya yang dibentuk oleh cermin/lensa selalu...", options: ["Tegak", "Terbalik", "Diperkecil selalu", "Nyata", "Di depan cermin"], correct: 0 },
        { q: "Indeks bias medium ($n$) dirumuskan sebagai perbandingan cepat rambat cahaya di ruang hampa ($c$) dengan kecepatan di medium ($v$), yaitu...", options: ["$n = c / v$", "$n = v / c$", "$n = c \\cdot v$", "$n = c - v$", "$n = 1/c$"], correct: 0 },
        { q: "Hukum Pembiasan Cahaya (Snellius Pembiasan) menyatakan bahwa...", options: ["$n_1 \\sin i = n_2 \\sin r$", "$n_1 \\sin i = n_2 \\cos r$", "$\\sin i = \\sin r$", "$n_1 \\cdot n_2 = \\sin i \\cdot \\sin r$", "$i = r$"], correct: 0 },
        { q: "Jika seberkas cahaya merambat dari medium kurang rapat ke lebih rapat ($n_1 < n_2$), maka cahaya akan dibiaskan...", options: ["Mendekati garis normal", "Menjauhi garis normal", "Lurus tidak dibiaskan", "Dipantulkan sempurna", "Sejajar bidang batas"], correct: 0 },
        { q: "Jika seberkas cahaya merambat dari medium lebih rapat ke kurang rapat ($n_1 > n_2$), maka cahaya akan dibiaskan...", options: ["Menjauhi garis normal", "Mendekati garis normal", "Tidak dibiaskan", "Berhenti", "Berbalik arah"], correct: 0 },
        { q: "Sudut kritis adalah sudut datang di medium rapat saat sudut bias di medium kurang rapat bernilai...", options: ["90°", "0°", "45°", "180°", "60°"], correct: 0 },
        { q: "Pemantulan sempurna (total internal reflection) terjadi apabila...", options: ["Sudut datang lebih besar dari sudut kritis ($i > \\theta_k$)", "Sudut datang lebih kecil dari sudut kritis", "Sudut datang sama dengan nol", "Medium luar lebih rapat", "Indeks bias sama"], correct: 0 },
        { q: "Lensa gabungan berfokus $f_1$ dan $f_2$ yang ditempel berimpit memiliki kekuatan lensa total ($P_{total}$) sebesar...", options: ["$P_1 + P_2$", "$P_1 \\cdot P_2$", "$P_1 - P_2$", "$1/P_1 + 1/P_2$", "$\\frac{P_1 P_2}{P_1 + P_2}$"], correct: 0 },
        { q: "Sebuah lensa cembung memiliki kekuatan $+2$ Dioptri. Panjang fokus lensa tersebut adalah...", options: ["0.5 meter (50 cm)", "2 meter", "0.2 meter", "1 meter", "10 cm"], correct: 0 },
        { q: "Cermin cembung selalu menghasilkan bayangan yang bersifat...", options: ["Maya, tegak, diperkecil", "Nyata, terbalik, diperbesar", "Nyata, tegak, diperbesar", "Maya, terbalik, diperkecil", "Sama besar dengan benda"], correct: 0 },
        { q: "Titik dekat mata normal (punctum proximum) manusia rata-rata pada usia dewasa adalah...", options: ["25 cm", "10 cm", "50 cm", "1 meter", "infinity"], correct: 0 },
        { q: "Titik jauh mata normal (punctum remotum) manusia normal berada di...", options: ["Tak hingga $(\\infty)$", "25 cm", "100 cm", "5 meter", "50 cm"], correct: 0 },
        { q: "Cacat mata rabun jauh (Miopi) dibantu dengan menggunakan kacamata berfokus...", options: ["Lensa Cekung (Negatif)", "Lensa Cembung (Positif)", "Lensa Silindris", "Lensa Doble Fokus", "Lensa Datar"], correct: 0 },
        { q: "Cacat mata rabun dekat (Hipermetropi) dibantu dengan menggunakan kacamata berfokus...", options: ["Lensa Cembung (Positif)", "Lensa Cekung (Negatif)", "Lensa Silindris", "Lensa Bifokal", "Lensa Datar"], correct: 0 },
        { q: "Cacat mata astigmatisma (silindris) disebabkan oleh bentuk kornea mata yang tidak melengkung sempurna, dibantu dengan...", options: ["Lensa Silindris", "Lensa Cekung", "Lensa Cembung", "Lensa Datar", "Lensa Kontak biasa"], correct: 0 }
    ];

    // --- FISIKA LEVEL 17: Listrik Searah (DC) & Hukum Kirchhoff ---
    window.MASTER_QUESTION_BANK.fisika[17] = [
        { q: "Kuat arus listrik ($I$) didefinisikan sebagai muatan listrik ($Q$) yang mengalir per satuan waktu ($t$), dirumuskan...", options: ["$I = Q / t$", "$I = Q \\cdot t$", "$I = V / R$", "$I = P / V$", "$I = R / V$"], correct: 0 },
        { q: "Hukum Ohm menyatakan hubungan antara Tegangan ($V$), Kuat Arus ($I$), dan Hambatan ($R$) yaitu...", options: ["$V = I \\cdot R$", "$I = V \\cdot R$", "$R = V \\cdot I$", "$V = I / R$", "$P = V \\cdot I$"], correct: 0 },
        { q: "Hambatan pengganti ($R_s$) untuk tiga resistor yang dirangkai secara SERI dirumuskan...", options: ["$R_s = R_1 + R_2 + R_3$", "$\\frac{1}{R_s} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\frac{1}{R_3}$", "$R_s = R_1 \\cdot R_2 \\cdot R_3$", "$R_s = \\frac{R_1 + R_2}{2}$", "$R_s = R_1 - R_2$"], correct: 0 },
        { q: "Hambatan pengganti ($R_p$) untuk tiga resistor yang dirangkai secara PARALEL dirumuskan...", options: ["$\\frac{1}{R_p} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\frac{1}{R_3}$", "$R_p = R_1 + R_2 + R_3$", "$R_p = \\frac{R_1 R_2}{R_1 + R_2}$", "$R_p = R_1 \\cdot R_2 \\cdot R_3$", "$R_p = R_1 - R_2$"], correct: 0 },
        { q: "Hukum I Kirchhoff (Hukum Titik Cabang) menyatakan bahwa jumlah kuat arus yang masuk titik cabang sama dengan...", q: "Hukum I Kirchhoff menyatakan jumlah arus masuk cabang sama dengan jumlah arus yang...", options: ["Keluar dari titik cabang $(\\Sigma I_{masuk} = \\Sigma I_{keluar})$", "Mengalir ke sumber tegangan", "Bernilai nol", "Tersimpan di kapasitor", "Terbuang sebagai kalor"], correct: 0 },
        { q: "Hukum II Kirchhoff (Hukum Loop Tertutup) menyatakan bahwa dalam satu rangkaian tertutup, jumlah aljabar GGL ($\\varepsilon$) dan penurunan potensial ($IR$) adalah...", options: ["Nol $(\\Sigma \\varepsilon + \\Sigma IR = 0)$", "Sama dengan arus total", "Sama dengan daya maksimum", "Bernilai satu", "Sama dengan hambatan dalam"], correct: 0 },
        { q: "Daya listrik ($P$) yang diserap oleh suatu hambatan $R$ yang dialiri arus $I$ dapat dirumuskan...", options: ["$P = I^2 \\cdot R = V^2 / R = V \\cdot I$", "$P = I \\cdot R^2$", "$P = V / I^2$", "$P = I / R$", "$P = V \\cdot R^2$"], correct: 0 },
        { q: "Energi listrik ($W$) yang digunakan alat berdaya $P$ selama waktu $t$ dirumuskan...", options: ["$W = P \\cdot t = V \\cdot I \\cdot t$", "$W = P / t$", "$W = I^2 \\cdot R$", "$W = V \\cdot R \\cdot t$", "$W = P^2 \\cdot t$"], correct: 0 },
        { q: "Satuan energi listrik yang biasa digunakan pada tagihan PLN rumah tangga adalah kWh (Kilowatt-hour), yang setara dengan...", options: ["$3,6 \\times 10^6\\text{ Joule}$", "$1000\\text{ Joule}$", "$3600\\text{ Joule}$", "$10^6\\text{ Joule}$", "$746\\text{ Joule}$"], correct: 0 },
        { q: "Faktor yang mempengaruhi besarnya hambatan suatu kawat penghantar ($R$) adalah...", options: ["Panjang kawat ($l$), luas penampang ($A$), dan hambatan jenis ($\\rho$)", "Kuat arus yang mengalir", "Tegangan sumber", "Waktu mengalir", "Suhu sekitar saja"], correct: 0 },
        { q: "Rumus hambatan kawat penghantar adalah...", options: ["$R = \\rho \\cdot \\frac{l}{A}$", "$R = \\rho \\cdot \\frac{A}{l}$", "$R = \\frac{l}{\\rho A}$", "$R = \\rho \\cdot l \\cdot A$", "$R = \\frac{A}{\\rho}$"], correct: 0 },
        { q: "Jika panjang kawat penghantar diperpanjang 2 kali dan luas penampangnya dijadikan setengahnya, maka hambatannya menjadi...", options: ["4 kali semula", "2 kali semula", "1/2 kali semula", "Tetap sama", "1/4 kali semula"], correct: 0 },
        { q: "Alat untuk mengukur Kuat Arus listrik dalam rangkaian dipasang secara...", options: ["Seri (Amperemeter)", "Paralel (Voltmeter)", "Bebas", "Menyilang", "Berlawanan"], correct: 0 },
        { q: "Alat untuk mengukur Tegangan listrik dalam rangkaian dipasang secara...", options: ["Paralel (Voltmeter)", "Seri (Amperemeter)", "Diagonal", "Terpisah", "Berurutan"], correct: 0 },
        { q: "Hambatan dalam ($r$) suatu sumber tegangan (baterai/aki) menyebabkan tegangan jepit ($V_{jepit}$) saat mengalirkan arus menjadi...", options: ["Lebih kecil dari GGL $(\\varepsilon - Ir)$", "Lebih besar dari GGL", "Sama persis dengan GGL", "Nol", "Tak terhingga"], correct: 0 },
        { q: "Rumus Tegangan Jepit pada sumber tegangan ber-GGL $\\varepsilon$ dan hambatan dalam $r$ yang mengalirkan arus $I$ adalah...", options: ["$V = \\varepsilon - I \\cdot r$", "$V = \\varepsilon + I \\cdot r$", "$V = I \\cdot r$", "$V = \\varepsilon$", "$V = \\frac{\\varepsilon}{r}$"], correct: 0 },
        { q: "Arus total ($I$) yang mengalir pada rangkaian sumber tegangan seri ber-GGL $n\\varepsilon$ dan hambatan total $(R + nr)$ adalah...", options: ["$I = \\frac{n\\varepsilon}{R + nr}$", "$I = \\frac{\\varepsilon}{R + r}$", "$I = \\frac{\\varepsilon}{nr}$", "$I = n \\cdot \\frac{V}{R}$", "$I = 0$"], correct: 0 },
        { q: "Tiga buah resistor masing-masing $3\\,\\Omega, 6\\,\\Omega,$ dan $9\\,\\Omega$ dirangkai secara SERI. Hambatan totalnya adalah...", options: ["18 Ω", "1.5 Ω", "9 Ω", "2 Ω", "54 Ω"], correct: 0 },
        { q: "Dua buah resistor $6\\,\\Omega$ dan $3\\,\\Omega$ dirangkai secara PARALEL. Hambatan penggantinya adalah...", options: ["2 Ω", "9 Ω", "18 Ω", "4.5 Ω", "1 Ω"], correct: 0 },
        { q: "Sebuah lampu bertuliskan $220\\text{ V}, 100\\text{ W}$. Hambatan dalam lampu tersebut adalah...", options: ["484 Ω", "22 Ω", "2200 Ω", "2.2 Ω", "48.4 Ω"], correct: 0 },
        { q: "Jika lampu 220V 100W dipasang pada sumber tegangan 110V, daya yang diserap lampu menjadi...", options: ["25 Watt", "50 Watt", "100 Watt", "200 Watt", "12.5 Watt"], correct: 0 },
        { q: "Jembatan Wheatstone adalah susunan rangkaian resistor yang digunakan untuk...", options: ["Menentukan besar hambatan yang belum diketahui nilainya secara presisi", "Menaikkan tegangan AC", "Menyimpan muatan listrik", "Mengubah arus DC ke AC", "Menyearahkan gelombang"], correct: 0 },
        { q: "Alat ukur multimeter gabungan dapat berfungsi sebagai...", options: ["Amperemeter, Voltmeter, dan Ohmmeter", "Transformator dan kapasitor", "Generator dan dinamo", "Accumulator", "Resistor variabel"], correct: 0 },
        { q: "Arus searah (DC - Direct Current) memiliki karakteristik aliran elektron yang...", options: ["Satu arah secara konstan dari kutub negatif ke positif", "Bolak-balik secara periodik", "Berputar melingkar", "Acak tidak beraturan", "Diam di tempat"], correct: 0 },
        { q: "Kalor yang timbul akibat mengalirnya arus listrik pada hambatan $R$ selama waktu $t$ dirumuskan oleh Hukum Joule yaitu...", options: ["$Q = I^2 \\cdot R \\cdot t$", "$Q = V \\cdot I \\cdot t^2$", "$Q = P / t$", "$Q = m \\cdot c \\cdot \\Delta T$", "$Q = I \\cdot R^2 \\cdot t$"], correct: 0 }
    ];

    // ==========================================
    // 4. BAHASA INDONESIA
    // ==========================================

    // --- INDO LEVEL 16: Analisis Kritis Teks & Paragraf Rumpang ---
    window.MASTER_QUESTION_BANK.indo[16] = [
        { q: "Paragraf Rumpang adalah paragraf yang di dalamnya terdapat bagian yang...", options: ["Rumpang / Kosong (dihilangkan untuk diisi kata atau kalimat yang tepat)", "Penuh dengan kesalahan ejaan", "Dicetak miring seluruhnya", "Tidak memiliki tanda baca", "Terlalu panjang"], correct: 0 },
        { q: "Langkah pertama dalam melengkapi paragraf rumpang adalah...", options: ["Mencermati kalimat sebelum dan sesudah bagian yang rumpang untuk memahami konteks", "Langsung menebak pilihan jawaban", "Menghitung jumlah huruf", "Membaca paragraf terakhir saja", "Mengabaikan kalimat utama"], correct: 0 },
        { q: "Kata atau frasa pengisi bagian rumpang harus memenuhi syarat...", options: ["Kohesi (kepaduan bentuk) dan Koherensi (keselarasan makna)", "Menggunakan kata asing yang sulit", "Berukuran sangat panjang", "Berbeda topik total", "Menggunakan singkatan bebas"], correct: 0 },
        { q: "Analisis kritis sebuah teks bacaan menuntut pembaca untuk mampu...", options: ["Menilai keakuratan fakta, logika penalaran, dan objektivitas penulis secara mendalam", "Membaca teks secepat kilat tanpa paham", "Menghafal seluruh isi teks luar kepala", "Menerjemahkan teks ke bahasa Inggris", "Menghitung jumlah kata dalam teks"], correct: 0 },
        { q: "Kalimat rumpang pada petunjuk kerja (prosedur) biasanya diisi dengan kata kerja...", options: ["Imperatif (perintah) atau verba material", "Adjektiva penilai", "Konjungsi antarkalimat", "Keterangan waktu lampau", "Pronomina persona"], correct: 0 },
        { q: "Dalam melengkapi kalimat rumpang berpola sebab-akibat, konjungsi yang tepat di tengah kalimat adalah...", options: ["Karena / sebab / sehingga", "Namun demikian,", "Oleh karena itu,", "Selain itu,", "Sebaliknya,"], correct: 0 },
        { q: "Evaluasi kritis terhadap keandalan sumber data dalam suatu artikel berita meninjau aspek...", options: ["Kredibilitas lembaga penerbit dan keaslian fakta narasumber", "Keindahan warna sampul berita", "Jumlah halaman cetak", "Harga surat kabar", "Nama panggilan wartawan"], correct: 0 },
        { q: "Bagian rumpang yang terletak di akhir paragraf argumentasi umumnya diisi oleh kalimat...", options: ["Simpulan / penegasan ulang pendapat penulis", "Kalimat tanya terbuka", "Awal perkenalan topik baru", "Judul karangan", "Kata seru"], correct: 0 },
        { q: "Jika bagian rumpang di tengah kalimat majemuk bertentangan diisi dengan kata hubung, pilihan yang tepat adalah...", options: ["Tetapi / melainkan / sedangkan", "Dan / serta", "Atau / maupun", "Karena / sebab", "Agar / supaya"], correct: 0 },
        { q: "Menganalisis bias dalam sebuah teks tajuk rencana berarti mencermati...", options: ["Kecenderungan keberpihakan redaksi yang mungkin tidak seimbang", "Jumlah iklan yang terpasang", "Ukuran huruf yang dipakai", "Jumlah paragraf berita", "Waktu terbit koran"], correct: 0 },
        { q: "Kalimat rumpang pada teks laporan observasi rincian bagian (deskripsi bagian) diisi dengan...", options: ["Ciri fisik, bagian-bagian objek, atau fungsi spesifik", "Opini pribadi pembaca", "Puisi kiasan sastra", "Dongeng fiktif masa lalu", "Kritik pedas politik"], correct: 0 },
        { q: "Uji validitas informasi dalam teks nonfiksi dilakukan dengan mencocokkan isi teks dengan...", options: ["Kenyataan empiris dan sumber data ilmiah terpercaya", "Khayalan penulis", "Pendapat mayoritas anak-anak", "Cerita sinetron", "Mitos masyarakat"], correct: 0 },
        { q: "Dalam soal melengkapi teks rumpang dialog negosiasi, jawaban yang tepat harus disesuaikan dengan...", options: ["Konteks kesantunan dan kesesuaian respons tawar-menawar", "Keinginan sepihak penawar", "Emosi kemarahan pembeli", "Bahasa sandi rahasia", "Durasi waktu percakapan"], correct: 0 },
        { q: "Teks ulasan (resensi) yang dikritisi secara kritis akan menilai keunggulan dan...", options: ["Kelemahan / kekurangan karya secara objektif", "Harga jual buku di toko", "Biaya cetak penerbit", "Jumlah halaman kosong", "Warna tinta cetakan"], correct: 0 },
        { q: "Pernyataan yang bersifat asumsi dalam teks analisis kritis ditandai oleh...", options: ["Sifatnya yang berupa dugaan sementara dan belum teruji kebenarannya", "Kepastian hukum mutlak", "Data statistik laboratorium BPS", "Angka tahun kemerdekaan", "Rumus fisika baku"], correct: 0 },
        { q: "Jika sebuah paragraf eksposisi rumpang membahas proses daur ulang sampah, kalimat lanjutannya harus...", options: ["Melanjutkan tahapan proses daur ulang secara kronologis logis", "Membahas sejarah kerajaan nusantara", "Menceritakan resep memasak kue", "Mengulas teknik mesin bubut", "Mengajak pembaca tidur"], correct: 0 },
        { q: "Kritik sastra atau teks secara konstruktif harus disertai dengan...", options: ["Alasan logis dan bukti kutipan teks yang mendukung", "Hinaan fisik penulis", "Pembakaran buku karya", "Pujian palsu berlebihan", "Penolakan membaca"], correct: 0 },
        { q: "Pesan tersirat (implisit) dalam sebuah paragraf dapat ditemukan melalui...", options: ["Penyimpulan mendalam dari makna keseluruhan konteks kalimat", "Membaca huruf pertama setiap baris", "Menghitung jumlah tanda baca titik", "Melihat ukuran font teks", "Menerjemahkan ke bahasa asing"], correct: 0 },
        { q: "Kalimat rumpang pada teks editorial yang meminta solusi penutup diisi dengan kalimat yang mengandung...", options: ["Saran konstruktif dan rekomendasi penyelesaian masalah", "Cacian tanpa arah", "Pertanyaan membingungkan", "Cerita horor", "Pujian kosong"], correct: 0 },
        { q: "Pendapat yang disampaikan tanpa landasan data pendukung yang valid dalam teks ilmiah dikategorikan sebagai...", options: ["Opini lemah / spekulasi tidak berdasar", "Fakta mutlak", "Teori baku", "Hukum alam", "Data empiris"], correct: 0 },
        { q: "Kelayakan isi sebuah artikel ilmiah populer diuji berdasarkan tingkat...", options: ["Relevansi, kebaruan, dan validitas data pendukung", "Kerumitan bahasa asingnya", "Ketebalan kertas cetak", "Jumlah gambar ilustrasi", "Popularitas penulis di media sosial"], correct: 0 },
        { q: "Paragraf rumpang jenis penutup laporan biasanya memerlukan kalimat yang merangkum...", options: ["Hasil keseluruhan pengamatan dan simpulan akhir", "Awal mula penelitian", "Biografi ketua tim peneliti", "Daftar belanja alat", "Nomor telepon instansi"], correct: 0 },
        { q: "Membaca secara kritis (critical reading) melibatkan aktivitas mental berupa...", options: ["M mempertanyakan, menganalisis, dan mengevaluasi argumen penulis", "Menerima mentah-mentah semua isi tulisan", "Mengingat warna sampul buku", "Menghafal urutan kata", "Membaca sambil tidur"], correct: 0 },
        { q: "Bagian rumpang pada kalimat perbandingan bertingkat memerlukan kata pengisi seperti...", options: ["Lebih ... daripada ... / paling ...", "Karena ... sehingga ...", "Meskipun ... tetapi ...", "Pertama ... lalu ...", "Jika ... maka ..."], correct: 0 },
        { q: "Tujuan pengujian konsistensi argumen dalam analisis kritis teks adalah untuk memastikan...", options: ["Tidak ada pertentangan gagasan antara paragraf awal dan akhir", "Penulis menggunakan font yang sama", "Jumlah kata genap", "Teks mudah dihafal", "Tidak ada titik koma"], correct: 0 }
    ];

    // --- INDO LEVEL 17: Rangkuman, Simpulan & Invensi Teks ---
    window.MASTER_QUESTION_BANK.indo[17] = [
        { q: "Rangkuman (Ringkasan) teks adalah bentuk ringkas dari suatu karangan dengan tetap...", options: ["Mempertahankan urutan isi dan gagasan asli penulis tanpa mengubah maksud", "Mengubah total alur cerita asli", "Menambahkan opini pribadi seluas-luasnya", "Memperpanjang jumlah kalimat", "Menghilangkan seluruh data angka"], correct: 0 },
        { q: "Simpulan (Kesimpulan) teks adalah...", options: ["Intisari atau pendapat akhir yang ditarik berdasarkan uraian teks secara keseluruhan", "Judul teks bacaan", "Kalimat pertama paragraf", "Daftar pustaka karangan", "Kutipan langsung pengarang"], correct: 0 },
        { q: "Perbedaan utama Rangkuman dan Simpulan adalah...", options: ["Rangkuman memuat ringkasan seluruh isi secara utuh, Simpulan merupakan intisari/pendapat akhir dari penalaran teks", "Rangkuman berupa puisi, Simpulan berupa angka", "Simpulan lebih panjang dari teks asli", "Rangkuman dibuat tanpa membaca teks", "Tidak ada perbedaan fungsi"], correct: 0 },
        { q: "Langkah pertama dalam menyusun rangkuman teks bacaan yang panjang adalah...", options: ["Membaca teks asli secara keseluruhan untuk memahami gagasan utama tiap paragraf", "Langsung menulis kalimat terakhir", "Menghafal seluruh kata sulit", "Menerjemahkan teks", "Membuat daftar pustaka"], correct: 0 },
        { q: "Dalam merangkum sebuah teks, hal yang harus DIHINDARI adalah...", options: ["Memasukkan pendapat atau komentar pribadi penyusun ringkasan", "Menuliskan gagasan utama asli", "Meringkas kalimat panjang", "Menggunakan bahasa sendiri yang ringkas", "Menjaga keutuhan isi"], correct: 0 },
        { q: "Invensi dalam konteks penulisan teks bermakna...", options: ["Penciptaan atau penemuan gagasan baru / sudut pandang segar yang kreatif", "Pencurian ide orang lain", "Pengulangan teks lama secara utuh", "Penerjemahan kamus", "Kesalahan penulisan ejaan"], correct: 0 },
        { q: "Ciri simpulan yang baik dan sah dalam teks argumentasi/eksposisi adalah...", options: ["Berasal langsung dari penalaran isi teks dan bersifat logis", "Berisi ancaman kepada pembaca", "Berupa kalimat tanya terbuka", "Bertentangan dengan isi teks", "Sangat subjektif emosional"], correct: 0 },
        { q: "Jika teks membahas dampak negatif sampah plastik dan solusi daur ulangnya, maka simpulan yang tepat adalah...", options: ["Pengelolaan sampah plastik melalui daur ulang sangat mendesak untuk menyelamatkan lingkungan", "Sampah plastik sangat indah dipandang", "Semua pabrik plastik harus dibakar", "Plastik tidak berbahaya sama sekali", "Pemerintah harus melarang orang berbelanja"], correct: 0 },
        { q: "Rangkuman teks eksplanasi fenomena alam harus mencakup unsur...", options: ["Pernyataan umum fenomena dan inti proses urutan kejadiannya", "Pendapat pribadi tentang cuaca", "Kritik terhadap pemerintah", "Cerita fiksi horor", "Daftar harga alat"], correct: 0 },
        { q: "Proses penarikan simpulan secara induktif dilakukan dengan cara...", options: ["Menarik intisari umum dari uraian khusus di setiap paragraf teks", "Menyalin kalimat pertama secara utuh", "Mengambil kesimpulan sebelum membaca teks", "Mencatat kata depan", "Menghitung jumlah titik"], correct: 0 },
        { q: "Proses penarikan simpulan secara deduktif dilakukan dengan cara...", options: ["Menyampaikan prinsip umum terlebih dahulu lalu menegaskan rincian khususnya", "Menyusun kalimat secara acak", "Mulai dari contoh terkecil", "Tanpa menggunakan premis", "Mengabaikan gagasan utama"], correct: 0 },
        { q: "Karangan ringkas hasil merangkum beberapa buku atau artikel dengan tema sejenis dinamakan...", options: ["Sinopsis / Ikhtisar / Resensi", "Novel fiksi", "Puisi bebas", "Naskah drama", "Surat pribadi"], correct: 0 },
        { q: "Sinopsis lazim digunakan untuk merangkum karya sastra berbentuk...", options: ["Novel, cerita pendek, film, atau drama", "Laporan keuangan perusahaan", "Petunjuk perakitan mesin", "Jurnal kedokteran", "Undangan rapat"], correct: 0 },
        { q: "Hal yang TIDAK boleh diubah saat membuat ringkasan isi buku adalah...", options: ["Gagasan pokok dan sudut pandang pengarang asli", "Jumlah halaman buku secara persis", "Warna sampul buku", "Nama penerbit buku", "Harga buku di toko"], correct: 0 },
        { q: "Kriteria keselarasan (koherensi) dalam menyusun simpulan teks berarti simpulan harus...", options: ["Selaras, sejalan, dan tidak bertentangan dengan isi keseluruhan teks", "Menggunakan bahasa asing", "Berupa angka statistik", "Ditulis dalam satu kalimat sangat panjang", "Memuat iklan komersial"], correct: 0 },
        { q: "Dalam soal ujian, pertanyaan 'Pernyataan yang sesuai dengan isi teks adalah...' menuntut peserta untuk mencari...", options: ["Informasi dalam pilihan ganda yang maknanya bersesuaian/sejalan dengan teks", "Pendapat pribadi peserta", "Argumen yang menentang teks", "Kalimat yang salah ejaannya", "Judul alternatif lain"], correct: 0 },
        { q: "Pertanyaan 'Pernyataan yang TIDAK SESUAI dengan isi teks adalah...' menuntut peserta mencari...", options: ["Pernyataan yang bertentangan atau tidak ada dalam teks", "Informasi utama teks", "Simpulan yang sah", "Gagasan pokok paragraf", "Fakta pendukung tesis"], correct: 0 },
        { q: "Kreativitas dalam invensi teks nonfiksi nampak pada kemampuan penulis dalam...", options: ["Menyajikan gagasan lama dengan kemasan sudut pandang baru yang lebih segar", "Menjiplak tulisan orang lain tanpa izin", "Mengubah fakta menjadi kebohongan", "Membuat kesalahan ejaan sengaja", "Menghilangkan daftar isi"], correct: 0 },
        { q: "Simpulan dalam teks berita jurnalistik biasanya terletak di bagian...", options: ["Akhir berita setelah pemaparan kronologi peristiwa", "Judul utama berita", "Nama reporter berita", "Foto ilustrasi", "Nama kota penerbit"], correct: 0 },
        { q: "Jika sebuah teks artikel memaparkan data penurunan produksi padi akibat hama dan solusi pupuk organik, simpulan teks tersebut adalah...", options: ["Penggunaan pupuk organik menjadi solusi efektif mengatasi penurunan produksi padi akibat hama", "Petani dilarang menanam padi", "Hama padi mustahil diberantas", "Harga beras akan turun drastis", "Pemerintah harus mengimpor semua beras"], correct: 0 },
        { q: "Ikhtisar berbeda dengan ringkasan dalam hal...", options: ["Ikhtisar tidak harus mempertahankan urutan karangan asli (lebih bebas mengambil inti sari)", "Ikhtisar lebih panjang dari buku asli", "Ikhtisar memuat seluruh kata asli", "Ringkasan dilarang memakai titik", "Tidak ada perbedaan"], correct: 0 },
        { q: "Syarat mutlak agar rangkuman mudah dipahami pembaca lain adalah...", options: ["Bahasa ringkasan harus komunikatif, runtut, dan gramatikal", "Menggunakan sandi rahasia", "Dicetak dengan huruf kapital semua", "Tanpa menggunakan tanda baca", "Berbentuk tabel angka"], correct: 0 },
        { q: "Penyusunan simpulan teks persuasi (ajakan) umumnya memuat unsur...", options: ["Imbauan atau dorongan agar pembaca melakukan tindakan positif sesuai isi teks", "Ancaman sanksi hukum", "Kritik tajam tanpa solusi", "Cerita lucu hiburan", "Iklan produk niaga"], correct: 0 },
        { q: "Makna kata 'Invensi' dalam bidang inovasi teknologi dan penulisan sains merujuk pada...",options: ["Penciptaan sesuatu yang benar-benar baru melalui proses berpikir kreatif", "Peniruan produk lama", "Kerusakan mesin", "Penghentian proyek", "Pembelian paten"], correct: 0 },
        { q: "Evaluasi akhir terhadap ketepatan sebuah simpulan teks diuji dengan pertanyaan...", options: ["Apakah simpulan ini ditarik secara logis dari premis-premis/fakta yang ada di dalam teks?", "Apakah penulisnya sudah terkenal?", "Apakah warna kertasnya bagus?", "Berapa jumlah paragraf teks tersebut?", "Apakah ada gambar ilustrasinya?"], correct: 0 }
    ];

    // ==========================================
    // 5. BAHASA INGGRIS TEKNIK
    // ==========================================

    // --- INGGRIS LEVEL 16: Procedure Text: Technical Manuals Analysis ---
    window.MASTER_QUESTION_BANK.inggris[16] = [
        { q: "A Procedure Text (Technical Manual) is designed to...", options: ["Provide step-by-step instructions on how to assemble, operate, or maintain equipment", "Tell a fictional adventure story", "Persuade readers to vote in an election", "Describe a historical event", "Express personal poetry"], correct: 0 },
        { q: "The structure of a technical procedure manual typically consists of...", options: ["Goal/Aim - Materials/Tools - Step-by-step Instructions", "Thesis - Arguments - Reiteration", "Orientation - Complication - Resolution", "Introduction - Body - Conclusion", "Abstract - References - Index"], correct: 0 },
        { q: "Which verb tense is most dominantly used in technical procedure instructions?", options: ["Imperative (Base verbs / V1 at the beginning of sentences)", "Past Continuous", "Present Perfect", "Past Perfect", "Future Continuous"], correct: 0 },
        { q: "Example of an imperative sentence in a technical manual is...", options: ["Disconnect the power supply before opening the panel.", "The power supply was disconnected.", "Will you disconnect the power supply?", "Disconnecting the power supply is important.", "Power supply is disconnected."], correct: 0 },
        { q: "The 'Materials or Tools' section in a manual lists...", options: ["The required equipment, parts, and safety gear needed for the task", "The history of the factory", "The salary of the technicians", "The price of the machine", "The names of the authors"], correct: 0 },
        { q: "Sequence connectors commonly found in procedure manuals include...", options: ["First, Next, Then, After that, Finally", "Because, Due to, Since", "However, Although, Despite", "If, Unless, Provided that", "Who, Which, Whose"], correct: 0 },
        { q: "Read instruction: 'Ensure the engine is completely cold before draining the coolant.' What is the purpose of this instruction?", options: ["To prevent burns and injuries from hot coolant", "To make the engine run faster", "To paint the radiator", "To clean the garage", "To drain oil instead"], correct: 0 },
        { q: "Technical manuals emphasize safety warnings using words like...", options: ["CAUTION, WARNING, DANGER", "MAYBE, PERHAPS, POSSIBLY", "ENTERTAIN, FUN, ENJOY", "CHEAP, DISCOUNT, SALE", "SLOW, QUIET, PEACE"], correct: 0 },
        { q: "Read: 'Tighten the cylinder head bolts in a criss-cross pattern using a torque wrench set to 30 Nm.' What tool is required?", options: ["Torque wrench", "Hammer", "Pliers", "Screwdriver", "Weld torch"], correct: 0 },
        { q: "Why are technical manuals written in clear, concise, and direct language?", options: ["To prevent misunderstandings and ensure safe, correct operation", "To make the book heavy", "To confuse beginner workers", "To practice poetry skills", "To increase page count"], correct: 0 },
        { q: "Read: 'Lubricate all moving joints with high-temperature grease.' What material should be applied?", options: ["High-temperature grease", "Water", "Engine coolant", "Battery acid", "Fuel gasoline"], correct: 0 },
        { q: "What does the instruction 'Inspect for leaks' mean?", options: ["Check carefully if any fluid is escaping from joints or seals", "Clean the workshop floor", "Paint the machine exterior", "Fill the tank fully", "Turn off the lights"], correct: 0 },
        { q: "Adverbs of manner or degree in manuals (e.g., 'tighten securely', 'apply evenly') tell the technician...", options: ["How to perform the action correctly", "When the factory was built", "Who invented the machine", "How much the tool costs", "Where the office is"], correct: 0 },
        { q: "Read: 'Dispose of used motor oil according to local environmental regulations.' What should be done with old oil?", options: ["Disposed of properly following environmental rules", "Pour it into the drainage river", "Burn it openly in the backyard", "Drink it", "Leave it on the floor"], correct: 0 },
        { q: "The 'Troubleshooting' section in a technical manual is used to...", options: ["Identify common problems, symptoms, and corrective actions", "List warranty prices", "Sell spare parts", "Teach English grammar", "List employee attendance"], correct: 0 },
        { q: "Read: 'If the indicator light flashes red, shut down the system immediately.' What action should be taken if the light flashes red?", options: ["Shut down the system immediately", "Ignore the light", "Add more fuel", "Increase speed", "Clean the screen"], correct: 0 },
        { q: "In maintenance instructions, 'Preventive Maintenance' refers to...", options: ["Regular scheduled checks to prevent unexpected equipment failure", "Fixing machines only after they explode", "Buying new machines every week", "Hiring new guards", "Closing the workshop"], correct: 0 },
        { q: "Read: 'Calibrate the digital sensor annually.' How often should calibration be performed?", options: ["Every year (annually)", "Every month", "Every week", "Every day", "Never"], correct: 0 },
        { q: "Technical manuals often use diagrams, schematics, and exploded views to...", options: ["Help technicians visualize component assembly and part locations", "Decorate empty spaces", "Hide manufacturing flaws", "Increase book weight", "Confuse readers"], correct: 0 },
        { q: "Read: 'Do not exceed the maximum load limit of 500 kg.' What happens if you load 600 kg?", options: ["It exceeds the safe operational limit and may cause damage", "It works better", "It floats", "Fuel efficiency increases", "Nothing happens"], correct: 0 },
        { q: "The target reader of an equipment maintenance procedure is typically...", options: ["Qualified technicians and machine operators", "Elementary school students", "Novel readers", "Tourists", "Politicians"], correct: 0 },
        { q: "Read: 'Bleed the hydraulic brake system to remove trapped air bubbles.' Why is bleeding necessary?", options: ["To remove air bubbles that make brakes spongy/ineffective", "To add more weight", "To heat up the fluid", "To change fluid color", "To save fuel"], correct: 0 },
        { q: "What is the function of a 'Part Number' in a technical manual spare parts catalog?", options: ["To identify and order the exact replacement component accurately", "To show the weight of the mechanic", "To measure voltage", "To set the clock", "To calculate tax"], correct: 0 },
        { q: "Read: 'Store the precision measuring instruments in a dry, clean wooden box.' How should instruments be stored?", options: ["In a dry, clean wooden box", "On the wet floor", "Under direct sunlight", "In oil pools", "Outside in the rain"], correct: 0 },
        { q: "Why are procedural steps numbered sequentially (1, 2, 3...) rather than written in a paragraph block?", options: ["To guide the technician through the correct chronological order without skipping steps", "To make the text look colorful", "To reduce word count", "To hide difficult words", "To confuse readers"], correct: 0 }
    ];

    // --- INGGRIS LEVEL 17: Analytical Exposition Text Analysis ---
    window.MASTER_QUESTION_BANK.inggris[17] = [
        { q: "An Analytical Exposition text is designed to...", options: ["Persuade the reader that something is the case by presenting arguments/opinions", "Tell a fictional fairy tale", "Explain how to cook food step by step", "Describe a specific animal", "Report a historical news event"], correct: 0 },
        { q: "The structure of an Analytical Exposition text consists of...", options: ["Thesis - Arguments - Reiteration (Conclusion)", "Goal - Materials - Steps", "Orientation - Complication - Resolution", "General Classification - Description", "Abstract - Introduction - Methods"], correct: 0 },
        { q: "The 'Thesis' section in an analytical exposition text functions to...", options: ["Introduce the topic and state the author's point of view / position", "List tools and materials", "Summarize the conclusion only", "Tell a funny joke", "Give step-by-step instructions"], correct: 0 },
        { q: "The 'Arguments' section in an analytical exposition text contains...", options: ["Series of logical reasons and supporting evidence to back up the thesis", "Fictional characters dialog", "Recipe ingredients", "Weather forecasts", "Personal diary entries"], correct: 0 },
        { q: "The 'Reiteration' section in an analytical exposition text functions to...", options: ["Restate the author's point of view / reaffirm the thesis", "Start a new debate", "List spare part numbers", "Ask riddles", "Describe machine parts"], correct: 0 },
        { q: "Which language feature is commonly found in analytical exposition texts?", options: ["Emotive words, thinking verbs, causal conjunctions, and simple present tense", "Imperative commands only", "Past tense narrative style", "Fictional dialogues", "Recipe measurements"], correct: 0 },
        { q: "Thinking verbs (mental verbs) used in exposition texts to express viewpoint include...", options: ["Believe, think, realize, assume, doubt", "Run, jump, swim, weld", "Have, has, had", "Is, am, are, was", "Mix, stir, boil"], correct: 0 },
        { q: "Causal conjunctions used in exposition arguments to link reasons include...", options: ["Because, consequently, therefore, due to", "First, next, then", "Who, which, whose", "Where, when, why", "As... as, more than"], correct: 0 },
        { q: "Read thesis snippet: 'Electric vehicles are essential to reduce carbon emissions in modern cities.' This statement expresses...", options: ["The author's position/thesis on electric vehicles", "A recipe instruction", "A fictional story plot", "A weather report", "A parts catalog code"], correct: 0 },
        { q: "Unlike Hortatory Exposition, Analytical Exposition does NOT end with a...", options: ["Recommendation (what should or should not be done)", "Conclusion / Reiteration of stance", "Logical argument", "Thesis statement", "Title heading"], correct: 0 },
        { q: "The primary purpose of arguments in an analytical exposition is to answer the question...", options: ["'Why is this the case?' (providing reasons)", "'How do I build this?'", "'Where is the location?'", "'Who wrote this book?'", "'When was it made?'"], correct: 0 },
        { q: "Read argument snippet: 'First, data shows that EV adoption drops urban smog levels by 40%.' This sentence acts as...", options: ["An argument supporting the thesis with factual data", "A procedure step", "A fictional character quote", "A greeting statement", "A closing farewell"], correct: 0 },
        { q: "What is the tone typically adopted by an author in an analytical exposition?", options: ["Persuasive, critical, and logical", "Humorous and silly", "Angry and abusive", "Fictional and magical", "Doubtful and confused"], correct: 0 },
        { q: "Modal verbs indicating possibility or certainty used in exposition include...", options: ["Must, should, will, can, may", "Could have cooked", "Would have been", "Shall have had", "Might have gone"], correct: 0 },
        { q: "Read reiteration snippet: 'Therefore, shifting to electric transport is crucial for environmental sustainability.' This restates...", options: ["The author's initial thesis / core position", "A repair manual step", "A shopping list", "A grammar rule", "A tool specification"], correct: 0 },
        { q: "Which topic is most suitable for an analytical exposition text?", options: ["Why vocational school graduates are ready for modern industry", "How to bake a chocolate cake", "Cinderella story summary", "My unforgettable holiday in Bali", "The life cycle of a butterfly"], correct: 0 },
        { q: "In an analytical exposition, connectives of transition to link arguments (e.g., 'Furthermore', tulang 'In addition', 'Moreover') are used to...", options: ["Add supporting points smoothly", "Show contrast only", "Indicate past time", "Ask questions", "End the text abruptly"], correct: 0 },
        { q: "Why does the author use factual evidence and statistics in the arguments?", options: ["To make the arguments valid and convince the reader logically", "To fill blank spaces", "To confuse the audience", "To tell a lie", "To increase book price"], correct: 0 },
        { q: "Read: 'Some people argue that EVs are too expensive; however, long-term fuel savings outweigh the initial cost.' This sentence presents...", options: ["A counter-argument addressed and refuted by the author", "A procedure step", "A recipe instruction", "A dialogue script", "A tool catalog"], correct: 0 },
        { q: "An analytical exposition focuses on 'abstract issues' or opinions rather than...", options: ["Physical step-by-step assembly instructions of a machine", "Grammar rules", "Mathematical formulas", "Dictionary definitions", "Poetic rhymes"], correct: 0 },
        { q: "Which conjunction shows contrast between arguments?", options: ["However, On the other hand, In contrast", "Because, Therefore, Thus", "First, Second, Finally", "And, Moreover, Furthermore", "If, Unless, Provided"], correct: 0 },
        { q: "The word 'Exposition' in text genres comes from a Latin root meaning to...", options: ["Explain, set forth, or discuss a viewpoint", "Hide secrets", "Cook food", "Build a house", "Sing a song"], correct: 0 },
        { q: "If an analytical exposition argues against smoking in public, the thesis will state...", options: ["Public smoking must be banned due to health hazards", "How to grow tobacco plants", "History of cigarette manufacturing", "Recipe for herbal cigarettes", "Smoking prices in stores"], correct: 0 },
        { q: "Nominalization (turning verbs into nouns, e.g., 'develop' into 'development') is frequently used in exposition to create a style that is...", options: ["Formal and objective", "Casual and slang", "Spoken conversational", "Fictional and magical", "Poetic and lyrical"], correct: 0 },
        { q: "At the end of an analytical exposition reading test, the question 'What is the writer's argument about...?' requires you to identify...", options: ["The core reasons presented by the author to support their stance", "The physical tools used", "The price of the book", "The publication date", "The font style"], correct: 0 }
    ];

}
