// Bank Soal Otomotif Sepeda Motor (Level 1 - 10) - Pola Kunci: E, B, D, C, A

if (window.MASTER_QUESTION_BANK) {

    if (!window.MASTER_QUESTION_BANK.otomotif) {
        window.MASTER_QUESTION_BANK.otomotif = {};
    }

    // =========================================================================
    // LEVEL 1: PMMSM - Dasar Mesin Sepeda Motor (2-Tak & 4-Tak) - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[1] = [
        { q: "Pada mesin sepeda motor 4-tak, satu siklus kerja lengkap membutuhkan putaran poros engkol sebanyak...", options: ["1 putaran", "1,5 putaran", "3 putaran", "4 putaran", "2 putaran"], correct: 4 },
        { q: "Langkah di mana piston bergerak dari TMA ke TMB dan kedua katup tertutup akibat ledakan pembakaran dinamakan...", options: ["Langkah Hisap", "Langkah Usaha (Power)", "Langkah Kompresi", "Langkah Buang", "Langkah Bilas"], correct: 1 },
        { q: "Komponen mesin 2-tak yang berfungsi menggantikan peran katup masuk dan katup buang adalah...", options: ["Poros nok (Camshaft)", "Rocker arm", "Saluran bilas & lubang membran (Reed valve)", "Piston pin", "Katup solenoide"], correct: 2 },
        { q: "Proses masuknya campuran bahan bakar dan udara ke dalam ruang engkol pada motor 2-tak terjadi saat piston bergerak dari...", options: ["TMA ke TMB", "TMB ke TMA (Langkah Kompresi & Hisap bawah)", "TMA ke TMA lagi", "TMB ke TMB lagi", "Posisi tengah"], correct: 1 },
        { q: "Pada motor 4-tak, jika katup masuk terbuka dan katup buang tertutup saat piston bergerak dari TMA ke TMB, maka sedang terjadi...", options: ["Langkah Kompresi", "Langkah Usaha", "Langkah Buang", "Langkah Bilas", "Langkah Hisap"], correct: 4 },
        { q: "Komponen mesin yang berfungsi mengubah gerak naik-turun (translasi) piston menjadi gerak putar adalah...", options: ["Poros Nok (Camshaft)", "Poros Engkol (Crankshaft)", "Blok Silinder", "Batang Piston", "Flywheel"], correct: 1 },
        { q: "Pengertian dari TMA (Titik Mati Atas) pada mesin torak adalah...", options: ["Posisi tertinggi yang dicapai oleh piston di dalam silinder", "Posisi terendah piston", "Posisi tengah silinder", "Posisi katup terbuka penuh", "Posisi engkol miring"], correct: 0 },
        { q: "Komponen yang berfungsi mencegah kebocoran gas kompresi di antara piston dan dinding silinder adalah...", options: ["Piston pin", "Snap ring", "Ring kompresi", "Connecting rod", "Gasket head"], correct: 2 },
        { q: "Overlapping katup pada mesin 4-tak adalah kondisi di mana...", options: ["Kedua katup (masuk & buang) terbuka bersamaan di akhir langkah buang/awal hisap", "Kedua katup tertutup rapat", "Katup masuk saja yang terbuka", "Katup buang tertutup", "Poros nok berhenti"], correct: 0 },
        { q: "Satu putaran penuh poros engkol (360 derajat) pada mesin 2-tak menghasilkan langkah usaha sebanyak...", options: ["2 kali", "0,5 kali", "3 kali", "1 kali usaha", "4 kali"], correct: 3 },
        { q: "Penyebab utama mesin 2-tak membutuhkan oli samping (oli pelumas khusus) adalah...", options: ["Ruang engkol digunakan sebagai tempat penampungan campuran bahan bakar", "Pelumasan menggunakan sistem pompa basah", "Oli mesin 4-tak terlalu kental", "Mesin 2-tak tidak memiliki piston", "Mencegah poros engkol patah"], correct: 0 },
        { q: "Langkah buang pada motor 4-tak terjadi saat piston bergerak dari...", options: ["TMB ke TMA dengan katup buang terbuka", "TMA ke TMB", "TMB ke TMA katup tertutup", "TMA ke TMB katup masuk terbuka", "Posisi diam"], correct: 0 },
        { q: "Perbandingan kompresi mesin dirumuskan sebagai perbandingan antara...", options: ["Volume silinder total (Vs + Vc) dibanding Volume ruang bakar (Vc)", "Volume langkah dibanding volume minyak", "Diameter piston dibanding langkah", "Jumlah katup dibanding silinder", "Luas katup masuk dibanding buang"], correct: 0 },
        { q: "Bila diameter silinder (Bore) lebih besar dari panjang langkah piston (Stroke), tipe mesin tersebut dinamakan...", options: ["Long stroke engine", "Square engine", "Short stroke / Overbore engine", "Single engine", "Inline engine"], correct: 2 },
        { q: "Bila diameter silinder sama dengan panjang langkah piston, tipe mesin dinamakan...", options: ["Overbore", "Square engine", "Long stroke", "DOHC", "SOHC"], correct: 1 },
        { q: "Volume langkah ($V_s$) piston dengan diameter $D$ dan langkah $S$ dirumuskan...", options: ["$V_s = \\frac{1}{4} \\pi D^2 S$", "$V_s = \\pi D S$", "$V_s = D \\cdot S$", "$V_s = \\frac{1}{2} \\pi D S^2$", "$V_s = \\pi D^2$"], correct: 0 },
        { q: "Fungsi utama katup membran (Reed Valve) pada motor 2-tak adalah...", options: ["Mencegah campuran bahan bakar dan udara di ruang engkol mengalir balik ke karburator", "Mengatur oli samping", "Mengatur gas buang", "Mencegah piston aus", "Menyaring udara"], correct: 0 },
        { q: "Ciri khas utama kepala silinder motor 2-tak dibanding motor 4-tak adalah...", options: ["Tidak memiliki mekanisme katup (poros nok, rocker arm, dan katup)", "Memiliki 4 katup", "Menggunakan rantai mesin (Kamrat)", "Terbuat dari besi tuang tebal", "Tidak memiliki busi"], correct: 0 },
        { q: "Volume ruang bakar dinotasikan dengan $V_c$. Jika $V_s = 110\\text{ cc}$ dan $V_c = 10\\text{ cc}$, perbandingan kompresinya adalah...", options: ["11 : 1", "12 : 1", "10 : 1", "9 : 1", "8 : 1"], correct: 1 },
        { q: "Gas hasil pembakaran yang keluar berwarna putih tebal pada motor 2-tak merupakan indikasi...", options: ["Campuran oli samping terlalu banyak atau oli transmisi bocor ke ruang engkol", "Bensin terlalu irit", "Pengapian terlalu maju", "Kiprok rusak", "Piston terlalu longgar"], correct: 0 },
        { q: "Piston bergerak dari TMA ke TMB sejauh 50 mm. Jarak perjalanan piston tersebut dinamakan...", options: ["Panjang Langkah (Stroke)", "Diameter Silinder (Bore)", "Celah Piston", "Volume Karburator", "Tinggi Katup"], correct: 0 },
        { q: "Usaha pembakaran diterima langsung oleh komponen...", options: ["Piston / Torak", "Poros Nok", "Busi", "Karburator", "Katup Buang"], correct: 0 },
        { q: "Rantai mesin (Timing Chain / Rantai Kamrat) berfungsi menghubungkan putaran...", options: ["Poros Engkol ke Poros Nok", "Poros Engkol ke Roda Belakang", "Poros Nok ke Katup", "Piston ke Poros Engkol", "Kopling ke Transmisi"], correct: 0 },
        { q: "Gas sisa pembakaran yang belum terbakar sempurna didorong keluar pada langkah...", options: ["Buang (Exhaust)", "Hisap", "Kompresi", "Usaha", "Bilas"], correct: 0 },
        { q: "Keunggulan utama mesin 4-tak dibandingkan mesin 2-tak adalah...", options: ["Efisiensi bahan bakar lebih tinggi dan emisi gas buang lebih ramah lingkungan", "Minyak boros", "Konstruksi lebih sederhana", "Tenaga dua kali lipat", "Suara lebih bising"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 2: PMMSM - Komponen Mesin, Blok Silinder & Piston - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[2] = [
        { q: "Komponen mesin yang berfungsi sebagai tempat bergerak naik-turunnya piston adalah...", options: ["Kepala Silinder", "Blok Silinder", "Bak Engkol", "Mekanis Katup", "Karter"], correct: 1 },
        { q: "Fungsi dari ring oli (oil ring) yang terpasang pada piston adalah...", options: ["Menyeka sisa oli pelumas pada dinding silinder agar tidak masuk ke ruang bakar", "Menahan tekanan kompresi", "Mencegah piston kocak", "Menyerap panas busi", "Mengunci pin piston"], correct: 0 },
        { q: "Komponen yang menghubungkan piston dengan batang torak (connecting rod) adalah...", options: ["Crankpin", "Piston Pin (Pena Torak)", "Snap Ring", "Rocker Arm Pin", "Bolt Head"], correct: 1 },
        { q: "Sirip-sirip udara yang terdapat pada blok silinder mesin pendingin udara berfungsi untuk...", options: ["Memperluas bidang radiasi pelepasan panas mesin ke udara bebas", "Memperindah bentuk mesin", "Mengurangi berat blok", "Menahan getaran piston", "Tempat oli mengalir"], correct: 0 },
        { q: "Penyebab utama dinding silinder mengalami keausan tidak merata (tirus / oval) adalah...", options: ["Gesekan samping piston akibat gaya dorong batang torak dan kurangnya pelumasan", "Tekanan busi", "Suhu udara dingin", "Bensin terlalu irit", "Setelan rantai kamrat kencang"], correct: 0 },
        { q: "Tanda panah atau tulisan 'IN' atau 'EX' pada bagian atas mahkota piston bertujuan untuk...", options: ["Menentukan posisi pemasangan piston terhadap katup masuk/buang atau saluran buang", "Tanda merk piston", "Tanda diameter piston", "Tanda berat piston", "Ukuran celah"], correct: 0 },
        { q: "Celah antara piston dan dinding silinder (Piston clearance) harus sesuai spesifikasi bertujuan untuk...", options: ["Memberikan ruang pemuaian saat piston panas agar tidak macet (seizure)", "Agar bensin tidak bocor", "Agar oli cepat habis", "Menambah kecepatan motor", "Mencegah busi mati"], correct: 0 },
        { q: "Jika celah piston terlalu besar (melebihi batas servis), akibat yang timbul pada mesin adalah...", options: ["Suara mesin berisik (piston slap) dan kompresi bocor / asap putih", "Mesin langsung macet", "Kelistrikan mati", "Bensin menjadi sangat irit", "Katup terbakar"], correct: 0 },
        { q: "Gasket (paking) kepala silinder berfungsi untuk...", options: ["Mencegah kebocoran kompresi dan kebocoran oli/air pendingin antara blok dan kepala silinder", "Menahan piston", "Setel celah katup", "Menyaring bensin", "Menyerap getaran mesin"], correct: 0 },
        { q: "Dinding silinder yang terbuat dari bahan Sleeved Cylinder (Liner) memiliki kelebihan yaitu...", options: ["Dapat dikarter / di-overbore jika mengalami keausan", "Tidak memerlukan oli", "Bahan ringan dari plastik", "Tidak bisa aus", "Harganya sangat murah"], correct: 0 },
        { q: "Tindakan memperbesar diameter silinder yang aus dan mengganti piston dengan ukuran lebih besar dinamakan...", options: ["Bore-Up / Oversize / Overbore", "Tune-Up", "Overhaul total", "Overlapping", "Skir Katup"], correct: 0 },
        { q: "Ukuran piston standar jika dinaikkan sebesar 0,25 mm dinamakan oversize...", options: ["Oversize 25", "Oversize 50", "Oversize 100", "Oversize 0,25 cm", "Oversize 2,5"], correct: 0 },
        { q: "Gaya yang bekerja pada batang torak saat langkah usaha adalah gaya...", options: ["Tekan / Kompresi", "Tarik murni", "Puntir (Torsi)", "Geser", "Gesek"], correct: 0 },
        { q: "Pemasangan ring kompresi nomor 1 dan nomor 2 tidak boleh terbalik karena...", options: ["Memiliki profil penampang, ketahanan panas, dan fungsi penyekatan yang berbeda", "Beda diameter luar", "Beda bahan dari karet", "Membuat bensin banjir", "Merusak busi"], correct: 0 },
        { q: "Posisi celah (gap) antar ring piston saat dipasang pada piston HARUS...", options: ["Diselingi saling membelakangi (berselisih 120 atau 180 derajat) dan tidak boleh sejajar", "Sejajar searah pena piston", "Sejajar searah tanda panah", "Bebas berhimpitan", "Di bagian bawah semua"], correct: 0 },
        { q: "Nomenklatur 'DiASil Cylinder' atau 'Nikasil' pada blok silinder aluminium berfungsi untuk...", options: ["Melapisi dinding silinder dengan bahan silikon/nikel agar tahan gesekan tanpa butuh liner besi", "Membuat blok menjadi transparan", "Mencegah oli masuk", "Setel celah katup", "Menyimpan bensin"], correct: 0 },
        { q: "Pena piston terkunci pada tempatnya di dalam piston menggunakan alat pengunci berupa...", options: ["Snap Ring / Circlip", "Baut 10 mm", "Pin cotter", "Pasak piringan", "Ring plat"], correct: 0 },
        { q: "Mahkota piston (Piston Crown) dirancang cembung, datar, atau cekung bertujuan untuk...", options: ["Membentuk rasio kompresi dan mengarahkan aliran efisiensi pembakaran", "Menyesuaikan berat piston", "Gaya tampilan", "Dudukan busi", "Menahan oli"], correct: 0 },
        { q: "Kepala silinder terbuat dari bahan paduan aluminium (Aluminum Alloy) terutama karena...", options: ["Ringan dan memiliki daya hantar panas (konduktivitas) yang sangat baik", "Murah harganya", "Tahan benturan martil", "Warna mengkilap", "Mudah dilas biasa"], correct: 0 },
        { q: "Baut kepala silinder dikencangkan menggunakan kunci momen (Torque Wrench) bertujuan agar...", options: ["Mencapai tingkat kekencangan yang merata sesuai spesifikasi agar tidak melengkung", "Baut tidak bisa dilepas lagi", "Cepat selesai", "Dapat diputar tangan", "Menghemat tenaga"], correct: 0 },
        { q: "Bila terjadi keausan dinding silinder di bagian atas lebih besar daripada bagian bawah, hal ini disebut...", options: ["Ketirusan (Taper)", "Keovalan (Out of round)", "Keolengan", "Keretakan", "Celah piston"], correct: 0 },
        { q: "Bila perbedaan diameter horizontal dan vertikal silinder berbeda pada posisi yang sama, dinamakan...", options: ["Keovalan (Out of Round)", "Ketirusan", "Kerataan", "Kehalusan", "Keolengan"], correct: 0 },
        { q: "Kerusakan 'Piston Seizure' (Piston Ceket/Macet) umumnya disebabkan oleh...", options: ["Overheating dan kegagalan sistem pelumasan", "Bensin basi", "Busi kotor", "Rantai kendor", "Aki tekor"], correct: 0 },
        { q: "Pembersihan kerak karbon pada mahkota piston dan kepala silinder dilakukan saat servis...", options: ["Skir katup / Skrap ruang bakar", "Ganti oli ganda", "Setel rantai roda", "Ganti ban", "Setel rem"], correct: 0 },
        { q: "Ruang bakar tipe Hemisphere (Setengah Lingkaran) memiliki keunggulan...", options: ["Efisiensi panas tinggi dan permukaan pelepasan panas minim", "Bisa muat 8 katup", "Bentuk kotak", "Bisa tanpa busi", "Tidak butuh paking"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 3: PMMSM - Mekanisme Katup & Setel Celah Katup - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[3] = [
        { q: "Tipe mekanisme katup di mana poros nok berada di kepala silinder dan menggerakkan katup secara langsung atau via rocker arm adalah...", options: ["OHV (Overhead Valve)", "SOHC (Single Overhead Camshaft)", "DOHC (Double Overhead Camshaft)", "SV (Side Valve)", "Rotary Valve"], correct: 1 },
        { q: "Fungsi utama pegas katup (Valve Spring) adalah...", options: ["Mendorong katup agar kembali menutup rapat setelah tertekan oleh nok", "Membuka katup", "Menahan oli pelumas", "Mengatur celah busi", "Mencegah katup patah"], correct: 0 },
        { q: "Alat ukur presisi yang wajib digunakan untuk mengukur celah katup adalah...", options: ["Mistar baja", "Feeler Gauge (Bilah Ukur)", "Micrometer", "Jangka sorong", "Dial Gauge"], correct: 1 },
        { q: "Penyetelan celah katup HARUS dilakukan pada posisi piston berada di...", options: ["TMA Langkah Kompresi (Kedua katup bebas/bebas tekan)", "TMB Langkah Hisap", "TMA Langkah Buang", "TMB Langkah Usaha", "Bebas di mana saja"], correct: 0 },
        { q: "Akibat yang terjadi jika celah katup disetel TERLALU RAPAT (hampir nol) adalah...", options: ["Katup tidak menutup rapat saat panas, kompresi bocor, dan katup bisa terbakar", "Suara mesin berisik ketiak", "Bensin menjadi sangat irit", "Tenaga mesin bertambah 2 kali", "Oli mesin tidak mengalir"], correct: 0 },
        { q: "Akibat yang terjadi jika celah katup disetel TERLALU RENGGANG adalah...", options: ["Timbul suara berisik (ngelitik/knocking) dan bukaan katup tidak maksimal", "Kompresi bocor", "Mesin macet seketika", "Busi cepat putus", "Oli bocor"], correct: 0 },
        { q: "Untuk menemukan posisi TMA Kompresi saat setel katup, tanda 'T' pada magnet harus tepat sejajar dengan...", options: ["Tanda garis penyesuai pada lubang pengintip di bak mesin", "Tanda spul", "Rantai roda", "Baut katup", "Poros engkol bawah"], correct: 0 },
        { q: "Proses merapatkan permukaan daun katup dengan dudukan katup (valve seat) menggunakan skir/grinding paste dinamakan...", options: ["Skir Katup (Valve Lapping)", "Skrap ruang bakar", "Bore-up", "Overhaul", "Tune-up"], correct: 0 },
        { q: "Komponen yang menahan oli pelumas dari kepala silinder agar tidak mengalir masuk ke batang katup dinamakan...", options: ["Seal Katup (Valve Stem Seal)", "Ring piston", "Gasket", "O-ring carbu", "Sim katup"], correct: 0 },
        { q: "Perbedaan utama SOHC dan DOHC terletak pada...", options: ["Jumlah poros nok di kepala silinder (SOHC 1 poros nok, DOHC 2 poros nok)", "Jumlah piston", "Jumlah busi", "Jenis bahan bakar", "Sistem pendingin"], correct: 0 },
        { q: "Mekanisme katup tipe OHV menggunakan penggerak katup berupa push rod (batang penekan) karena...", options: ["Poros nok terletak di blok silinder bagian bawah", "Poros nok di atas", "Tanpa poros nok", "Menggunakan transmisi CVT", "Menggunakan oli ganda"], correct: 0 },
        { q: "Nok / Cam lobe pada poros nok berfungsi untuk...", options: ["Mendorong / menekan rocker arm atau katup agar membuka", "Menutup katup", "Memutar rantai kamrat", "Mengatur api busi", "Pompa oli"], correct: 0 },
        { q: "Penyetelan celah katup tipe Shim (Shim Under Bucket) dilakukan dengan cara...", options: [" mengganti ketebalan kepingan Shim dengan ketebalan yang sesuai", "Memutar baut setel dengan obeng", "Memotong batang katup", "Mengencangkan pegas", "Mengganti rocker arm"], correct: 0 },
        { q: "Komponen yang berfungsi menjaga ketegangan rantai mesin (timing chain) agar selalu stabil dinamakan...", options: ["Tensioner / Lifter Tensioner", "Rocker arm", "Camshaft", "Guide stopper", "Sprocket"], correct: 0 },
        { q: "Diameter daun katup masuk (Intake Valve) selalu dirancang LEBIH BESAR daripada katup buang karena...", options: ["Untuk memaksimalkan efisiensi pemasukan campuran udara-bahan bakar ke dalam silinder", "Agar tidak tertukar saat dipasang", "Bahan katup masuk lebih murah", "Tekanan hisap lebih kuat dari buang", "Agar katup buang tidak patah"], correct: 0 },
        { q: "Bila terjadi kebocoran pada skir katup buang, gejala yang dirasakan pada mesin adalah...", options: ["Kompresi rendah / lemas dan sesekali terjadi ledakan di knalpot (backfire)", "Mesin berputar cepat", "Asap knalpot biru", "Aki cepat tekor", "Oli mesin hitam"], correct: 0 },
        { q: "Bilah poros nok aus / tergerus akan mengakibatkan...", options: ["Tinggi angkat katup (Valve Lift) berkurang sehingga tenaga mesin drop", "Celah katup menjadi nol", "Mesin macet total", "Busi mati", "Pengapian terlambat"], correct: 0 },
        { q: "Tujuan ditempatkannya dua pegas katup (dalam dan luar) yang arah ulirnya berlawanan adalah...", options: ["Mencegah terjadinya getaran gelombang pegas (Valve Surge) pada RPM tinggi", "Agar lebih murah", "Agar katup keras ditahan", "Gaya hiasan", "Menghemat tempat"], correct: 0 },
        { q: "Besarnya celah katup standar motor bebek/sport harian umumnya berkisar antara...", options: ["0,03 mm - 0,10 mm", "0,50 mm - 1,00 mm", "1,0 mm - 2,0 mm", "0,001 mm", "0,25 cm"], correct: 0 },
        { q: "Tanda 'I' atau 'IN' pada sprocket poros nok saat posisi TMA harus...", options: ["Sejajar dengan permukaan atas kepala silinder atau tanda panah penyesuai", "Mengarahkan ke bawah", "Bebas", "Mengarahkan ke busi", "Mengarahkan ke knalpot"], correct: 0 },
        { q: "Komponen yang mentransfer penekanan dari nok langsung ke ujung batang katup dinamakan...", options: ["Pelatuk Katup (Rocker Arm)", "Push rod", "Valve lifter", "Valve retainer", "Cotter pin"], correct: 0 },
        { q: "Penggunaan Roller Rocker Arm (pelatuk ber-roller) bertujuan untuk...", options: ["Mengurangi gesekan antara nok dan pelatuk sehingga mesin lebih ringan dan irit", "Membuat suara kasar", "Menambah berat mesin", "Menghemat oli", "Memperbesar celah"], correct: 0 },
        { q: "Pengunci per katup agar tidak lepas dari batangnya dinamakan...", options: ["Valve Cotter / Kuku Macan", "Snap ring", "Pin dowel", "Lock nut", "Retainer cap"], correct: 0 },
        { q: "Dudukan katup (Valve Seat) dipasang pada kepala silinder dengan cara dipress dan terbuat dari bahan...", options: ["Besi tuang khusus / Besi paduan tahan panas dan gesekan", "Aluminium murni", "Kuningan soft", "Tembaga", "Plastik tebal"], correct: 0 },
        { q: "Apabila rantai kamrat mengendor terlalu parah, risiko paling berbahaya yang dapat terjadi adalah...", options: ["Rantai melompat gigi sprocket, waktu katup kacau, dan katup menabrak piston", "Bensin banjir", "Kipas mati", "Ban pecah", "Kiprok terbakar"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 4: Pengukuran Presisi I - Vernier, Micrometer & CBG - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[4] = [
        { q: "Tingkat ketelitian skala nonius Vernier Caliper (Jangka Sorong) 20 bagian skala nonius adalah...", options: ["0,05 mm", "0,02 mm", "0,01 mm", "0,1 mm", "0,001 mm"], correct: 0 },
        { q: "Alat ukur presisi yang paling tepat untuk mengukur diameter luar skirt piston adalah...", options: ["Mistar Baja", "Outside Micrometer", "Vernier Caliper", "Dial Gauge", "Feeler Gauge"], correct: 1 },
        { q: "Alat ukur yang digunakan bersama dengan Outside Micrometer untuk mengukur keausan dinding silinder adalah...", options: ["Cylinder Bore Gauge (CBG)", "Vernier Caliper", "Depth Gauge", "Feeler Gauge", "Small Hole Gauge"], correct: 0 },
        { q: "Skala Utama Vernier Caliper menunjuk angka 42 mm, dan skala nonius ke-7 lurus dengan skala utama (ketelitian 0,05 mm). Hasil pengukurannya adalah...", options: ["42,35 mm ($42 + 7 \\times 0,05 = 42,35$)", "42,70 mm", "42,07 mm", "49,00 mm", "42,50 mm"], correct: 0 },
        { q: "Fungsi dari Ratchet Thimble / Ratchet Stop pada Outside Micrometer adalah...", options: ["Memutar thimble dan memastikan tekanan pengukuran pada benda kerja konsisten/stabil", "Mengunci spindel", "Mengatur skala nol", "Memegang benda kerja", "Membersihkan spindel"], correct: 0 },
        { q: "Pengukuran diameter luar pin piston diperoleh hasil: Skala utama thimble = 14,5 mm, skala putar nonius = 18 (ketelitian 0,01 mm). Hasil totalnya adalah...", options: ["14,68 mm ($14,5 + 0,18 = 14,68$)", "14,18 mm", "14,518 mm", "14,80 mm", "15,00 mm"], correct: 0 },
        { q: "Sebelum Cylinder Bore Gauge (CBG) digunakan untuk mengukur silinder, alat tersebut harus disetel nol (zero reset) menggunakan...", options: ["Outside Micrometer yang telah disetel sesuai standar bore", "Vernier Caliper biasa", "Mistar gulung", "Feeler gauge", "Dial indicator"], correct: 0 },
        { q: "Komponen Vernier Caliper yang berfungsi mengukur kedalaman lubang atau celah adalah...", options: ["Depth Bar (Batang Pengukur Kedalaman)", "Jaw luar", "Jaw dalam", "Lock screw", "Main scale"], correct: 0 },
        { q: "Kalibrasi Outside Micrometer dilakukan menggunakan keping standar (Gauge Block/Standard Bar) bertujuan untuk...", options: ["Memastikan titik nol alat ukur tepat sebelum digunakan", "Mengencangkan baut", "Membersihkan oli", "Meluruskan spindel", "Memperbesar skala"], correct: 0 },
        { q: "Pengukuran kedalaman celah ring piston pada piston menggunakan...", options: ["Feeler Gauge bersumber bersama Vernier Caliper / Depth Micro", "Dial gauge saja", "Mistar baja", "Hydrometer", "Bore gauge"], correct: 0 },
        { q: "Pada pembacaan Micrometer $25-50\\text{ mm}$, jika timbel menunjukkan angka 0 di skala utama bawah dan angka 25 di timbel putar, maka hasil bacaan murninya adalah...", options: ["25,25 mm", "25,00 mm", "25,50 mm", "0,25 mm", "50,00 mm"], correct: 0 },
        { q: "Penggunaan pengetukan kasar atau penjatuhan alat ukur presisi Vernier Caliper akan mengakibatkan...", options: ["Kerusakan kepresisian sensor rahang (akibat deformation/benturan)", "Alat makin teliti", "Skala makin jelas", "Bisa digunakan untuk las", "Tidak berpengaruh"], correct: 0 },
        { q: "Skala terkecil nonius Vernier Caliper ketelitian 0,02 mm terdiri atas ... jumlah garis skala nonius.", options: ["50 garis", "20 garis", "10 garis", "100 garis", "5 garis"], correct: 0 },
        { q: "Pengukuran ketirusan silinder dilakukan dengan mengukur diameter silinder pada...", options: ["3 posisi kedalaman (Atas, Tengah, Bawah) di dalam silinder", "1 posisi saja", "Luar blok silinder", "Batas gasket", "Sisi mahkota piston"], correct: 0 },
        { q: "Jangkauan (range) Outside Micrometer umum dijual di pasaran dalam selang...", options: ["25 mm (misal 0-25 mm, 25-50 mm, 50-75 mm)", "10 mm", "100 mm", "50 mm", "5 mm"], correct: 0 },
        { q: "Pengunci (Lock Nut / Lock Lever) pada Micrometer berfungsi untuk...", options: ["Mengunci posisi poros geser (spindel) agar hasil pengukuran tidak bergeser saat dibaca", "Mengunci benda kerja", "Setel nol", "Memutar spindel cepat", "Menahan anvil"], correct: 0 },
        { q: "Anvil dan Spindle pada Outside Micrometer terbuat dari bahan karbida keras bertujuan untuk...", options: ["Tahan terhadap keausan akibat gesekan berulang", "Membuat alat menjadi ringan", "Mencegah karat listrik", "Menghantar panas", "Hiasan kilap"], correct: 0 },
        { q: "Bila pengukuran silinder menggunakan CBG menunjukkan jarum bergerak searah jarum jam sejauh 0,08 mm dari posisi zero nol micrometer 50,00 mm, artinya diameter silinder adalah...", options: ["49,92 mm ($50,00 - 0,08 = 49,92$)", "50,08 mm", "50,80 mm", "49,08 mm", "50,00 mm"], correct: 0 },
        { q: "Sebaliknya, bila jarum CBG bergerak berlawanan arah jarum jam sejauh 0,12 mm dari zero reset 50,00 mm, artinya diameter silinder adalah...", options: ["50,12 mm ($50,00 + 0,12 = 50,12$)", "49,88 mm", "50,21 mm", "49,12 mm", "51,20 mm"], correct: 0 },
        { q: "Pengukuran ketebalan kanvas rem cakram dapat menggunakan alat...", options: ["Vernier Caliper / Outside Micrometer", "CBG", "Hydrometer", "Dial indicator", "Feeler gauge"], correct: 0 },
        { q: "Zero adjustment (Setel Nol) pada Vernier Caliper dilakukan ketika...", options: ["Rahang rapat tertutup, garis nol skala utama dan nonius harus lurus tepat", "Rahang terbuka lebar", "Depth bar keluar 10 mm", "Baut dikencangkan penuh", "Skala dibersihkan alkohol"], correct: 0 },
        { q: "Pembersihan alat ukur presisi setelah dipakai wajib menggunakan...", options: ["Kain lap bersih/halus (Kain Majun/Microfiber) dan dioled oli tipis tahan karat", "Air sabun basah", "Bensin murni disikat kasar", "Amplas halus", "Minyak rem"], correct: 0 },
        { q: "Alat ukur yang paling cocok mengukur diameter luar batang katup adalah...", options: ["Outside Micrometer (0-25 mm)", "Vernier Caliper", "CBG", "Depth gauge", "Mistar gulung"], correct: 0 },
        { q: "Kesalahan paralaks (Parallax Error) saat membaca alat ukur terjadi karena...", options: ["Posisi mata pengamat tidak tegak lurus dengan garis skala pembacaan", "Alat ukur jatuh", "Suhu ruangan dingin", "Lampu terlalu terang", "Benda kerja kotor"], correct: 0 },
        { q: "Satuan pengukuran standar internasional (SI) yang digunakan pada alat ukur mekanik presisi di Indonesia adalah...", options: ["MiliMeter (mm)", "Inchi (inch)", "Sentimeter (cm)", "Meter (m)", "Mikron ($\\mu m$)"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 5: ULANGAN EVALUASI OTOMOTIF (Level 1 - 4) - 50 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[5] = [];
    for (let i = 1; i <= 50; i++) {
        const sourceL = ((i - 1) % 4) + 1;
        const sourceQIdx = Math.floor((i - 1) / 4);
        const refQ = window.MASTER_QUESTION_BANK.otomotif[sourceL][sourceQIdx] || window.MASTER_QUESTION_BANK.otomotif[1][0];
        window.MASTER_QUESTION_BANK.otomotif[5].push({
            q: `[EVALUASI LEVEL ${sourceL}] ${refQ.q}`,
            options: refQ.options,
            correct: refQ.correct
        });
    }

    // =========================================================================
    // LEVEL 6: PMMSM - Pelumasan & Pendinginan Mesin - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[6] = [
        { q: "Fungsi utama oli pelumas pada mesin sepeda motor adalah...", options: ["Mengurangi gesekan, mendinginkan, membersihkan, dan menyekat kompresi", "Menambah bensin", "Mempercepat pembakaran", "Menghasilkan pengapian", "Mencegah aki tekor"], correct: 0 },
        { q: "Kode SAE (Society of Automotive Engineers) pada kemasan oli menunjukkan...", options: ["Tingkat kekentalan (viskositas) oli pelumas", "Kualitas oli API", "Masa kadaluarsa", "Jenis mesin", "Volume oli"], correct: 0 },
        { q: "Kode SAE '10W-40' pada oli mesin menandakan bahwa oli tersebut bersifat...", options: ["Multigrade (memiliki tingkat kekentalan stabil pada suhu dingin W-Winter maupun panas)", "Monograde dingin", "Oli khusus 2-tak", "Oli gerdang", "Oli sintetis murni"], correct: 0 },
        { q: "Kode API Service 'S' (misal SJ, SL, SN) pada kemasan oli diperuntukkan untuk...", options: ["Mesin Bensin (Spark Ignition)", "Mesin Diesel", "Oli Samping", "Oli Gardan", "Minyak rem"], correct: 0 },
        { q: "Komponen yang memompa oli pelumas dari karter ke seluruh bagian mesin adalah...", options: ["Pompa Oli (Oil Pump)", "Filter oli", "Dipstick", "Kiprok", "Karburator"], correct: 0 },
        { q: "Pompa oli tipe Trochoid terdiri dari...", options: ["Rotor dalam (Inner rotor) dan Rotor luar (Outer rotor)", "Roda gigi lurus", "Plunger piston", "Baling-baling", "Diafragma"], correct: 0 },
        { q: "Fungsi dari saringan oli (Oil Filter) adalah...", options: ["Menyaring kotoran dan serbuk logam dari oli sebelum mengalir ke komponen mesin", "Mendinginkan oli", "Setel tekanan oli", "Memompa oli", "Menampung oli"], correct: 0 },
        { q: "Sistem pendinginan cair (Liquid Cooling) menggunakan media pendingin berupa...", options: ["Radiator Coolant (Campuran air bersih dan Ethylene Glycol)", "Air murni biasa", "Oli bekas", "Alkohol", "Freon"], correct: 0 },
        { q: "Komponen sistem pendingin cair yang berfungsi mengatur sirkulasi coolant berdasarkan suhu mesin adalah...", options: ["Thermostat", "Radiator", "Pompa air (Water pump)", "Tutup radiator", "Kipas radiator"], correct: 0 },
        { q: "Suhu kerja optimal mesin sepeda motor berpendingin cairan berkisar antara...", options: ["80°C - 90°C", "0°C - 50°C", "150°C - 200°C", "200°C - 300°C", "50°C - 60°C"], correct: 0 },
        { q: "Komponen yang berfungsi menjaga tekanan di dalam sistem pendingin dan menaikkan titik didih air adalah...", options: ["Tutup Radiator (Radiator Cap)", "Thermostat", "Reservoir tank", "Water jacket", "Selang bypass"], correct: 0 },
        { q: "Tutup radiator dilengkapi dua katup utama yaitu...", options: ["Katup Tekan (Pressure Valve) dan Katup Vakum (Vacuum Valve)", "Katup Masuk dan Buang", "Katup Solenoide dan Jarum", "Katup Kupu-kupu", "Katup Membran"], correct: 0 },
        { q: "Bila suhu mesin naik melebihi batas, katup tekan pada tutup radiator akan membuka dan mengalirkan kelebihan cairan ke...", options: ["Tangki Cadangan (Reservoir Tank)", "Luar mesin", "Karter oli", "Knalpot", "Ruang bakar"], correct: 0 },
        { q: "Bila mesin menjadi dingin dan cairan di radiator menyusut vacuum, maka katup vakum akan...", options: ["Membuka dan menyedot kembali cairan dari reservoir tank ke radiator", "Menutup rapat", "Membuang air keluar", "Mematikan kipas", "Mengunci salurang"], correct: 0 },
        { q: "Saluran tempat mengalirnya air pendingin di sekeliling silinder dan kepala silinder dinamakan...", options: ["Water Jacket (Mantel Air)", "Radiator core", "Bypass pipe", "Thermostat housing", "Reservoir"], correct: 0 },
        { q: "Pompa air (Water Pump) pada sepeda motor umumnya digerakkan oleh...", options: ["Putaran Poros Nok (Camshaft) atau Poros Engkol", "Motor listrik aki", "Rantai roda", "Tekanan knalpot", "Gaya gravitasi"], correct: 0 },
        { q: "Sistem pendinginan minyak (Oil Cooler) bekerja dengan cara...", options: ["Mendinginkan oli mesin lewat radiator kecil khusus oli di bagian depan", "Mencampur oli dengan air", "Menyemprot oli ke ban", "Mendinginkan bensin", "Menggunakan es"], correct: 0 },
        { q: "Penyebab terjadinya pembuihan (milky oil) warna putih susu pada oli mesin adalah...", options: ["Tercampurnya air pendingin (coolant) ke dalam oli mesin akibat seal pompa air/gasket bocor", "Bensin terlalu irit", "Oli terlalu tua", "Mesin dingin", "Filter oli kotor"], correct: 0 },
        { q: "Filter oli tipe centrifugal kotoran dibersihkan saat...", options: ["Servis berkala / bongkar bak kopling kanan", "Ganti busi", "Setel rantai", "Ganti ban", "Cuci motor"], correct: 0 },
        { q: "Bila thermostat macet pada posisi TERTUTUP terus, akibat yang terjadi adalah...", options: ["Mesin mengalami panas berlebih (Overheating) karena coolant tidak bisa mengalir ke radiator", "Mesin terlalu dingin", "Air radiator habis", "Kipas mati", "Oli membeku"], correct: 0 },
        { q: "Fungsi sirip pendingin radiator (Radiator Fins) adalah...", options: ["Memperluas area pelepasan panas dari pipa radiator ke udara yang melintas", "Menahan air", "Menyaring debu", "Dudukan kipas", "Mengatur tekanan"], correct: 0 },
        { q: "Campuran ethylene glycol pada coolant berfungsi untuk...", options: ["Menaikkan titik didih air dan mencegah korosi/karat serta pembekuan", "Membuat air harum", "Membuat air berwarna merah", "Melumasi piston", "Membersihkan busi"], correct: 0 },
        { q: "Pemeriksaan jumlah oli mesin secara manual dilakukan menggunakan...", options: ["Dipstick (Batang Pengukur Oli) pada kondisi motor berdiri tegak di standar tengah", "Feeler gauge", "Jangka sorong", "Kaca pembesar", "Gelas ukur"], correct: 0 },
        { q: "Sistem pelumasan tekan (Force Feed Lubrication) menggunakan...", options: ["Pompa oli untuk menekan oli ke seluruh komponen presisi", "Sistem percik saja", "Sistem campur bensin", "Gaya gravitasi murni", "Tekanan udara vacuum"], correct: 0 },
        { q: "Katup bypass pada filter oli berfungsi untuk...", options: ["Mengalirkan oli langsung tanpa disaring jika filter oli tersumbat total demi mencegah aus", "Membuang oli", "Setel tekanan", "Mematikan mesin", "Mengunci oli"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 7: PMMSM - Karburator & Sistem Injeksi (PGM-FI) - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[7] = [
        { q: "Fungsi utama karburator atau sistem injeksi pada sepeda motor adalah...", options: ["Mencampur bahan bakar dan udara dalam perbandingan yang tepat sesuai kebutuhan mesin", "Memompa oli", "Memercikkan bunga api", "Menyaring udara", "Menghasilkan listrik"], correct: 0 },
        { q: "Perbandingan campuran udara dan bahan bakar teoritis ideal (Stoichiometric AFR) untuk mesin bensin adalah...", options: ["14,7 : 1 (14,7 gram udara : 1 gram bensin)", "10 : 1", "1 : 14,7", "20 : 1", "12 : 1"], correct: 0 },
        { q: "Komponen karburator yang berfungsi mensuplay bahan bakar pada putaran stasioner (Idle/RPM rendah) adalah...", options: ["Pilot Jet (Slow Jet)", "Main Jet", "Needle Jet", "Jet Needle (Jarum Skep)", "Power Jet"], correct: 0 },
        { q: "Komponen karburator yang berfungsi mensuplay bahan bakar pada putaran menengah hingga tinggi adalah...", options: ["Main Jet", "Pilot Jet", "Choke", "Air Screw", "Float"], correct: 0 },
        { q: "Fungsi dari sistem Choke pada karburator adalah...", options: ["Memperkaya campuran bahan bakar (AFR kaya) untuk mempermudah start saat mesin dingin", "Mengeritkan bensin", "Menambah udara", "Mematikan mesin", "Setel stasioner"], correct: 0 },
        { q: "Komponen karburator yang mengatur tinggi rendahnya permukaan bahan bakar di dalam ruang pelampung adalah...", options: ["Pelampung (Float) dan Jarum Pelampung (Needle Valve)", "Main jet", "Skep", "Air screw", "Choke valve"], correct: 0 },
        { q: "Prinsip kerja karburator didasarkan pada Hukum Fisika yaitu...", options: ["Asas / Efek Venturi (Hukum Bernoulli)", "Hukum Pascal", "Hukum Archimedes", "Hukum Ohm", "Hukum Hooke"], correct: 0 },
        { q: "Pada sistem Injeksi (PGM-FI), komponen yang menyemprotkan bahan bakar berbentuk kabut halus ke saluran hisap adalah...", options: ["Injektor (Injector)", "Fuel Pump", "ECM / ECU", "Throttle Body", "Pressure regulator"], correct: 0 },
        { q: "Komponen yang mengontrol seluruh kerja sistem injeksi berdasarkan sinyal dari sensor-sensor adalah...", options: ["ECU / ECM (Engine Control Unit/Module)", "Injektor", "Kiprok", "Spul", "Busi"], correct: 0 },
        { q: "Sensor yang berfungsi mendeteksi suhu oli atau cairan pendingin mesin pada sistem injeksi adalah...", options: ["EOT (Engine Oil Temp) / ECT (Engine Coolant Temp)", "IAT Sensor", "MAP Sensor", "TP Sensor", "CKP Sensor"], correct: 0 },
        { q: "Sensor yang berfungsi mendeteksi bukaan sudut katup gas pada Throttle Body dinamakan...", options: ["TP (Throttle Position) Sensor", "MAP Sensor", "IAT Sensor", "O2 Sensor", "CKP Sensor"], correct: 0 },
        { q: "Sensor yang berfungsi mendeteksi posisi dan kecepatan putaran poros engkol (RPM) adalah...", options: ["CKP (Crankshaft Position) Sensor", "TP Sensor", "MAP Sensor", "EOT Sensor", "Bank Angle Sensor"], correct: 0 },
        { q: "Sensor yang mematikan sistem injeksi/mesin secara otomatis saat sepeda motor miring melebihi sudut aman (jatuh) adalah...", options: ["BAS (Bank Angle Sensor) / Lean Angle Sensor", "CKP Sensor", "O2 Sensor", "TP Sensor", "MAP Sensor"], correct: 0 },
        { q: "Pompa bahan bakar (Fuel Pump) sepeda motor FI terpasang di dalam tangki dan berfungsi menghasilkan tekanan bensin sebesar...", options: ["294 kPa (sekitar 2,94 bar / 42 psi)", "10 kPa", "1000 kPa", "50 kPa", "10 bar"], correct: 0 },
        { q: "Sensor O2 (Oxygen Sensor) yang terpasang pada saluran buang (knalpot) berfungsi untuk...", options: ["Mendeteksi sisa kadar oksigen gas buang untuk mengoreksi campuran bahan bakar oleh ECU", "Mengukur suhu knalpot", "Menyaring jelaga", "Meredam suara", "Mencegah kobaran api"], correct: 0 },
        { q: "Sistem injeksi Loop Tertutup (Closed Loop) menggunakan umpan balik dari sensor...", options: ["O2 Sensor", "IAT Sensor", "TP Sensor", "EOT Sensor", "Starter switch"], correct: 0 },
        { q: "Tekanan bahan bakar yang terlalu rendah pada motor injeksi akan mengakibatkan...", options: ["Semprotan injektor tidak mengabut sempurna, mesin brebet / hilang tenaga", "Bensin banjir", "Mesin terlalu panas", "Busi meleleh", "Kiprok panas"], correct: 0 },
        { q: "Lampu MIL (Malfunction Indicator Lamp) pada panel spedometer akan berkedip jika...", options: ["Terjadi kegagalan atau kerusakan pada salah satu sensor/artuator sistem injeksi", "Bensin habis", "Oli habis", "Aki habis", "Lampu sein mati"], correct: 0 },
        { q: "Kedipan MIL 7 kali pendek pada motor Honda PGM-FI menandakan adanya masalah pada...", options: ["Sensor EOT / ECT", "Sensor TP", "Sensor MAP", "Injektor", "Sensor IAT"], correct: 0 },
        { q: "Kedipan MIL 8 kali pendek pada motor PGM-FI menandakan masalah pada...", options: ["Sensor TP (Throttle Position)", "Sensor EOT", "Sensor IAT", "Injektor", "Fuel Pump"], correct: 0 },
        { q: "Kedipan MIL 12 kali pendek pada motor PGM-FI menandakan masalah pada...", options: ["Injektor (Injector Circuit)", "Sensor CKP", "ECM", "Sensor O2", "Sensor TP"], correct: 0 },
        { q: "Alat diagnostik khusus yang dihubungkan ke DLC (Data Link Connector) untuk membaca data FI dinamakan...", options: ["Diagnostic Scanner Tool (Hi-Scan / Diagnostic Tool)", "Multimeter", "Hydrometer", "Feeler gauge", "Tachometer"], correct: 0 },
        { q: "Proses Reset ECM / ECU bertujuan untuk...", options: ["Menghapus memori kode kerusakan (DTC) setelah perbaikan sensor selesai", "Membuat bensin irit 100%", "Menaikkan kompresi", "Mengganti program mesin", "Menyetel rantai"], correct: 0 },
        { q: "Bila karburator 'Banjir' (bensin meluap dari selang pernapasan), penyebab utamanya adalah...", options: ["Jarum pelumpung aus atau terganjal kotoran sehingga tidak menutup rapat", "Main jet tersumbat", "Pilot jet terlalu besar", "Setelan stasioner terlalu tinggi", "Choke terbuka"], correct: 0 },
        { q: "Pembersihan elemen saringan udara tipe kertas berlapis oli (Viscous Paper Element) dilakukan dengan...", options: ["TIDAK BOLEH dicuci/disemprot angin kencang, harus diganti berkala", "Dicuci bensin", "Dicuci sabun", "Disemprot kompresor kencang", "Diamplas"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 8: Pemeliharaan Sasis - Rem, Suspensi, Kemudi, Roda & Ban - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[8] = [
        { q: "Komponen sistem rem hidrolik yang mengubah gaya tekan tuas rem menjadi tekanan cairan fluida adalah...", options: ["Master Silinder (Master Cylinder)", "Caliper", "Brakepad", "Piringan cakram", "Slang rem"], correct: 0 },
        { q: "Komponen rem cakram yang mendorong pad rem menekan piringan cakram saat menerima tekanan fluida adalah...", options: ["Piston Caliper (Kaliper)", "Master piston", "Brake lever", "Disc rotor", "Reservoir"], correct: 0 },
        { q: "Proses pembuangan udara palsu (gelembung udara) pada sistem rem hidrolik dinamakan...", options: ["Bleeding Rem", "Skir rem", "Tune-up rem", "Spooring", "Balancing"], correct: 0 },
        { q: "Cairan rem (Brake Fluid) yang umum digunakan pada sepeda motor harian menggunakan standar...", options: ["DOT 3 atau DOT 4", "SAE 10W-40", "API SJ", "DOT 5 murni", "ISO 9001"], correct: 0 },
        { q: "Penyebab tuas rem hidrolik terasa membal / dalam saat ditekan adalah...", options: ["Adanya gelembung udara terperangkap di dalam saluran hidrolik", "Minyak rem baru", "Pad rem baru", "Piringan tebal", "Seal kaliper baru"], correct: 0 },
        { q: "Sistem rem ABS (Anti-lock Braking System) berfungsi untuk...", options: ["Mencegah roda terkunci saat pengereman mendadak sehingga kendaraan tetap bisa dikendalikan", "Mempercepat pengereman", "Menghemat minyak rem", "Membuat rem empuk", "Mencegah pad rem aus"], correct: 0 },
        { q: "Sistem Kombi Rem (CBS - Combi Brake System) pada motor matic berfungsi untuk...", options: ["Mendistribusikan gaya pengereman ke roda depan dan belakang secara bersamaan saat tuas rem kiri ditarik", "Mengunci roda belakang", "Mengabaikan rem depan", "Menaikkan kecepatan", "Sistem ABS otomatis"], correct: 0 },
        { q: "Penyebab pengereman rem tromol terasa tidak pakem atau meluncur meskipun tuas ditarik kuat adalah...", options: ["Kanvas rem aus / licin terkena oli atau tromol tergerus", "Kabel rem baru", "Tromol bersih", "Jarak bebas tuas tepat", "Pegas pengembali kuat"], correct: 0 },
        { q: "Suspensi depan tipe Teleskopik menggunakan komponen penyeram kejutan berupa...", options: ["Minyak Suspensi (Fork Oil) dan Pegas Spiral (Fork Spring)", "Gas nitrogen murni", "Karet padat", "Per daun", "Batang torsi"], correct: 0 },
        { q: "Bila penutup seal oli suspensi depan bocor, akibat yang terjadi adalah...", options: ["Oli shock keluar merembes dan suspensi terasa terlalu empuk / mengocok (bottoming)", "Suspensi menjadi keras", "Kemudi berat", "Ban bocor", "Rem pakem"], correct: 0 },
        { q: "Suspensi tipe USD (Up-Side Down) memiliki keunggulan dibanding teleskopik biasa yaitu...", options: ["Rigiditas / kekakuan lebih tinggi dan handling lebih stabil pada kecepatan tinggi", "Harga lebih murah", "Oli tidak bisa bocor", "Bentuk lebih kecil", "Lebih empuk untuk beban berat"], correct: 0 },
        { q: "Pemeriksaan keolengan piringan cakram (Disc Run-out) menggunakan alat ukur presisi...", options: ["Dial Indicator (Dial Gauge) dan V-Block", "Mistar baja", "Jangka sorong", "Feeler gauge", "Micrometer"], correct: 0 },
        { q: "Batas maksimum keolengan (run-out) piringan cakram rem sepeda motor umumnya tidak boleh melebihi...", options: ["0,10 mm - 0,30 mm", "1,00 mm", "5,00 mm", "0,001 mm", "1,0 cm"], correct: 0 },
        { q: "Komponen sistem kemudi yang menampung bantalan pelor (steel ball/bearing) pada poros kemudi adalah...", options: ["Steering Cone (Steering Stem Bearing)", "Shockbreaker", "Segitiga atas", "Stang stir", "As roda"], correct: 0 },
        { q: "Penyebab stang kemudi terasa berat diputar atau terasa 'terkunci' di posisi lurus adalah...", options: ["Steering cone aus / tergerus atau penyetelan mur pengunci terlalu kencang", "Ban terlalu kencang", "Minyak rem penuh", "Shockbreaker baru", "Rantai kencang"], correct: 0 },
        { q: "Kode ban sepeda motor '110/80 - 17 57P'. Angka '110' menyatakan...", options: ["Lebar telapak ban dalam satuan milimeter (mm)", "Tinggi ban", "Diameter velg", "Indeks beban", "Simbol kecepatan"], correct: 0 },
        { q: "Angka '80' pada kode ban '110/80 - 17' menyatakan Aspect Ratio yaitu...", options: ["Tinggi profil ban sebesar 80% dari lebar telapak ban (110 mm)", "Tinggi ban 80 mm", "Lebar ban 80 mm", "Diameter velg 80 inchi", "Sudut kemiringan"], correct: 0 },
        { q: "Angka '17' pada kode ban '110/80 - 17' menyatakan...", options: ["Diameter lingkaran velg dalam satuan inchi", "Lebar velg", "Tinggi ban", "Jumlah kawat ban", "Usaha ban"], correct: 0 },
        { q: "Tipe ban 'Tubeless' adalah ban yang...", options: ["Tidak menggunakan ban dalam (Inner tube) karena lapisan dalam ban kedap udara", "Menggunakan ban dalam tebal", "Tidak bisa bocor", "Bisa jalan tanpa udara", "Khusus velg jari-jari"], correct: 0 },
        { q: "Tanda TWI (Tread Wear Indicator) berbentuk segitiga kecil pada dinding pinggir ban berfungsi sebagai...", options: ["Batas indikator keausan ketebalan telapak ban yang aman digunakan", "Tanda rotasi putaran ban", "Tanda tekanan angin", "Tanda velg", "Tanda tempat tubeless"], correct: 0 },
        { q: "Tekanan angin ban yang TERLALU RENDAH akan menyebabkan...", options: ["Ban aus di kedua sisi pinggir telapak, kemudi berat, dan konsumsi bensin boros", "Ban aus di tengah saja", "Motor meluncur kencang", "Velg menjadi kencang", "Ban awet"], correct: 0 },
        { q: "Tekanan angin ban yang TERLALU TINGGI akan menyebabkan...", options: ["Ban aus di bagian tengah telapak dan susfensi terasa sangat keras / membanting", "Ban aus di pinggir", "Ban empuk", "Cengkeraman basah maksimal", "Kemudi berat"], correct: 0 },
        { q: "Pemeriksaan dan penyetelan ketegangan rantai roda (Drive Chain) dilakukan pada posisi...", options: ["Standar tengah di tempat datar, celah lendut rantai berkisar 15 - 25 mm", "Standar samping", "Sambil dinaiki 2 orang", "Rantai ditarik kencang tanpa celah", "Motor berjalan"], correct: 0 },
        { q: "Bantalan roda (Wheel Bearing) yang aus/oblak akan mengakibatkan...", options: ["Roda bergoyang / tidak stabil saat jalan dan menimbulkan suara dengung", "Ban makin awet", "Rem makin pakem", "Shockbreaker keras", "Bensin irit"], correct: 0 },
        { q: "Penyetelan jari-jari roda (Spoke Wheel) dilakukan agar velg tidak oleng menggunakan kunci khusus dinamakan...", options: ["Spoke Wrench (Kunci Jari-jari)", "Kunci pas 10", "Kunci ring 12", "Tang kombinasi", "Kunci inggris"], correct: 0 }
    ];

    // ==========================================
    // LEVEL 9: Pemeliharaan Kelistrikan - Pengapian, Pengisian, Starter & Penerangan - 25 Soal
    // ==========================================
    window.MASTER_QUESTION_BANK.otomotif[9] = [
        { q: "Fungsi utama sistem pengapian (Ignition System) pada sepeda motor adalah...", options: ["Menghasilkan percikan bunga api listrik pada busi untuk membakar campuran bensin di ruang bakar", "Mengecas baterai", "Nyalakan lampu", "Putar mesin", "Bunyikan klakson"], correct: 0 },
        { q: "Komponen sistem pengapian yang menaikkan tegangan baterai 12V menjadi tegangan tinggi 15.000V - 25.000V adalah...", options: ["Koil Pengapian (Ignition Coil)", "CDI / ECU", "Busi", "Spul", "Kiprok"], correct: 0 },
        { q: "Komponen yang berfungsi memercikkan bunga api listrik di dalam ruang bakar adalah...", options: ["Busi (Spark Plug)", "Koil", "CDI", "Kiprok", "Spul"], correct: 0 },
        { q: "Pada sistem pengapian CDI (Capacitor Discharge Ignition), energi listrik disimpan sementara di dalam...", options: ["Kapasitor (Capacitor)", "Transistor", "Resistor", "Diode", "Transformator"], correct: 0 },
        { q: "Komponen yang memberi sinyal pulsa listrik ke CDI/ECU untuk memicu saat pengapian (Timing) adalah...", options: ["Pulser (Pick-Up Coil / CKP Sensor)", "Spul pengisian", "Aki", "Kiprok", "Kunci kontak"], correct: 0 },
        { q: "Warna percikan bunga api busi yang BAIK dan kuat menunjukkan pengapian sempurna adalah berwarna...", options: ["Biru keunguan", "Merah kusam", "Kuning redup", "Hijau", "Putih pucat"], correct: 0 },
        { q: "Penyebab busi cepat hitam dan basah oleh kerak karbon (Carbon Fouling) adalah...", options: ["Campuran bahan bakar terlalu kaya (terlalu banyak bensin) atau oli masuk ruang bakar", "Campuran terlalu irit", "Busi terlalu panas", "Aki tekor", "Kiprok rusak"], correct: 0 },
        { q: "Pemeriksaan celah busi (Spark plug gap) standar motor harian menggunakan Feeler Gauge berkisar antara...", options: ["0,80 mm - 0,90 mm", "0,10 mm - 0,20 mm", "2,00 mm - 3,00 mm", "0,01 mm", "1,0 cm"], correct: 0 },
        { q: "Fungsi utama Sistem Pengisian (Charging System) adalah...", options: ["Menghasilkan arus listrik untuk mengisi ulang baterai dan mensuplai beban kelistrikan saat mesin hidup", "Memutar motor starter", "Menyalakan busi saja", "Mendinginkan air", "Memompa oli"], correct: 0 },
        { q: "Komponen sistem pengisian yang mengubah arus AC dari alternator/spul menjadi arus DC adalah...", options: ["Kiprok / Rectifier Regulator", "Koil", "CDI", "Relay", "Fuse"], correct: 0 },
        { q: "Selain sebagai penyearah arus, fungsi Kiprok (Regulator) adalah...", options: ["Membatasi/memfiksasi tegangan pengisian agar tidak melebihi 14,5 Volt (mencegah overcharge)", "Menaikkan arus", "Menyimpan listrik", "Mematikan mesin", "Setel lampu"], correct: 0 },
        { q: "Bila kiprok rusak dan gagal membatasi tegangan (overcharging > 15V), akibat yang timbul adalah...", options: ["Baterai panas/kembung, air aki cepat habis, dan bohlam lampu mudah putus", "Aki makin awet", "Lampu redup", "Motor makin kencang", "Mesin dingin"], correct: 0 },
        { q: "Bila spul pengisian (Stator Coil) terbakar/putus, akibat yang timbul adalah...", options: ["Baterai tidak terisi (tekor/soak) dan kelistrikan mati saat aki habis", "Lampu makin terang", "Aki kembung", "Kiprok terbakar", "Busi meledak"], correct: 0 },
        { q: "Komponen yang memutar poros engkol pertama kali secara elektrik saat tombol starter ditekan adalah...", options: ["Motor Starter (Starter Motor)", "Kiprok", "Spul", "Koil", "Alternator"], correct: 0 },
        { q: "Komponen Sakelar Magnetik (Relay Starter / Solenoide) berfungsi untuk...", options: ["Menghubungkan arus listrik besar langsung dari baterai ke motor starter dengan arus sakelar kecil", "Mengarahkan pengapian", "Mengecas aki", "Mengatur klakson", "Setel rem"], correct: 0 },
        { q: "Bila tuas rem ditarik dan tombol starter ditekan hanya terdengar suara 'Klek-Klek' dari relay tetapi motor starter tidak berputar, penyebabnya adalah...", options: ["Tegangan baterai tekor/drop atau sikat arang (carbon brush) motor starter habis", "Kiprok terbakar", "Busi mati", "Bensin habis", "Sekering putus"], correct: 0 },
        { q: "Fungsi Fuse (Sekering) pada sistem kelistrikan sepeda motor adalah...", options: ["Pengaman rangkaian dari bahaya korsleting / arus pendek berlebih", "Penyimpan arus", "Peningkat tegangan", "Penyearah arus", "Sakelar otomatis"], correct: 0 },
        { q: "Kapasitas baterai ditulis '12V 5Ah'. Angka '5Ah' (Ampere-Hour) menunjukkan...", options: ["Kapasitas daya simpan muatan arus listrik baterai", "Tegangan maksimum", "Arus starter", "Panjang baterai", "Berat baterai"], correct: 0 },
        { q: "Sakelar Kunci Kontak (Main Switch) berfungsi untuk...", options: ["Memutus dan menghubungkan arus listrik utama dari baterai ke seluruh rangkaian", "Setel pengapian", "Mengecas aki", "Nyalakan sein", "Memutar dinamo"], correct: 0 },
        { q: "Sistem penerangan lampu utama tipe AC (Alternating Current) mengambil sumber listrik langsung dari...", options: ["Spul Generator / Alternator (mengikuti putaran mesin)", "Baterai / Aki murni", "Kiprok DC", "Koil", "CDI"], correct: 0 },
        { q: "Sistem penerangan lampu utama tipe DC mengambil sumber listrik dari...", options: ["Baterai / Aki (kunci kontak ON lampu langsung nyala terang stabil)", "Spul murni", "Koil pengapian", "Busi", "Pulser"], correct: 0 },
        { q: "Fungsi Flasher (Flasher Relay) pada rangkaian lampu tanda belok (Sein) adalah...", options: ["Membuat lampu sein berkedip secara periodik (sekitar 60-120 kedipan per menit)", "Menerangkan lampu sein", "Mematikan lampu", "Membunyikan klakson", "Pengaman listrik"], correct: 0 },
        { q: "Bila lampu sein menyala terus tanpa berkedip saat sakelar di-ON-kan, penyebab utamanya adalah...", options: ["Flasher sein rusak atau daya beban bohlam lampu terlalu kecil/putus sebelah", "Aki soak", "Kiprok mati", "Spul putus", "Sakelar aus"], correct: 0 },
        { q: "Lampu rem (Brake Light) memiliki dua filamen kawat, yaitu...", options: ["Filamen Lampu Kota/Senja (daya kecil) dan Filamen Lampu Rem (daya lebih besar)", "Lampu jauh dan dekat", "Lampu sein kiri dan kanan", "Lampu hazard", "Lampu DC"], correct: 0 },
        { q: "Pemeriksaan kontinyuitas / keutuhan kabel dan sakelar menggunakan alat ukur Multimeter pada posisi...", options: ["Ohm Meter ($\\Omega$) atau Continuity Buzzer", "Volt Meter DC", "Volt Meter AC", "Ampere Meter", "Watt Meter"], correct: 0 }
    ];

    // =========================================================================
    // LEVEL 10: Pengukuran Presisi II - Dial Gauge, Feeler, Hydrometer & Scanner - 25 Soal
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[10] = [
        { q: "Alat ukur presisi yang digunakan untuk mengukur keolengan (Run-Out) poros engkol atau piringan cakram adalah...", options: ["Dial Indicator (Dial Gauge)", "Feeler Gauge", "Micrometer", "Hydrometer", "Vernier Caliper"], correct: 0 },
        { q: "Nilai ketelitian satu garis skala nonius pada Dial Indicator standar adalah...", options: ["0,01 mm", "0,1 mm", "0,05 mm", "0,001 mm", "0,5 mm"], correct: 0 },
        { q: "Dial Indicator wajib dipasang pada dudukan magnetik tegar yang dinamakan...", options: ["Magnetic Stand", "V-Block", "Surface plate", "Micrometer stand", "C-Clamp"], correct: 0 },
        { q: "Saat mengukur keolengan poros engkol, kedua ujung poros engkol ditopang di atas alat yang dinamakan...", options: ["V-Block", "Dial Stand", "Mistar baja", "Catok meja", "Plat penyangga"], correct: 0 },
        { q: "Alat ukur berupa lembaran-lembaran bilah baja tipis presisi dengan berbagai ukuran ketebalan dinamakan...", options: ["Feeler Gauge (Bilah Ukur / Thickness Gauge)", "Dial gauge", "Depth gauge", "Pitch gauge", "Wire gauge"], correct: 0 },
        { q: "Feeler Gauge digunakan pada pemeliharaan sepeda motor untuk mengukur...", options: ["Celah katup, celah samping ring piston, celah busi, dan celah rotor pompa oli", "Diameter piston", "Panjang rantai", "Tegangan aki", "Diameter silinder"], correct: 0 },
        { q: "Alat ukur yang digunakan untuk mengukur Berat Jenis (BJ) cairan elektrolit baterai basah adalah...", options: ["Hydrometer", "Hygrometer", "Multimeter", "Tachometer", "Barometer"], correct: 0 },
        { q: "Nilai Berat Jenis (BJ) elektrolit baterai basah kondisi terisi penuh (fully charged) pada suhu $20^\\circ\\text{C}$ adalah...", options: ["1,260 - 1,280", "1,000 - 1,100", "1,500 - 2,000", "0,800 - 0,900", "12,6 Volt"], correct: 0 },
        { q: "Bila pembacaan Hydrometer menunjukkan BJ elektrolit baterai di bawah 1,210, tindakan yang harus dilakukan adalah...", options: ["Lakukan pengisian ulang (recharge / stroom aki)", "Ganti aki baru langsung", "Buang air aki", "Tambah air zuur pekat", "Biarkan saja"], correct: 0 },
        { q: "Pelampung di dalam kaca Hydrometer akan bertambah terapung naik tinggi jika cairan elektrolit baterai...", options: ["Makin pekat / berat jenisnya tinggi (aki penuh)", "Makin encer / tekor", "Tercampur air murni", "Panas", "Kosong"], correct: 0 },
        { q: "Alat diagnostik elektronik (Diagnostic Scanner OBD-II / Hi-Scan) dihubungkan ke sepeda motor injeksi melalui soket...", options: ["DLC (Data Link Connector)", "Soket ECM", "Soket kiprok", "Soket aki", "Soket busi"], correct: 0 },
        { q: "Fungsi utama alat Diagnostic Scanner pada sepeda motor PGM-FI / Injeksi adalah...", options: ["Membaca kode kerusakan DTC, membaca live data sensor, dan melakukan reset memori ECM", "Menaikkan cc mesin", "Mengecas aki", "Setel celah busi", "Mengubah warna spedometer"], correct: 0 },
        { q: "Istilah 'DTC' pada sistem diagnostik injeksi merupakan singkatan dari...", options: ["Diagnostic Trouble Code (Kode Kerusakan Diagnostik)", "Direct Torque Control", "Dual Throttle Chamber", "Data Transmission Cable", "Digital Timing Control"], correct: 0 },
        { q: "Fitur 'Clear DTC' / 'Erase Code' pada alat scanner berfungsi untuk...", options: ["Menghapus riwayat memori kode kerusakan dari ECM setelah komponen sensor diperbaiki", "Mereset mesin baru", "Menghapus program ECM", "Mematikan lampu depan", "Mereset spedometer"], correct: 0 },
        { q: "Fitur 'Live Data Stream' pada scanner menampilkan...", options: ["Kondisi kerja sensor-sensor secara real-time saat mesin berputar (suhu, RPM, bukaan TP, dll)", "Harga sparepart", "Kode warna kabel", "Biaya servis", "Jadwal ganti oli"], correct: 0 },
        { q: "Alat ukur yang digunakan untuk mengukur tekanan kompresi ruang bakar silinder dinamakan...", options: ["Compression Tester", "Vacuum gauge", "Tire pressure gauge", "Hydrometer", "Multimeter"], correct: 0 },
        { q: "Saat melakukan tes tekanan kompresi dengan Compression Tester, langkah wajib yang dilakukan adalah...", options: ["Buka katup gas (Throttle) penuh dan putar starter/engkol beberapa kali hingga jarum stabil", "Tutup katup gas rapat", "Matikan kunci kontak saja", "Buka busi sebelah saja", "Isi bensin penuh"], correct: 0 },
        { q: "Tekanan kompresi standar mesin sepeda motor harian berkisar antara...", options: ["10 - 12 kg/cm² (atau 140 - 170 psi)", "1 - 2 kg/cm²", "50 - 60 kg/cm²", "100 bar", "2 psi"], correct: 0 },
        { q: "Alat ukur yang digunakan untuk mengukur kecepatan putaran mesin (RPM - Revolutions Per Minute) dinamakan...", options: ["Tachometer", "Spedometer", "Odometer", "Altimeter", "Voltmeter"], correct: 0 },
        { q: "Alat ukur yang digunakan untuk mengukur tekanan pompa bahan bakar (Fuel Pressure Gauge) dipasang pada...", options: ["Antara selang output fuel pump dan injektor", "Di dalam tangki bensin", "Di lubang busi", "Di knalpot", "Di karburator"], correct: 0 },
        { q: "Alat ukur presisi untuk mengukur celah samping (side clearance) ring piston pada alurnya adalah...", options: ["Feeler Gauge", "Dial indicator", "Micrometer", "Vernier caliper", "CBG"], correct: 0 },
        { q: "Pengukuran keolengan poros engkol dengan Dial Gauge dibaca dari...", options: ["Selisih simpangan pergerakan jarum maksimum dan minimum (Total Indicator Reading / TIR)", "Angka jarum awal saja", "Angka jarum akhir saja", "Jumlah putaran jarum", "Panjang poros"], correct: 0 },
        { q: "Bila air aki berada di bawah garis 'LOWER LEVEL' pada tempat baterai basah, cairan yang ditambahkan adalah...", options: ["Air Suling / Air Murni (Air Aki Tutup Biru)", "Air Zuur keras (Tutup Merah)", "Air keran biasa", "Coolant radiator", "Minyak rem"], correct: 0 },
        { q: "Alat ukur yang digunakan untuk memeriksa tegangan drop aki saat dilakukan cranking starter adalah...", options: ["Voltmeter DC (pada Multimeter) / Battery Tester", "Amperemeter AC", "Hydrometer", "Tachometer", "Scanner OBD"], correct: 0 },
        { q: "Tegangan baterai saat dilakukan cranking starter tidak boleh drop di bawah...", options: ["9,6 Volt (jika di bawah 9,6V baterai dalam kondisi tekor/soak)", "12,0 Volt", "14,0 Volt", "5,0 Volt", "0 Volt"], correct: 0 }
    ];

}
