// Bank Soal Otomotif Sepeda Motor (Level 11 - 15) - Materi Sertifikasi Servis & Diagnostik
// Pola Kunci Jawaban Berulang: C, A, D, E, B

if (window.MASTER_QUESTION_BANK) {

    if (!window.MASTER_QUESTION_BANK.otomotif) {
        window.MASTER_QUESTION_BANK.otomotif = {};
    }

    // =========================================================================
    // LEVEL 11: Perawatan Karburator, Renggang Klep, Kabel Gas & Filter Udara (25 Soal)
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[11] = [
        { q: "Berdasarkan SOP K3 pada prosedur servis karburator, alat perlindungan diri (APD) utama yang wajib digunakan mekanik sebelum memulai pekerjaan adalah...", options: ["Helm proyek dan rompi fosfor", "Sarung tangan kain tebal dan masker kain", "Wearpack, sepatu keselamatan (safety shoes), dan kaca mata kerja", "Kaca mata hitam dan sarung kulit", "Apron plastik dan sepatu boots tinggi"], correct: 2 },
        { q: "Saat melakukan pembongkaran karburator, komponen yang dibongkar dari mangkuk karburator untuk dibersihkan jalurnya adalah...", options: ["Main jet, pilot jet, pelampung, dan jarum pelampung", "Choke kabel dan jarum skep", "Sprocket dan rantai kamrat", "Skip gas dan per skep", "Intake manifold dan paking"], correct: 0 },
        { q: "Pemeriksaan fisik pada jarum pelampung (needle valve) karburator bertujuan untuk memastikan bahwa...", options: ["Warna jarum hitam", "Jarum terbuat dari kuningan murni", "Jarum mudah berkarat", "Kondisi ujung jarum tidak aus/terkikis agar bensin tidak banjir", "Panjang jarum bertambah 2 mm"], correct: 3 },
        { q: "Cairan pembersih yang digunakan untuk membersihkan saluran-saluran kecil (passage) karburator dari kerak dan endapan adalah...", options: ["Air sabun hangat", "Oli mesin bekas", "Minyak tanah", "Cairan rem DOT 4", "Carb cleaner / carburetor spray bertekanan"], correct: 4 },
        { q: "Pada pemeriksaan skep (piston valve / throttle valve) karburator, kondisi yang harus dipastikan agar skep tidak macet saat digas adalah...", options: ["Permukaan skep dilapisi oli kental", "Permukaan skep mulus dan tidak terdapat goresan/baret", "Permukaan skep diamplas kasar", "Diameter skep membesar 1 mm", "Skep berwarna kuning emas"], correct: 1 },
        { q: "Penyetelan putaran stasioner (idle RPM) standar pada mesin sepeda motor setelah servis karburator berada pada kisaran...", options: ["800 - 1000 RPM", "2000 - 2500 RPM", "1400 - 1600 RPM", "3000 - 3500 RPM", "500 - 800 RPM"], correct: 2 },
        { q: "Pada pekerjaan pemeriksaan celah katup (klep) sesuai buku pedoman reparasi, posisi piston harus tepat berada pada...", options: ["TMA langkah kompresi (kedua katup bebas)", "TMB langkah hisap", "TMA langkah buang", "TMB langkah usaha", "Bebas pada posisi mana saja"], correct: 0 },
        { q: "Jarak main bebas (free play) pada tuas kabel gas (throttle gas) yang standar bertujuan untuk...", options: ["Mencegah kabel gas putus", "Menghemat penggunaan bahan bakar", "Mempercepat akselerasi putaran bawah", "Memberikan celah aman agar stang saat dibelokkan tidak menarik gas sendiri", "Membuat putaran gas menjadi berat"], correct: 3 },
        { q: "Pada pemeriksaan elemen filter udara tipe Viscous Paper (kertas berlapis oli), prosedur pembersihan yang BENAR sesuai BPR adalah...", options: ["Dicuci menggunakan bensin murni", "Disemprot angin kompresor bertekanan tinggi dari dalam", "Dicuci dengan deterjen lalu dijemur", "Sikat menggunakan sikat kawat", "TIDAK Boleh dicuci atau disemprot kompresor, wajib diganti berkala"], correct: 4 },
        { q: "Jika karet seal/paking pada mangkuk karburator dalam kondisi gepeng, getas, atau sobek, tindakan yang harus dilakukan adalah...", options: ["Diolesi lem besi", "Diganti dengan karet seal/paking baru", "Dibiarkan saja asal baut kencang", "Dilapisi isolasi kertas", "Diikat dengan tali rafia"], correct: 1 },
        { q: "Pemeriksaan fungsi akhir (final test) setelah merakit karburator dan menghidupkan mesin meliputi...", options: ["Suara knalpot menjadi lebih keras", "Asap knalpot berwarna hitam pekat", "Putaran mesin stasioner stabil, respon gas baik, dan tidak ada kebocoran bahan bakar", "Mesin dapat berputar hingga 10.000 RPM tanpa beban", "Lampu depan menyala lebih terang"], correct: 2 },
        { q: "Penyebab utama dari timbulnya gejala 'kebanjiran' bensin pada karburator setelah dirakit kembali adalah...", options: ["Jarum pelampung terganjal kotoran atau aus sehingga tidak menutup rapat", "Main jet terlalu kecil", "Pilot jet tersumbat", "Setelan sekrup udara terlalu rapat", "Filter udara basah"], correct: 0 },
        { q: "Alat ukur yang digunakan untuk menyetel renggang celah katup (klep) sesuai spesifikasi BPR adalah...", options: ["Mistar baja", "Micrometer luar", "Dial indicator", "Feeler gauge (bilah ukur)", "Jangka sorong"], correct: 3 },
        { q: "Saat memasang kembali karburator ke intake manifold, hal penting yang harus dipastikan agar tidak terjadi kebocoran udara palsu adalah...", options: ["Baut manifold dikencangkan dengan las", "Manifold diisi oli pelumas", "Sekrup stasioner diputar habis ke kanan", "Selang bensin dilepas", "Gasket/O-ring isolator intake terpasang dengan baik dan tidak terjepit"], correct: 4 },
        { q: "Setelah menyelesaikan seluruh pekerjaan perawatan karburator, langkah K3 dan manajemen bengkel yang wajib dilakukan adalah...", options: ["Langsung menyerahkan kunci ke konsumen", "Pembersihan dan penataan kembali alat serta area kerja (Housekeeping)", "Membiarkan alat berserakan di atas meja", "Mencuci karburator lagi dengan air", "Mencatat nomor mesin"], correct: 1 },
        { q: "Pekerjaan penyervisan komponen pemasuk bahan bakar mekanis pada sepeda motor mencakup perawatan...", options: ["Sistem rem dan suspensi", "Sistem pengisian dan baterai", "Unit karburator dan saluran suplay bahan bakar", "Transmisi CVT", "Rantai roda dan sprocket"], correct: 2 },
        { q: "Mengatur sekrup udara (air screw) pada karburator tipe konvensional bertujuan untuk mendapatkan...", options: ["Campuran bahan bakar dan udara yang pas pada putaran stasioner", "Bukaan katup gas maksimal", "Tinggi pelampung yang pas", "Tegangan pegas skep", "Kecepatan maksimal motor"], correct: 0 },
        { q: "Pemeriksaan kabel gas melingkupi kelancaran gerak kabel. Jika kabel gas terasa seret saat diputar, tindakan perawatan pertama adalah...", options: ["Mengganti karburator baru", "Memotong kabel gas 2 cm", "Putar sekrup stasioner", "Memberikan cairan pelumas/penetran ke dalam selongsong kabel gas", "Kencangkan per skep"], correct: 3 },
        { q: "Elemen filter udara tipe kering (dry paper element) yang kotor oleh debu halus dapat dibersihkan dengan cara...", options: ["Dicuci dengan minyak tanah", "Dicuci dengan air sabun", "Rendam dalam oli mesin", "Disikat kasar dengan sikat cuci", "Disemprot udara bertekanan rendah dari arah dalam ke luar"], correct: 4 },
        { q: "Prosedur persiapan sebelum meloloskan karburator dari mesin meliputi pelepas komponen...", options: ["Busi, kabel spul, dan rantai", "Kabel choke, kabel gas, selang bensin, dan baut intake manifold", "Kabel kopling, oli mesin, dan knalpot", "Roda depan, spatbor, dan stang", "Aki, sekering, dan relay"], correct: 1 },
        { q: "Penyebab stasioner mesin naik-turun atau tidak mau langsam setelah karburator dibersihkan biasanya karena...", options: ["Bensin terlalu penuh di tangki", "Busi baru diganti", "Kebocoran udara pada intake manifold atau paking karburator", "Oli mesin baru", "Kabel gas terlalu kendur"], correct: 2 },
        { q: "Hasil pemeriksaan komponen main jet dan pilot jet yang baik saat dibersihkan adalah...", options: ["Lubang spuyer bersih dan terang saat diterawang tanpa sumbatan", "Lubang spuyer tersumbat kerak", "Lubang spuyer dibersihkan dengan kawat keras hingga membesar", "Lubang spuyer retak", "Spuyer diolesi lem paking"], correct: 0 },
        { q: "Alat yang digunakan untuk memutar sekrup penyetel stasioner dan sekrup udara pada karburator adalah...", options: ["Kunci ring 10-12", "Tang kombinasi", "Kunci L bintang", "Obeng minus (-) atau obeng khusus penyetel karburator", "Kunci sock 8"], correct: 3 },
        { q: "Kondisi skep/piston valve yang baret parah akan mengakibatkan gangguan mesin berupa...", options: ["Suara knalpot makin halus", "Pengapian hilang", "Bensin tidak mau mengalir dari tangki", "Oli mesin cepat habis", "Skep mudah tersangkut (gas macet) atau putaran mesin sulit turun"], correct: 4 },
        { q: "Tujuan pemeriksaan kebersihan area kerja setelah servis adalah untuk memenuhi prinsip K3 dan 5S, yaitu...", options: ["Memperlama waktu servis", "Mencegah bahaya kebakaran akibat ceceran bensin dan menjaga keselamatan kerja", "Memenuhi syarat pembuangan sampah berbayar", "Menunjukkan alat-alat baru", "Menghabiskan waktu jam kerja"], correct: 1 }
    ];

    // =========================================================================
    // LEVEL 12: Kopling (Manual/Otomatis), Oli Mesin/Transmisi & Pelumasan (25 Soal)
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[12] = [
        { q: "Pemeriksaan jarak main bebas (free play) pada tuas kopling manual sepeda motor standar BPR berada pada kisaran...", options: ["30 - 40 mm", "2 - 5 mm", "10 - 20 mm", "50 mm", "0 mm (tanpa jarak bebas)"], correct: 2 },
        { q: "Prosedur pemeriksaan kondisi oli mesin menggunakan tangkai pengukur (dipstick) yang BENAR adalah...", options: ["Motor distandar tengah di tempat datar, dipstick dibersihkan lalu dimasukkan tanpa diulirkan", "Motor dimiringkan ke kiri saat mengukur", "Motor distandar samping dan dipstick diulirkan rapat", "Mesin harus dalam keadaan hidup gas tinggi", "Oli diukur langsung dari lubang pembuangan"], correct: 0 },
        { q: "Perawatan unit pemindah tenaga pada sepeda motor manual atau otomatis meliputi pemeriksaan...", options: ["Sistem pengereman hidrolik", "Kelistrikan penerangan", "Tegangan pengisian aki", "Komponen kopling, jarak bebas tuas, dan perpindahan transmisi", "Tekanan ban depan"], correct: 3 },
        { q: "Pada pemeriksaan fisik oli mesin, indikasi oli yang sudah terkontaminasi oleh air pendingin (coolant) akan berwarna...", options: ["Hitam pekat", "Bening keemasan", "Merah terang", "Kuning jernih", "Cokelat keruh keabu-abuan / Putih seperti susu"], correct: 4 },
        { q: "Fungsi utama filter oli mesin tipe kertas pada sistem pelumasan sepeda motor adalah...", options: ["Mendinginkan oli mesin", "Menyaring serbuk logam dan kotoran halus sebelum oli mengalir ke komponen presisi", "Menambah volume oli", "Setel tekanan oli", "Memisahkan bensin dari oli"], correct: 1 },
        { q: "Jarak main bebas pedal pindah gigi (persneling) pada sepeda motor tipe bebek (kopling otomatis) disetel melalui...", options: ["Kabel gas di stang", "Penyetel rantai roda", "Baut penyetel kopling di bak kanan dengan mengendurkan mur pengunci lalu memutar bautnya", "Baut drain oli", "Kabel spedometer"], correct: 2 },
        { q: "Pemeriksaan keausan kanvas kopling (clutch friction disc) secara visual dilakukan dengan melihat...", options: ["Ketebalan alur kanvas kopling dan tanda bekas terbakar/hangus", "Warna cat plat kopling", "Diameter luar rumah kopling", "Jumlah pegas kopling", "Panjang kabel kopling"], correct: 0 },
        { q: "Tingkat kekentalan oli pelumas mesin sepeda motor dinyatakan dalam indeks standar...", options: ["API Service", "JASO MA/MB", "DOT 3", "SAE (Society of Automotive Engineers)", "ISO 9001"], correct: 3 },
        { q: "Penggunaan oli mesin dengan standar JASO MB ditujukan khusus untuk sepeda motor tipe...", options: ["Motor bebek transmisi manual", "Motor sport kopling basah", "Motor 2-tak", "Motor listrik", "Motor matic (CVT) dengan kopling kering"], correct: 4 },
        { q: "Penyebab utama timbulnya slip kopling saat sepeda motor diakselerasi adalah...", options: ["Celah katup terlalu renggang", "Kanvas kopling aus atau setelan jarak bebas kopling terlalu rapat", "Rantai roda kendor", "Busi kotor", "Oli transmisi terlalu encer"], correct: 1 },
        { q: "Pemeriksaan berkala volume oli transmisi (oli gardan) pada sepeda motor matic dilakukan melalui...", options: ["Kaca pengintip tangki bensin", "Baut kepala silinder", "Baut lubang pemeriksa/pengisian oli transmisi pada bak reduksi belakang", "Dipstick oli mesin", "Lubang filter udara"], correct: 2 },
        { q: "Akibat yang ditimbulkan jika baut pembuangan oli (drain plug) dikencangkan melebihi momen spesifikasi BPR adalah...", options: ["Drat baut pembuangan pada crankcase menjadi dol/drod/retak", "Mesin menjadi lebih dingin", "Oli mesin mengalir lebih lancar", "Kopling menjadi lebih empuk", "Gigi persneling mudah dipindah"], correct: 0 },
        { q: "Spesifikasi oli pelumas untuk transmisi reduksi motor matic umumnya menggunakan oli dengan viskositas...", options: ["SAE 90", "Minyak rem DOT 4", "Oli samping 2-tak", "SAE 10W-30 / SAE 20W-50", "Air murni"], correct: 3 },
        { q: "Prosedur servis berkala pelumasan mesin kendaraan bermotor meliputi...", options: ["Mengganti ban dan pelampung", "Setel velg dan komstir", "Ganti cairan rem dan seal", "Setel lampu dan klakson", "Pemeriksaan volume, warna, viskositas, kontaminasi, serta penggantian oli dan filter"], correct: 4 },
        { q: "Pemeriksaan kelancaran gerak perpindahan gigi transmisi pada motor bebek/sport dilakukan dengan cara...", options: ["Memutar stang kemudi", "Menekan pedal persneling sambil menguji kerapatan perpindahan gigi saat roda diputar", "Menekan tuas rem depan", "Mendorong motor tanpa rantai", "Mencabut kunci kontak"], correct: 1 },
        { q: "Pekerjaan inspeksi aliran pelumasan mesin dilakukan dengan memantau aliran oli pada...", options: ["Lubang indikator oli di kepala silinder saat mesin dihidupkan", "Tangki bensin", "Knalpot belakang", "Mangkuk karburator", "Kotak filter udara"], correct: 2 },
        { q: "Pemeriksaan kontaminasi oli mesin dilakukan dengan mengamati...", options: ["Terdapatnya serbuk gram logam, endapan lumpur (sludge), atau ceceran bensin/air pada oli", "Bau oli saja", "Berat wadah oli", "Harga oli", "Merek oli"], correct: 0 },
        { q: "Fungsi dari pegas kopling (clutch spring) pada unit kopling manual adalah...", options: ["Melumasi kanvas", "Menghubungkan kabel gas", "Menahan poros engkol", "Menekan plat dan kanvas kopling agar saling merapat dan memindahkan tenaga", "Mendorong pedal transmisi"], correct: 3 },
        { q: "Gejala yang dirasakan saat pengendara memindahkan gigi transmisi jika setelan kopling terlalu kendur adalah...", options: ["Kopling slip pada kecepatan tinggi", "Mesin mati tiba-tiba", "Suara knalpot meletup", "Rem belakang terkunci", "Perpindahan gigi terasa kasar/keras dan motor cenderung jalan sendiri saat tuas ditarik"], correct: 4 },
        { q: "Penggantian washer/ring paking alumunium pada baut pembuangan oli mesin setiap kali servis bertujuan untuk...", options: ["Menaikkan tekanan oli", "Mencegah kebocoran rembesan oli dari celah baut pembuangan", "Mempercepat alir buang", "Variasi warna baut", "Menahan baut agar tidak hilang"], correct: 1 },
        { q: "Standar pergantian oli mesin sepeda motor harian sesuai buku pedoman reparasi umumnya dilakukan setiap kisaran...", options: ["10.000 - 15.000 km", "500 km", "2.000 - 4.000 km", "20.000 km", "100 km"], correct: 2 },
        { q: "Pemeriksaan kerapatan sistem pelumasan mesin bertujuan untuk memastikan...", options: ["TIDAK ADA kebocoran oli pada paking crankcase, seal oil, atau baut kuras", "Warna cat mesin", "Jumlah baut mesin genap", "Tebal blok silinder", "Kecepatan pompa oli"], correct: 0 },
        { q: "Minyak pelumas yang sudah encer (viskositas rusak akibat usia pakai) ditandai dengan...", options: ["Warna menjadi bening", "Oli terasa sangat lengket", "Oli berubah jadi padat", "Oli terasa licin seperti air tanpa kekentalan saat diusap jari", "Oli berbau wangi"], correct: 3 },
        { q: "Pada motor matic, penggantian oli reduksi/gardan dilakukan dengan rasio berkala dibanding oli mesin yaitu...", options: ["1 : 1 (Setiap ganti oli mesin)", "10 : 1", "5 : 1", "Tidak perlu diganti", "2 : 1 atau 3 : 1 (Setiap 2-3 kali ganti oli mesin)"], correct: 4 },
        { q: "Prosedur pengukuran volume oli bekas yang ditampung saat kuras berfungsi untuk...", options: ["Menjual kembali oli bekas", "Mengetahui adanya indikasi kebocoran oli atau penguapan oli berlebih di dalam mesin", "Mengisi oli ke motor lain", "Memastikan filter oli rusak", "Membersihkan karter"], correct: 1 }
    ];

    // =========================================================================
    // LEVEL 13: Sistem CVT, Sistem Pendingin & Sistem Injeksi (25 Soal)
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[13] = [
        { q: "Pemeriksaan komponen sabuk penggerak (V-Belt) pada sistem CVT sepeda motor matic melingkupi...", options: ["Panjang rantai", "Jumlah gigi sprocket", "Lebar V-Belt, keretakan pada gigi V-Belt, dan keausan sisi samping", "Kadar oli sabuk", "Tekanan angin sabuk"], correct: 2 },
        { q: "Pemeriksaan komponen Roller (Weight Roller) pada CVT dilakukan dengan melihat kondisi fisik berupa...", options: ["Warna roller", "Diameter dalam roller", "Berat minyak roller", "Keausan pipih/gepeng pada permukaan roller dan kelancaran gerak roller", "Keharuman roller"], correct: 3 },
        { q: "Pemberian Grease / Gemuk khusus CVT (High Temperature Grease) HANYA diperbolehkan pada area...", options: ["Sabuk V-Belt dan permukaan puli sliding", "Gigi pemutar starter", "Poros slider dan bearing piringan Driven Pulley (Puli Belakang)", "Seluruh permukaan roller", "Kampas kopling ganda"], correct: 2 },
        { q: "Gejala berupa getaran/gredek pada putaran awal (stasioner ke jalan) motor matic umumnya disebabkan oleh...", options: ["Roller baru", "V-belt baru", "Air radiator penuh", "Busi mati", "Kampas kopling ganda (centrifugal clutch) licin/kotor oleh debu atau oli"], correct: 4 },
        { q: "Alat khusus yang digunakan untuk menguji kebocoran radiator dan tekanan kerja tutup radiator adalah...", options: ["Compression tester", "Multimeter", "Radiator Cap & System Tester", "Feeler gauge", "Hydrometer"], correct: 2 },
        { q: "Pemeriksaan kondisi air pendingin (coolant) di dalam tangki cadangan (reservoir tank) dipastikan berada di antara garis...", options: ["LOWER dan UPPER level", "Di atas garis UPPER", "Di bawah garis LOWER", "Tangki harus penuh bersisa 1 cm", "Tangki harus kosong"], correct: 0 },
        { q: "Pekerjaan servis berkala pada unit CVT motor matic meliputi pemeriksaan...", options: ["Lantai pijakan kaki", "Minyak rem belakang", "Tekanan ban depan", "Kondisi V-belt, roller, rumah roller, sliding sheath, dan kebersihan ruang CVT", "Setel velg jari-jari"], correct: 3 },
        { q: "Pemeriksaan komponen rumah roller (movable drive face) melingkupi...", options: ["Kondisi got/jalur roller tidak tergerus dan bushing sliding tidak kocak", "Warna sirip kipas", "Tebal paking bak CVT", "Panjang baut bak CVT", "Kebersihan saringan oli"], correct: 0 },
        { q: "Jika V-Belt terolesi oleh cairan grease/gemuk, akibat yang timbul pada akselerasi motor matic adalah...", options: ["Motor jalan lebih kencang", "V-Belt makin awet", "Suara CVT makin halus", "Bensin makin irit", "CVT akan mengalami slip parah dan motor tidak mau jalan/akselerasi lemas"], correct: 4 },
        { q: "Pemeriksaan rutin pada sistem pendingin cair (liquid cooling) sepeda motor melingkupi...", options: ["Jumlah sirip radiator", "Kondisi kebocoran radiator, fungsi tutup radiator, level reservoir, serta kondisi kisi/kipas", "Warna selang", "Jenis cairan pembersih bodi", "Tegangan aki"], correct: 1 },
        { q: "Pemeriksaan kondisi fisik sirip-sirip (core) radiator bertujuan untuk memastikan...", options: ["Sirip berwarna hitam", "Sirip dilepas", "Sirip tidak tersumbat kotoran/debu dan tidak bengkok tertutup", "Jumlah sirip genap", "Sirip dilapisi cat tebal"], correct: 2 },
        { q: "Fungsi thermostat pada sistem pendingin cairan sepeda motor adalah...", options: ["Menutup saluran ke radiator saat mesin dingin dan membuka saat suhu mesin mencapai ~80°C", "Memompa air pendingin", "Mendinginkan air radiator", "Menyimpan air cadangan", "Meringankan kerja kipas"], correct: 0 },
        { q: "Pemeriksaan komponen utama sistem bahan bakar injeksi PGM-FI/EFI melingkupi...", options: ["Gigi rasio dan roda", "Aki dan klakson", "Rantai dan gir", "Throttle Body, injektor, sensor-sensor utama, dan tekanan pompa bahan bakar", "Setel rem"], correct: 3 },
        { q: "Pemeriksaan komponen Throttle Body pada motor injeksi melingkupi...", options: ["Kebersihan saluran udara, katup kupu-kupu (butterfly valve), dan sensor IACV/FID", "Pemeriksaan oli mesin", "Pemeriksaan busi", "Pemeriksaan celah klep", "Pemeriksaan tekanan ban"], correct: 0 },
        { q: "Pemeriksaan tekanan kerja pompa bahan bakar (fuel pump) sepeda motor injeksi menggunakan alat...", options: ["Compression tester", "Vacuum gauge", "Multimeter", "Fuel Pressure Gauge", "Hydrometer"], correct: 3 },
        { q: "Tekanan bensin standar yang dihasilkan oleh Fuel Pump sepeda motor Honda PGM-FI saat kontak ON adalah sekitar...", options: ["100 kPa", "500 kPa", "294 kPa (2,94 kgf/cm² / 42 psi)", "10 kPa", "10 psi"], correct: 2 },
        { q: "Komponen yang memicu semprotan bahan bakar dari injektor secara presisi berdasarkan sinyal masa dari ECM adalah...", options: ["Solenoid Injektor", "Fuel pump", "Pressure regulator", "Filter bensin", "Busi"], correct: 0 },
        { q: "Pemeriksaan keberadaan kebocoran pada selang/saluran bahan bakar tekanan tinggi dilakukan dengan cara...", options: ["Mencuci selang dengan bensin", "Meniup selang dengan mulut", "Membakar ujung selang", "Pemeriksaan visual saat kunci kontak di-ON-kan (fuel pump pressurize)", "Melepas selang saat mesin hidup"], correct: 3 },
        { q: "Gejala yang mengindikasikan bahwa filter bahan bakar (fuel strainer) di dalam tangki tersumbat adalah...", options: ["Motor melaju sangat kencang", "Lampu MIL berkedip 12 kali", "Motor terasa brebet/pingsan pada putaran tinggi akibat suplai bensin tertahan", "Oli mesin cepat habis", "Aki tekor"], correct: 2 },
        { q: "Pemeriksaan kebersihan filter udara pada cover CVT motor matic bertujuan untuk...", options: ["Mendinginkan mesin", "Menyaring oli gardan", "Menambah akselerasi", "Mencegah debu masuk ke ruang CVT yang dapat mengikis V-belt dan roller", "Mencegah rem aus"], correct: 3 },
        { q: "Bila seal oli poros engkol (crankshaft oil seal) pada bak CVT kanan/kiri bocor, akibatnya adalah...", options: ["Mesin menjadi sangat dingin", "Aki tidak bisa terisi", "Oli mesin/gardan akan masuk membasahi ruang CVT dan menyebabkan slip", "Bensin meluap", "Rem cakram terkunci"], correct: 2 },
        { q: "Pemeriksaan kondisi kipas pendingin radiator elektrik meliputi...", options: ["Kelancaran putaran kipas dan fungsi otomatis sakelar suhu (thermoswitch)", "Warna baling-baling", "Jumlah baling-baling", "Berat kipas", "Bentuk dudukan kipas"], correct: 0 },
        { q: "Suhu pembukaan awal thermostat pada sebagian besar sepeda motor bebek/sport adalah sekitar...", options: ["50°C", "100°C", "120°C", "80°C - 84°C", "30°C"], correct: 3 },
        { q: "Pemeriksaan kekencangan klem selang radiator bertujuan untuk...", options: ["Mempercepat alir air", "Menambah estetika", "Memudahkan pelepasan selang", "Menahan thermostat", "Mencegah kebocoran cairan pendingin saat sistem bertekanan tinggi"], correct: 4 },
        { q: "Pembersihan permukaan Throttle Body dari jelaga jelaga karbon dilakukan menggunakan...", options: ["Amplas keping", "Inversion spray / Throttle body cleaner khusus FI", "Sikat kawat besi", "Air sabun colek", "Oli bekas"], correct: 1 }
    ];

    // =========================================================================
    // LEVEL 14: Alat Diagnostik (Scanner OBD-II/MST), Baterai, Busi & Instrumen Kelistrikan (25 Soal)
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[14] = [
        { q: "Pekerjaan perawatan berkala pada unit injektor sepeda motor FI meliputi...", options: ["Pembersihan kerak lubang semprotan injektor, tes debit semprotan, dan pemeriksaan kebocoran seal", "Ganti kabel busi", "Setel klep", "Ganti filter oli", "Setel rantai"], correct: 0 },
        { q: "Langkah pertama sebelum menggunakan alat diagnostic scanner pada sepeda motor injeksi adalah...", options: ["Membuka jok dan tangki", "Membongkar mesin", "Menghubungkan soket scanner ke DLC (Data Link Connector) motor dan menghidupkan kunci kontak", "Melepas aki", "Mencuci motor"], correct: 2 },
        { q: "Saat membaca 'Live Data Stream' menggunakan scanner diagnostik pada kondisi stasioner, putaran mesin standar menunjukkan angka...", options: ["500 - 800 RPM", "2500 - 3000 RPM", "1400 - 1600 RPM", "5000 RPM", "0 RPM"], correct: 2 },
        { q: "Pada layar scanner diagnostik, pembacaan parameter bukaan Throttle Position (TP) sensor saat gas DITUTUP RAPAT harus menunjukkan angka...", options: ["100%", "50%", "0,0° atau 0,0%", "12 Volt", "45°"], correct: 2 },
        { q: "Sebaliknya, pembacaan parameter TP sensor pada scanner saat stang gas DIBUKA FULL / MAXIMAL harus berkisar...", options: ["0°", "10°", "180°", "75° - 82° (atau ~100%)", "360°"], correct: 3 },
        { q: "Sensor IAT (Intake Air Temperature) pada live data scanner diagnostik berfungsi menampilkan...", options: ["Suhu oli mesin", "Suhu cairan radiator", "Suhu udara yang masuk melalui filter udara ke intake manifold", "Suhu gas buang", "Suhu ruang kerja"], correct: 2 },
        { q: "Sensor MAP (Manifold Absolute Pressure) pada live data scanner diagnostik menampilkan...", options: ["Nilai tekanan udara di dalam saluran intake manifold", "Tekanan oli", "Tekanan ban", "Tekanan bensin", "Tekanan rem"], correct: 0 },
        { q: "Pemeriksaan kondisi baterai (aki) sepeda motor meliputi pengujian...", options: ["Warna wadah aki", "Bentuk terminal", "Kebersihan terminal, tegangan statis, kapasitas daya tahanan, dan berat jenis elektrolit", "Tebal kabel", "Merk baterai"], correct: 2 },
        { q: "Pemeriksaan kondisi fisik terminal baterai melingkupi...", options: ["Warna cat aki", "Berat aki", "Merek aki", "Kebersihan terminal dari kerak sulfasi putih dan kekencangan baut terminal", "Panjang kabel aki"], correct: 3 },
        { q: "Pengukuran tegangan statis baterai 12V (keadaan mesin mati) yang masih baik harus menunjukkan tegangan di atas...", options: ["10,0 Volt", "8,0 Volt", "15,0 Volt", "12,4 Volt - 12,8 Volt", "6,0 Volt"], correct: 3 },
        { q: "Pengukuran berat jenis (BJ) cairan elektrolit baterai basah kondisi penuh menggunakan Hydrometer pada suhu 20°C berada pada nilai...", options: ["1,260 - 1,280", "1,000", "1,500", "0,800", "2,000"], correct: 0 },
        { q: "Pemeriksaan dan perawatan berkala pada busi sepeda motor meliputi...", options: ["Warna cat busi", "Pembersihan kerak karbon, pengukuran celah elektroda, dan tes nilai tahanan cap busi", "Ukuran diameter ulir", "Ganti kabel busi", "Setel kunci kontak"], correct: 1 },
        { q: "Pemeriksaan celah (gap) elektroda busi standar menggunakan Feeler Gauge sesuai BPR berkisar antara...", options: ["0,10 - 0,20 mm", "2,0 - 3,0 mm", "0,01 mm", "0,80 - 0,90 mm", "1,5 cm"], correct: 3 },
        { q: "Pemeriksaan nilai tahanan penutup busi (spark plug cap / kop busi) menggunakan Multimeter skala Ohm berkisar...", options: ["0 \\Omega", "100 M\\Omega", "1 \\Omega", "3,75 - 5,00 k\\Omega", "100 k\\Omega"], correct: 3 },
        { q: "Kondisi elektroda busi yang menunjukkan hasil pembakaran sempurna berwarna...", options: ["Hitam pekat basah oli", "Hitam berkerak tebal", "Putih pucat meleleh", "Kuning mengkilap", "Cokelat kemerahan / Abu-abu terang dan kering"], correct: 4 },
        { q: "Pemeriksaan sistem instrumen sinyal dan penerangan pada sepeda motor melingkupi pengujian...", options: ["Fungsi sakelar, lampu dekat/jauh, lampu sein, lampu rem, lampu senja, dan klakson", "Tegangan pengisian", "Putaran stasioner", "Tekanan kompresi", "Celah katup"], correct: 0 },
        { q: "Pemeriksaan instrumen kelistrikan sinyal dan penerangan melingkupi fungsi dari...", options: ["Lampu indikator rumah saja", "Pengapian busi", "Lampu sakelar penerangan, lampu dekat/jauh, lampu sein, lampu rem, lampu belakang, dan horn/klakson", "Pengisian spul", "Motor starter"], correct: 2 },
        { q: "Alat pembersih injektor (Injector Cleaner Tester Tool) digunakan untuk...", options: ["Mengecas aki", "Membaca kode MIL", "Membersihkan deposit kotoran pada nozzle injektor dan menguji debit serta pola semprotan", "Setel celah katup", "Menguji kompresi"], correct: 2 },
        { q: "Pengujian 'Kesehatan Baterai' (%) pada battery tester digital dihitung berdasarkan nilai...", options: ["Berat baterai", "Tinggi air aki", "Warna wadah", "Luas terminal", "CCA (Cold Cranking Amps) dan ketahanan tegangan dalam beban"], correct: 4 },
        { q: "Bila pengukuran ketinggian air baterai basah berada di bawah garis 'LOWER LEVEL', tindakan perawatan yang BENAR adalah...", options: ["Menambahkan Air Zuur pekat (Tutup Merah)", "Menambahkan Air Aki Murni (Air Suling / Tutup Biru) hingga batas UPPER LEVEL", "Menambahkan air keran biasa", "Menguras seluruh air aki", "Membiarkan saja"], correct: 1 },
        { q: "Sensor O2 pada data scanner diagnostik yang bekerja normal akan menampilkan sinyal tegangan yang...", options: ["Konstan di 12 Volt", "Selalu 0 Volt", "Berfluktuasi cepat antara 0,1 Volt sampai 0,9 Volt", "Konstan di 5 Volt", "Negative 1 Volt"], correct: 2 },
        { q: "Kondisi elektroda busi yang berwarna putih kering melepuh mengindikasikan bahwa...", options: ["Bensin terlalu banjir", "Oli bocor", "Busi baru", "Campuran bahan bakar terlalu irit (lean) atau tingkat panas busi terlalu dingin", "Pengapian terlambat"], correct: 3 },
        { q: "Alat ukur yang digunakan untuk mengecek kontinyuitas (keutuhan) filamen bohlam lampu adalah...", options: ["Feeler gauge", "Hydrometer", "Multimeter pada sakelar Ohm / Buzzer", "Scanner OBD", "Micrometer"], correct: 2 },
        { q: "Pemeriksaan fungsi sakelar lampu rem (brake light switch) memastikan bahwa lampu rem menyala saat...", options: ["Tuas rem depan atau pedal rem belakang ditarik/ditekan sedikit", "Kunci kontak OFF", "Tombol starter ditekan", "Stang dibelokkan", "Motor distandar tengah"], correct: 0 },
        { q: "Penyebab utama dari lampu sein berkedip terlalu cepat (hyper flash) adalah...", options: ["Aki terlalu penuh", "Kiprok rusak", "Spul putus", "Sakelar aus", "Daya watt bohlam replacement lebih kecil dari standar atau salah satu bohlam putus"], correct: 4 }
    ];

    // =========================================================================
    // LEVEL 15: Pemeliharaan Sasis Kompleks - Rantai, Roda, Rem, Kemudi & Suspensi (25 Soal)
    // =========================================================================
    window.MASTER_QUESTION_BANK.otomotif[15] = [
        { q: "Pemeriksaan dan penggantian unit rantai roda (drive chain) melingkupi...", options: ["Lebar velg", "Tekanan ban", "Pemeriksaan kekendoran/jarak main rantai, keausan gigi sprocket, dan pelumasan rantai", "Tinggi shockbreaker", "Suhu roda"], correct: 2 },
        { q: "Penyetelan jarak main bebas (kekendoran) rantai roda sepeda motor bebek/sport standar BPR adalah...", options: ["5 - 10 mm", "50 - 60 mm", "20 - 30 mm", "0 mm", "100 mm"], correct: 2 },
        { q: "Pelumasan rantai roda sepeda motor yang BENAR sesuai lembar kerja BPR adalah menggunakan...", options: ["Gemuk/grease tebal", "Minyak goreng bekas", "Cairan rem DOT 3", "Oli khusus rantai (Chain Lube) atau oli SAE 80-90", "Air sabun"], correct: 3 },
        { q: "Pemeriksaan keausan komponen Gear Sprocket Set (Sprocket depan & belakang) ditandai dengan...", options: ["Warna sprocket jadi hitam", "Diameter sprocket bertambah", "Jumlah gigi bertambah", "Sprocket bersih", "Bentuk gigi-gigi sprocket yang sudah runcing, tajam, atau tergerus melengkung"], correct: 4 },
        { q: "Pemeriksaan keolengan (run-out) roda depan dan belakang melingkupi...", options: ["Pengukuran keolengan arah radial (lingkaran) dan axial (kesamping) menggunakan dial indicator", "Tebal ban", "Lebar rantai", "Diameter as roda", "Warna cat velg"], correct: 0 },
        { q: "Pemeriksaan keolengan (run-out) velg roda depan dan belakang menggunakan alat ukur...", options: ["Jangka sorong", "Feeler gauge", "Micrometer", "Dial Indicator (Dial Gauge) dan Stand Penyangga", "Mistar gulung"], correct: 3 },
        { q: "Batas maksimum keolengan melingkar (radial) dan menyamping (axial) velg roda sepeda motor standar BPR adalah...", options: ["0,01 mm", "2,0 mm", "10,0 mm", "5,0 mm", "0,1 mm"], correct: 1 },
        { q: "Pemeriksaan dan perawatan sistem pengereman hidrolik (rem cakram) melingkupi...", options: ["Warna kaliper", "Jenis velg", "Merek kanvas", "Pemeriksaan ketebalan pad rem, level minyak rem, kinerja tuas, dan keolengan piringan cakram", "Diameter selang"], correct: 3 },
        { q: "Pada pemeriksaan rem cakram hidrolik, batas ketebalan minimum kanvas rem (pad set) yang masih aman adalah...", options: ["5,0 mm", "10,0 mm", "0 mm", "0,1 mm", "1,0 - 2,0 mm (atau sampai batas garis indikator aus)"], correct: 4 },
        { q: "Pemeriksaan ketinggian permukaan minyak rem pada reservoir master silinder ditunjukkan oleh garis...", options: ["UPPER saja", "LOWER / MIN", "TOP", "FULL", "MAX"], correct: 1 },
        { q: "Pemeriksaan jarak main bebas tuas rem cakram depan standar BPR berada pada kisaran...", options: ["2 - 5 mm", "30 - 40 mm", "10 - 20 mm", "50 mm", "0 mm"], correct: 2 },
        { q: "Pada pemeriksaan rem tromol (Drum Brake) depan/belakang, ketebalan kanvas rem (brake shoe) minimal adalah...", options: ["10,0 mm", "0,5 mm", "0 mm", "2,0 - 3,0 mm", "5,0 mm"], correct: 3 },
        { q: "Jarak main bebas pedal rem belakang tipe tromol standar BPR berada pada kisaran...", options: ["20 - 30 mm", "5 - 10 mm", "50 - 60 mm", "0 mm", "100 mm"], correct: 0 },
        { q: "Pemeriksaan dan perawatan sistem kemudi (steering system) melingkupi...", options: ["Pemeriksaan gerak stang kemudi, kelonggaran poros kemudi (komstir), dan kekencangan mur pengunci", "Tebal ban", "Ukuran segitiga", "Warna stang", "Panjang kabel gas"], correct: 0 },
        { q: "Pemeriksaan gerak stang kemudi melingkupi kelancaran putaran ke kiri dan ke kanan tanpa ada rasa...", options: ["Suara mesin", "Bocoran oli", "Getaran ban", "Ganjalan, berat, atau 'terkunci' di bagian tengah (keausan komstir)", "Getaran knalpot"], correct: 3 },
        { q: "Pemeriksaan kelonggaran poros kemudi (steering stem) dilakukan dengan cara...", options: ["Memutar stang gas", "Menekan tuas rem", "Menarik/mendorong garpu depan ke depan-belakang pada posisi motor distandar tengah", "Memutar roda belakang", "Menduduki jok"], correct: 2 },
        { q: "Pemeriksaan dan perawatan sistem suspensi sepeda motor melingkupi...", options: ["Panjang garpu saja", "Warna oli shock", "Kondisi fisik as shock/inner tube, kebocoran seal oli shock, dan fungsi gerakan redaman", "Tebal per", "Merk peredam"], correct: 2 },
        { q: "Pemeriksaan fisik pada pipa dalam garpu depan (inner tube / as shock) melingkupi...", options: ["Warna cat as", " Diameter luar pipa 50 cm", "Berat pipa", "Kondisi permukaan melengkung/bengkok, baret/goresan, dan kebocoran seal oli", "Merk shock"], correct: 3 },
        { q: "Pemeriksaan kondisi suspensi belakang (rear cushion / monoshock) melingkupi...", options: ["Kekencangan rantai", "Lebar velg", "Tekanan ban", "Setelan rem", "Kebocoran oli pada batang peredam, kondisi karet bushing, dan fungsi redaman (rebound)"], correct: 4 },
        { q: "Pekerjaan pelepasan dan pemasangan cover body sepeda motor melingkupi...", options: ["Identifikasi jenis pengikat (baut, sekrup, plastic clip/rivet) dan kerapatan sambungan bodi", "Mencuci bodi dengan sabun", "Mengecat bodi", "Menempel stiker", "Memotong klip"], correct: 0 },
        { q: "Pemeriksaan jalur pengikat cover body sepeda motor melingkupi jenis pengikat...", options: ["Paku kawat", "Lem besi", "Baut, sekrup tapping, dan plastic clip (rivet)", "Kawat bendrat", "Tali karet"], correct: 2 },
        { q: "Pemeriksaan rangka (Chassis) utama sepeda motor melingkupi...", options: ["Inspeksi retakan rangka, kebingkokan, bekas las tidak standar, serta dudukan mesin (engine mounting)", "Warna cat rangka", "Nomor rangka saja", "Merek rangka", "Berat rangka"], correct: 0 },
        { q: "Pemeriksaan inspeksi visual pada rangka (frame) utama sepeda motor melingkupi...", options: ["Warna cat rangka", "Nomor rangka saja", "Merek rangka", "Periksa adanya retakan, kebingkokan, bekas las tidak standar, atau korosi parah", "Berat rangka"], correct: 3 },
        { q: "Pemeriksaan kondisi dudukan mesin (engine mounting) melingkupi...", options: ["Warna baut", "Panjang baut", "Periksa kekencangan baut engine mounting dan kondisi bushing/rubber mount dari keretakan/Pecah", "Posisi filter", "Posisi knalpot"], correct: 2 },
        { q: "Pemeriksaan fungsi dan kondisi standar samping (side stand) serta standar tengah (main stand) memastikan bahwa...", options: ["Standar dicat ulang", "Tinggi standar 1 meter", "Standar dikunci mati", "Tanpa karet penahan", "Pegas pengembali bekerja baik dan posisi standar tidak bengkok/oblak"], correct: 4 }
    ];

}
